### ISSUE TITLE
Specify Type quick fix uses undenoteable type

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-ide-eclipse#1011]
```ceylon
object o {
    shared class C() {}
}
value v = o.C();
```
If you use the Specify Type quick fix on `value`, it adds the type `o.C`, which doesn’t even parse. Not sure what it *should* do… probably use the best denoteable type (in this case, `Basic`).

**Comment by gavinking** [comment]
This was fixed a while ago.
