### ISSUE TITLE
quick fix to propose member to fix typing error 

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1079]
If I have a typing error here:

    void bar(Bar bar) {}
    class Foo(shared Bar bar) {}
    Foo foo = Foo(...);
    bar(foo); //error

I would like a quick fix that proposes:

    void bar(Bar bar) {}
    class Foo(shared Bar bar) {}
    Foo foo = Foo(...);
    bar(foo.bar);

**Comment by lucaswerkmeister** [comment]
Is there an invisible `foo` declaration somewhere in the example code? I don’t see how the IDE could otherwise deduce that `<unknown type>.bar` has type `Bar`.

**Comment by gavinking** [comment]
@lucaswerkmeister yes.

**Comment by gavinking** [comment]
Done.
