### ISSUE TITLE
Spurious error when adding a method to an interface and its implementation

### ISSUE THREAD

**Issue by PhiLhoSoft** [ceylon/ceylon-ide-eclipse#1105]
I have an interface I and an implementation C.
I add a new method to I: `shared formal void addStuff(Stuff s);`
Eclipse tells me the implementation is missing in C.
I type in C `add` then hit Ctrl+Space and choose at the bottom of the list the default implementation of the method.
Auto-completion does its job and add an implementation with an empty body.
I add some code in the body.
I get a red marker, with two notices:
- refines I.addStuff
- Method does not override or implement a method from a supertype
A bit contradictory...
If I clean the project, the error disappears.

Using Ceylon 1.1 with plugin from official dev channel.

**Comment by gavinking** [comment]
Closing.
