### ISSUE TITLE
Autocompletion on camel case

### ISSUE THREAD

**Issue by PhiLhoSoft** [ceylon/ceylon-ide-eclipse#1118]
Following my request, Gavin implemented autocompletion on initials of identifiers:
cML + Ctrl+Space => currentMaxLevel
POI  + Ctrl+Space => PreOrderIteration
if they are unambiguous and in the scope, of course.
In case of ambiguity, a list is proposed to choose one of the choices.

OK, but I would appreciate if it supported camel case as well (like Eclipse in Java mode):
cML can lead to currentMaxLevel or compareMeasureLines
so I type cuML + Ctrl+space to quickly have an unambiguous choice and direct autocompletion.
Likewise, POI can be PreOrderIteration or PrimaryOffsetIndentation, I would like to type PrOrIt, for example (or POrIt or whatever combination) to get direct autocompletion on my hinted choice.

In a related request, I would prefer to have local variables and other identifiers before keywords and library choices: I more often want autocompletion on `readValue` (local variable or field) than on `return`...
Ideally, the closer (in terms of scope) the identifier is from the caret, the higher it should be on the list.

Thank you.

**Comment by gavinking** [comment]
I already implemented this.
