### ISSUE TITLE
Warning suppression

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-ide-eclipse#1184]
ceylon/ceylon-compiler#1866 adds support to the JVM compiler to suppress warnings generated by the typechecker using either a command line option or the `suppressWarnings` annotation. 

The IDE should support both ways of suppressing warnings.

**Comment by gavinking** [comment]
This is done, as far as I'm concerned. If the IDE setting is supposed to be somehow integrated with the compiler config file, then someone else needs to do that bit, @quintesse, or someone.

**Comment by quintesse** [comment]
I'm looking into this because indeed it has to be synced with the config file. But I was wondering @gavinking , why is this using a text box and not a list of checkboxes or something like that?

**Comment by gavinking** [comment]
@quintesse well the list of legal warning types is currently undocumented.

**Comment by quintesse** [comment]
But isn't it part of the typechecker? In the `com.redhat.ceylon.compiler.typechecker.analyzer.Warning` enumeration?

**Comment by gavinking** [comment]
A Java class inside the typechecker is "documentation"?

**Comment by quintesse** [comment]
Well what better than the actual code???

**Comment by quintesse** [comment]
Anyway the options are now read/written from/to the config file.

**Comment by quintesse** [comment]
Now we have checkboxes, nice, but certain options are combined, so if my config file contains just "ceylonNamespace" and open it the IDE it won't show up and if you change anything it disappears.
