### ISSUE TITLE
quick assist: use constructor

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-ide-eclipse#1207]
It would be nice if the IDE could convert a class such as

    class Example(String foo) extends Foo(foo) {
        // intializer statements...
        // declaration section
    }

to the equivalent class using a constructor:

    class Example extends Foo {
        // initializer statements...
        shared new Example(String foo) extends Foo(foo) {
        }
        // declaration section
    }

And I suppose in a class with (just) a default constructor there's the reverse transformation too.

**Comment by gavinking** [comment]
I did most of the work on this earlier. I've just finished it off today.
