### ISSUE TITLE
Run As > Ceylon Java Application is messed up

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-ide-eclipse#1211]
* With `void test() {}` and **Run > Run As > Ceylon Java Application** I get a dialog box "No ceylon runnable element". There should be an explanation that it needs to be shared.
* If I make `test()` shared I can run it. If I then make is non-shared I can *still* run it via **Run > Run History > ...**. I should get the same response as when I try to run it directly.
* If I add a non-defaulted parameter to `test()` (it's shared again now) then and I try to run it not via history I get the same dialog.
* But if I run it out of the history again then I get an error message in the dialog:

    > ceylon run: Cannot run toplevel method 'jsonsl.test': it should have no
      parameters or they should all have default values.

    But this message doesn't mention the need for `shared`!

**Comment by gavinking** [comment]
Fixed.
