### ISSUE TITLE
Auto-close ' is messed up

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-ide-eclipse#1217]
case( ) {
    //   ^ caret here: when I type ' I get a closing ' inserted.
    //     If I type a closing ' myself then it overtypes the
    //    auto inserted one. Fine.
    }
    case( "whatever") {
    //   ^ caret here: when I type ' I don't get a closing ' inserted.
    //     If I type a closing ' myself then it 
    //    inserts one. Fine.
    }
    case( "whatever") {
    //   ^ with the string literal selected (so deleted on keypress): 
    //     When I type ' I don't get a closing ' inserted.
    //    If I then type a closing ' myself then two get inserted.
    }
    case( 'x') {
    //   ^ with the character literal selected (so deleted on keypress): 
    //     When I type ' the 'x' gets deleted, but nothing gets inserted
    }

**Comment by gavinking** [comment]
Fixed.
