### ISSUE TITLE
can't drag/drop ceylon or java files onto a package node

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1222]
I often try to move a java or ceylon source file to a package in the ceylon explorer by dragging it to the package node. That doesn't work.

**Comment by PhiLhoSoft** [comment]
Yes, I noticed that. The worst part is that it does that even out of the Ceylon perspective, ie. when I code in Java in a non-Ceylon project.
Note that the file is still moved (in Luna), but it shows a message telling that a move participant badly behaved. In the error log, I have the following:
```
Participant 'com.redhat.ceylon.eclipse.code.refactor.MoveFileRefactoringParticipant' removed due to the following exception

java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lorg.eclipse.core.resources.IResource;
	at com.redhat.ceylon.eclipse.code.refactor.MoveFileRefactoringParticipant.initialize(MoveFileRefactoringParticipant.java:67)
	at org.eclipse.ltk.core.refactoring.participants.RefactoringParticipant.initialize(RefactoringParticipant.java:105)
[...]
```

**Comment by gavinking** [comment]
This seems to be fixed now. Closing.
