### ISSUE TITLE
Common quick-fix pattern causes errors

### ISSUE THREAD

**Issue by akberc** [ceylon/ceylon-ide-eclipse#1229]
A common refactoring usage pattern in which quick-fix results in duplicate names.  Note that the example below is simplistic. In complex cases, the duplicate leads to inheritance errors with the quick-fixed code, which can be misleading
```ceylon
interface A {
  shared formal String version;
}

String name = "n";
String version = "v";
A something = Something (name, "", "", version);
```
when quick-fixed to create a class `Something` results in:

```ceylon
class Something(String name, String string, String string1, String version)
         satisfies A {
    shared actual String version => nothing;   //     Duplicate declaration name version
}
```

**Comment by gavinking** [comment]
@akberc fixed, HTH.
