### ISSUE TITLE
Building with (pure) Eclipse fails on Java 8

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-ide-eclipse#1232]
1- For this you need to have Java 8 installed and configured as your default Java compiler/runtime (`java -version` and `javac -version` should return 1.8).

2- You will also need the `rt.jar` and `jce.jar` from a Java 7 installation.

3- Then create the file `ceylon-common/user-build.properties` with the following contents:

```
compile.java.bootclasspath=/usr/java/jdk1.7.0_71/jre/lib/rt.jar:/usr/java/jdk1.7.0_71/jre/lib/jce.jar
```

(where you will need to edit the 2 paths to point to the actual location of the 2 JARs on your system).

4- Now follow the normal build procedure of `ant clean publish ide-quick` in the `ceylon-dist` and `ceylon.formatter` projects.

5- You should do the Maven build for the Eclipse plugin and install it in Eclipse (which should also be running Java 8!) to see that everything works just fine.

The problem comes when you try to run the Eclipse plugin as an Eclipse application.

**Comment by quintesse** [comment]
PS: when done testing this and you're switching back to Java 7 don't forget to remove the `user-build.properties` file (or maybe better , just comment out the single line it contains).

**Comment by davidfestal** [comment]
I followed all these steps, and it works well. But produces no error at all !
I can run the Eclipse plugin from inside a Main Eclipse, even with Java 8, and then work correctly in the secondary Eclipse with Ceylon projects.
To summarize, I'm all in Java 8 and have no problem !
@quintesse : when you're available for this, we can take some time to check how our configurations are different.

**Comment by quintesse** [comment]
The linkn to the errors I'm getting: https://gist.github.com/quintesse/96298c1bf17ddf95afb5#file-errors1-L106

**Comment by gavinking** [comment]
What is `user-build.properties`?

**Comment by quintesse** [comment]
It's a file that you can create to override values in common-build.properties without having that file show up in your git status (it's ignored). It's just so you won't commit any personal settings you might have by accident.

**Comment by davidfestal** [comment]
@quintesse : since we have had a look into this by Skype, and it seems the IDE is out of concern (afair), can I close this issue ?

**Comment by quintesse** [comment]
Yes indeed, closing.
