### ISSUE TITLE
ModelResolutionException when a jar lib is imported + IDE and CLI do not see the same methods

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-ide-eclipse#1240]
The symptom is this error in the IDE :
```
UnitDependencyVisitor caused an exception visiting ImportMember node: com.redhat.ceylon.compiler.loader.ModelResolutionException:
JDT reference binding without a JDT IType element ! at com.redhat.ceylon.eclipse.core.model.JDTModelLoader.toType(JDTModelLoader.java:932)
```
To reproduce, start with this Ceylon code (JVM backend)
```ceylon
import org.gradle.api {
    Project
}
shared class Foo(shared Project project){
}  
```
The `Project` Java class comes from a gradle jar (the jar was imported in my Ceylon repos : it is **gradle-core-2.2.1.jar** in the Gradle distrib).So the module descriptor looks like this :
```ceylon
module com.sgalles "1.0.0" {
     shared import gradlecore "2.2.1";
} 
```
Then perform a **clean** of the project, you get the error :
```
UnitDependencyVisitor caused an exception visiting ImportMember node: com.redhat.ceylon.compiler.loader.ModelResolutionException:
JDT reference binding without a JDT IType element ! at com.redhat.ceylon.eclipse.core.model.JDTModelLoader.toType(JDTModelLoader.java:932)
```
Then, I had to force a save on the ceylon source of the class to make this error goes away.

**Comment by sgalles** [comment]
The error shows up again after a `clean` in the IDE

**Comment by gavinking** [comment]
One for you, @davidfestal.

**Comment by sgalles** [comment]
Oh : That's even more interesting :
```ceylon
import org.gradle.api {
    ...
}
shared class Foo(shared Project project){
    print(project.group);   
}  
```
**I can compile this code with the CLI, but, I can't with the IDE !**
with the ide I get : `method or attribute does not exist: 'group' in type 'Project'`
(but it exists https://gradle.org/docs/current/javadoc/org/gradle/api/Project.html)
**and the CLI sees it.**

FTR, I've tried to execute this Ceylon code compiled with the CLI in the context of Gradle and I get :
```
Caused by: com.redhat.ceylon.compiler.java.language.UnresolvedCompilationError: method or attribute does not exist: 'group' in
type 'Project'
        at com.sgalles.Foo.<init>(run.ceylon:5)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
```
So, at runtime, Ceylon does not see the `group` attribute. Like the IDE at compile time. Strange.

**Comment by sgalles** [comment]
Actually, when I clean the project now I get :
`ExpressionVisitor caused an exception visiting QualifiedMemberExpression node: com.redhat.ceylon.compiler.loader.ModelResolutionException: JDT reference binding without a JDT IType element ! at com.redhat.ceylon.eclipse.core.model.JDTModelLoader.toType(JDTModelLoader.java:932)`
Wild guess : could it be the "real" error that make the IDE *not see* the `group`attribute ?

**Comment by sgalles** [comment]
@davidfestal I've modified the title of the issue because the problem was not related to the shared vs non-shared import eventually. I've also slightly modified the description and my previous comments.

I'm still going to try to find out what's so special about this `Project` gradle Java interface that makes the IDE behave differently from the CLI.

**Comment by sgalles** [comment]
OK, so it seems that this message
```
ExpressionVisitor caused an exception visiting QualifiedMemberExpression node: com.redhat.ceylon.compiler.loader.ModelResolutionException: Failed to find declaration for org.gradle.api.Task at com.redhat.ceylon.compiler.loader.AbstractModelLoader.getNonPrimitiveType(AbstractModelLoader.java:4289)
```
Shows up when the transitive dependencies are incomplete (meaning I must add more Gradle jar).
I also got this error with the CLI.

And indeed, I was able to compile my example with the IDE eventually by adding more jars.

So, at this point the probleme seems related to missing dependencies in my project, but the error messages with `ModelResolutionException ` everywhere do not help (in the IDE or in the CLI)

**Comment by gavinking** [comment]
Yeah thats rubbish we totally need to make sure this kind of problem never blows up the compiler. It's surely a common sort of problem!

**Comment by sgalles** [comment]
@gavinking Should I open an issue for `ceylon-compiler` with a example that blows up the CLI ? Because eventually it does not seem to be an IDE issue per se.

**Comment by gavinking** [comment]
Yes please.

**Comment by sgalles** [comment]
Done
https://github.com/ceylon/ceylon-compiler/issues/2052

**Comment by gavinking** [comment]
@sgalles Thanks.

**Comment by davidfestal** [comment]
@sgalles : is there something more to do with the IDE ? it seems that in both cases of the IDE and CLI, incomplete transitive dependencies produce an error, but it's just not the same error message. The reason is : since the error occurs internally in the model loader, its message depends on the internals of each model loader.
So, @sgalles, @gavinking , should I close this issue ?

**Comment by sgalles** [comment]
@davidfestal if I get this right it seems that the problem is only https://github.com/ceylon/ceylon-compiler/issues/2052 right ? In this case I believe that you are right and this issue can be closed AFAICT.

**Comment by davidfestal** [comment]
OK
