### ISSUE TITLE
tests take too long to start

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-ide-eclipse#1241]
I have a small test model with 22 tests in (https://github.com/tombentley/jsonsl/ as it happens, but I don't think it's especially relevant) and when I run these tests in the IDE it takes about 5 or 6 seconds before the test cases even start executing. It feels like a lifetime. (The tests then take about 3s to execute which is too long, but I can live with it).

On the command line ceylon test runs the tests in about 3s. This makes me think it's not simply a matter of the metamodel initialization taking a long time. Somehow the test plugin is taking an extra 5s doing I-don't-know-what.

**Comment by gavinking** [comment]
@thradec would you take a look please?

**Comment by thradec** [comment]
I did some measurement and the good news is, that test plugin doesn't do anything extra, what could delay actual test execution. Here are some numbers ...

```
13:46:00.531         - in IDE click run tests 
13:46:00.720 (+189)  - start ceylon.modules.bootstrap.CeylonTestTool.run()                       
13:46:01.503 (+783)  - start ceylon.modules.bootstrap.CeylonRunTool.run()                
13:46:02.024 (+521)  - start com.redhat.ceylon.testjvm::Runner.run()                               
13:46:02.056 (+32)   - start ceylon.test.core::DefaultTestRunner.createExecutors()                  
13:46:03.756 (+1700) - end ceylon.test.core::DefaultTestRunner.createExecutors()                  
13:46:03.758 (+2)    - start ceylon.test.core::DefaultTestRunner.run()                              
13:46:05.158 (+1400) - end ceylon.test.core::DefaultTestRunner.run()  
```

But there is approximately 3s delay, to actual test execution begin. First half of this time is spend in tool infrastructure and the second half is spend for searching test annotations and creating execution plan.

**Comment by thradec** [comment]
I did small change, now the test view show currently running tests immediately, even if it doesn't have tests structure yet. So the UI is little more responsive, but I can't do much more from IDE side.
