### ISSUE TITLE
Breakpoint properties by right clicking on breakpoint in gutter

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-ide-eclipse#1242]
In JDT/Debug I usually get to the breakpoint properties by rightclicking on the breakpoint in the left gutter/margin and selecting **Breakpoint properties...** in the context menu. This isn't present in the Ceylon IDE.

**Comment by davidfestal** [comment]
Done with commit 6021a1c29e190a82795130cccaf540805e67b749

**Comment by tombentley** [comment]
Thanks!
