### ISSUE TITLE
rerunning old tests could be improved

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-ide-eclipse#1247]
I often want to rerun a test that's not the very last one I ran, (maybe there's two or three tests I'm running in sequence trying to understand why one fails and the other pass). 

In the JUnit plugin I can do this by clicking the down arrow next to the test history icon, clicking the test I want to re-run and clicking on the re-run test button. Three clicks.

In the Ceylon test plugin I have to click the test history button, click on the test I want to rerun, click OK and click on re-run. 4 clicks, but it feels even more clunky because I have to move the pointer to the dialog (which gnome, in its infinite wisdom, always puts in the middle of the screen and doesn't let me move; I hate gnome...).

What I think would be best would be a down arrow next to the rerun test button which showed the history of past tests, but when I click on one of those it just reruns that test immediately. That would be two clicks.

**Comment by thradec** [comment]
Done.

**Comment by quintesse** [comment]
> but when I click on one of those it just reruns that test immediately

Wait, what? *Immediately*?
But I often just go back to see the results of previous runs, to compare them to the new run, that would now not be possible anymore!
I'm not sure that auto-running is something I would want.

**Comment by thradec** [comment]
Browsing tests history is unchanged, there is only new dropdown menu next to relaunch action.

**Comment by quintesse** [comment]
ok! :)

**Comment by tombentley** [comment]
Thanks!
