### ISSUE TITLE
missing completion proposals

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-ide-eclipse#1248]
I have the following source

```ceylon
void completion() {
    Entry<String, String> e = nothing;
    if (exists n = parseInteger(e.key./*HERE*/)) {
        
    }
}
```

If I ask for completion proposals with the caret at the given point the members of `String` are not suggested, only toplevels which take a `String` argument. It works fine if the expression is part of a boolean condition, or not part of an `if` at all, so it's something to do with the `exists`.

**Comment by gavinking** [comment]
oops, silly mistake! Thanks
