### ISSUE TITLE
parameters of TreeMap.compare have null initializerParameter field when loaded from binary archive 

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1259]
Some problem in the model loader means that the field `MethodOrValue.initializerParameter` is not getting set.

@davidfestal would you take a look, please.

**Comment by davidfestal** [comment]
OK, I'll have a look

**Comment by davidfestal** [comment]
Fixed by https://github.com/ceylon/ceylon-compiler/commit/76bc84ca8a8f93ef6d69f44d41568c5614101164

**Comment by gavinking** [comment]
Excellent, thanks!
