### ISSUE TITLE
`Null at Naming.escapeClassName` for incomplete class definition

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-ide-eclipse#1264]
* Create a JVM project
* Create a module named `org.boo` (really use this name)
* Create a package named `org.boo.api` (really use this name)

In `org.boo/run.ceylon` add this code
```ceylon
import org.boo.api {
    Project
}

shared void run() {
    Project a = nothing;
}
```
 In `org.boo.api/run.ceylon` add this (erroneous) code
```ceylon
shared interface Project {     
     class 
}
```
You should get 
`compiler bug: null at com.redhat.ceylon.compiler.java.codegen.Naming.escapeClassName(Naming.java:1348)`
(if you don't get the error, try to modify and save the file  `org.boo.api/run.ceylon`

**Comment by gavinking** [comment]
I'm not sure if this bug is correctly files. @davidfestal WDYT? I'm inclined to think we should blame it on `ceylon-compiler`...

**Comment by sgalles** [comment]
@gavinking OK, no problem I'll refile the bug if necessary (FTR I can't reproduce with the CLI).
BTW, while being at it I have a variation on the same issue, and I don't know if it is really the same issue.
Replace the last step by :

In `org.boo.api/run.ceylon` add this (erroneous) code
```ceylon
shared interface Project {
    class Foo(){
         func(outer.outer);  
     } 
}
shared void func(Project p){}
```
You get something slighty more impressive
```
compiler bug: compiler bug: +  [QualifiedMemberExpression] <unknown> (5:14-5:19)
  |  +  [Identifier] (5:19-5:19)
  |  +  [InferredTypeArguments]
  |  + outer [Outer] <Project> (5:14-5:18) => Interface[Project]
  |  + . [MemberOp] (5:19-5:19)
   has a null target at unknown
```

**Comment by gavinking** [comment]
@sgalles Look, these simply aren't IDE bugs, they are problems occurring during binary generation. I'm sure you'll get them fixed much more quickly by closing this issue report and opening one against `ceylon-compiler`.

**Comment by sgalles** [comment]
OK, it's here
https://github.com/ceylon/ceylon-compiler/issues/2107
