### ISSUE TITLE
Module import quick fix imports java.auth when it should import ceylon.math

### ISSUE THREAD

**Issue by kpdonn** [ceylon/ceylon-ide-eclipse#1266]
I've just started playing around with Ceylon and I ran into a bug that I didn't see reported when I looked through the open issues. 

Basically I was trying out the answer to [this stackoverflow question.](http://stackoverflow.com/questions/28789422/why-would-you-create-an-iterable-instead-of-a-sequence-in-ceylon) But when I added the import statement there was an error because I didn't import the ceylon.math module in my module.ceylon file. When I hovered over it it offered to "quick fix" it by importing the "java.auth" module, which obviously didn't fix the error when I tried it.

I was able to reproduce this in a fresh workspace with a fresh project. My specific steps:
1. Created a new project through the "New Ceylon Project" wizard. Gave it a name and kept all defaults.
2. Created new module in the source directory using the "New Ceylon Module" wizard. Gave it a name but kept defaults.
3. Added to `import ceylon.math.float {random}` to the top of the run.ceylon file. 
4. Wrong quick fix suggestion then appeared.

When I click the quick fix it will add `import java.auth "7";` to the module.ceylon file. If I manually change it to `import ceylon.math "1.1.0";` everything works fine and the example program runs. If I remove it the same problem comes back though.

I believe I am on the latest Eclipse version and the latest Ceylon IDE plugin version. Specifically:

Eclipse Platform Version: 4.4.2.v20150204-1700
Ceylon IDE: 1.1.0.v20141013-1438-Final

Here is a screenshot of the problem with the project structure open on the left:

![screen shot 2015-02-28 at 10 55 39 pm](https://cloud.githubusercontent.com/assets/11252611/6429523/6cdca44c-bf9d-11e4-9f39-5840636e9d00.png)

**Comment by gavinking** [comment]
Moved to ceylon/ceylon-module-resolver/issues/115.

**Comment by gavinking** [comment]
This was fixed by @quintesse.
