### ISSUE TITLE
Incomplete results in OpenDeclarationDialog

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-eclipse#1269]
If you have 2 projects in the IDE, and in project A `ceylon.collection` is imported _explicitly_, and in project  B `ceylon.collection` is transitively imported in a _non-shared_ way by some explicit dependency.   
In this case, the `JDTModule` object contained in the project B is __*not available*__ and _does not contain any Package_, since in fact it is never seen (either directly or transitively) by the user code.

In the `OpenDeclarationDialog`, if this project B is considered before project A for the search, then all the declarations of module `ceylon.collection` will be skipped in the search results.

When using `Modules.getListOfModules()`, we should ensure that the `JDTModule` object is available with `isAvailable()`

**Comment by gavinking** [comment]
And?

**Comment by davidfestal** [comment]
@gavinking : And I had clicked on submit by mistake, before finishing to write the Issue description :-)
