### ISSUE TITLE
Autocompletion of nested entries does not work correctly.

### ISSUE THREAD

**Issue by tkaitchuck** [ceylon/ceylon-ide-eclipse#1279]
If I attempt to implement:

```ceylon
class MyMap satisfies Map<String->String, String> {
  ...
}
```

The IDE will auto generate the signature:
```ceylon
	shared actual Iterator<String->String->String> iterator() => nothing;
```

Which is a compile error with the message:
```
Incorrect syntax: missing > operator at ->
```
But if I create a map and pass it the generic types `<String->String, String>` it says the return type of the `iterator()` method is: 

```ceylon
 Iterator<String->String->String>
```

The correct signature would be:

```ceylon
    shared actual Iterator<<String->String>->String> iterator() => nothing;
```

This also applies to the popup dialogs that show signatures.

**Comment by gavinking** [comment]
This must actually be a bug in `ProducedTypeNamePrinter` in ceylon-spec.

**Comment by gavinking** [comment]
Fixed, thanks.
