### ISSUE TITLE
debug hover does not work when debugging a constructor

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1283]
Apparently constructors are not very well supported by the debug infrastructure.

**Comment by davidfestal** [comment]
Waiting for the fix  of issue ceylon/ceylon-compiler#2087

**Comment by gavinking** [comment]
@davidfestal Looks like @tombentley might have fixed this now?

**Comment by davidfestal** [comment]
I'm just testing it right now :-)

**Comment by tombentley** [comment]
Well it's only fixed on the `new_def_constr` branch at the moment.

**Comment by davidfestal** [comment]
So I should wait a bit I assume ?

**Comment by tombentley** [comment]
Well you can either wait till the branches are merged (I think we're in a position to do that today, aren't we @gavinking?) Or you can use the `new_def_constr` branches of ceylon-spec, ceylon-compiler, ceylon.language and ceylon-js and see whether I really did fix your issue.

**Comment by gavinking** [comment]
@tombentley I don't see why not. Though I'm not sure where @chochos is at with the JS impl.

**Comment by tombentley** [comment]
Well he's definitely started (https://github.com/ceylon/ceylon-js/issues/513) and the language module compiles so it won't inconvenience people working on the JVM compiler at all, but we should probably wait till he says he's ready.

**Comment by gavinking** [comment]
Folks I just tested the IDE with a build of @tombentley's branch, and the debug hover is still not working inside constructors.

@davidfestal I don't see any problem with the line numbers. I think this might be something else.

**Comment by davidfestal** [comment]
I'll have a look again

**Comment by davidfestal** [comment]
This is now working. Let me close it.

**Comment by gavinking** [comment]
Thanks David!
