### ISSUE TITLE
Workbench possibly not available early in plugin cycle

### ISSUE THREAD

**Issue by akberc** [ceylon/ceylon-ide-eclipse#1296]
From the bleeding edge:

Running Eclipse Mars M5 and forgot to specify `-vm` in eclipse.ini and had an EA version of Java 1.9 as the default Java on the system.

NPE at this line: https://github.com/ceylon/ceylon-ide-eclipse/blob/master/plugins/com.redhat.ceylon.eclipse.ui/src/com/redhat/ceylon/eclipse/ui/CeylonPlugin.java#L97

I have not tried to replicate with Luna but it appears that it may be too early in the plugin cycle to have access to the workbench.  However, since the purpose of this check is to hedge against JVMs below 1.7 and higher than 1.8, it perhaps does qualify as a bug if it throws an error on 1.9.

**Comment by gavinking** [comment]
Thanks, @akberc, WDYT of my fix? Does it solve the problem?

**Comment by davidfestal** [comment]
@gavinking : Shouldn't this validation code be moved into the `CeylonStartup` class, so that we are sure that the workbench object is available ?

**Comment by davidfestal** [comment]
I also moved the code in the `CeylonStartup` class, whose purpose is to run code that need access to a fully initialized workbench.
  
@akberc  : Could you confirm that we can close the issue ?

**Comment by gavinking** [comment]
Let's close it. @akberc can reopen if the problem still exists.

**Comment by akberc** [comment]
Sorry to be late, Gmail was not routing Github messages with name in them to the right folder.

OK, I recreated the environment, and yes, nice dialog this time.  Hope it does help someone!  Image:
![image](https://cloud.githubusercontent.com/assets/2241218/6993363/b6cf344a-dae9-11e4-973a-29ad50839ebb.png)

**Comment by gavinking** [comment]
@akberc thanks for confirming.
