### ISSUE TITLE
\Iunknown import when using assist: create toplevel class in new source file

### ISSUE THREAD

**Issue by DiegoCoronel** [ceylon/ceylon-ide-eclipse#1299]
Steps:

1 - Create module (for example: bug)
2 - Create module (for example: test)
3 - In file run.ceylon in module test write something like: Check check = Check();
4 - Use assist create toplevel class 'Check' in new source file
5 - In popup change the package to: bug
6 - Finish

It occurs 100% and i think its really critical because developers that like to use TDD will get this bug all time while coding.

**Comment by gavinking** [comment]
Fixed.

**Comment by DiegoCoronel** [comment]
checked, thanks.
