### ISSUE TITLE
Debug view sometimes doesn’t use Ceylon labels if “Disable Java classes calling Ceylon” option is enabled

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-ide-eclipse#1306]
If the project option “Disable Java classes calling Ceylon” option is enabled, all declarations from that project are shown in Java style (`run_.run()`) instead of Ceylon style (`tmp::run()`).

**Comment by davidfestal** [comment]
Yes, of course, the `.exploded` directory is necessary in the JavaProject classpath to be able to find the Java model element of the generated code, and, from there, map to the ceylon source model element.

In fact some times ago, we had said that we should always enable the "exploded directory". I had finally put it by default at this time.

But maybe we should now always enforce the ".exploded" directory use ?

@gavinking : wdyt ?

**Comment by gavinking** [comment]
@davidfestal I don't understand why the `.exploded` dir should be necessary for this. For archives in a module repo we don't need it, so it doesn't seem to be logically related.

**Comment by davidfestal** [comment]
@gavinking :  Archives from a module repo have the corresponding CAR archive in the project java classpath (through the Ceylon classpath containers).
On the contrary, the output CAR archives are *not* in the project classpath. it is the `.exploded` directory that is used to make the Ceylon-generated classes visible in the project Java classpath.

**Comment by davidfestal** [comment]
@gavinking : so do you agree that we *always* use the `.exploded` directory, and remove the checkbox in the Project properties ?

**Comment by davidfestal** [comment]
@gavinking : by the way, it seems we had already decided to do so in #842, but at this time I had only made it the default *option*, instead of making it the default *behavior*.

**Comment by gavinking** [comment]
Grrrr. If you *absolutely insist*. :-(

**Comment by davidfestal** [comment]
OK, I'll do it then.
