### ISSUE TITLE
error accessing top-level attributes in packages with mangled names

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-eclipse#1314]
Within the IDE, there are compile errors when attempting to access top-level attributes in a package with `long` as a component of the name, presumably due to mangling of Java reserved words. This happens if the top-level is a) imported, and b) not in the same eclipse project.

With module and package `simple.long` with the following:

```ceylon
shared class Foo() {}
shared Foo foo = Foo();
shared Foo fooLazy => Foo();
shared Foo fooFactory() => Foo();
```

The following occurs in module `simple.core`:

```ceylon
import simple.long {
    Foo,
    foo,
    fooFactory,
    fooLazy
}

shared suppressWarnings("unusedDeclaration")
void run() {
    Foo myFoo1 = Foo();         // ok
    Foo myFoo2 = fooFactory();  // ok
    Foo myFoo3 = foo;           // error
    Foo myFoo4 = fooLazy;       // error
    
    // could not determine type of function or value reference: 'foo'
    // could not determine type of function or value reference: 'fooLazy'
}
```

The errors do not occur when compiling with the CLI, or afaict when `simple.long` is part of the same compilation unit in Eclipse.

The linked tar.gz contains an eclipse project and sources. `source-deps` must be compiled outside of Eclipse per the README.

https://www.dropbox.com/s/o61z5jtqogv4yln/toplevel-bug.tar.gz?dl=0

**Comment by gavinking** [comment]
Looks like one for you, @davidfestal.
