### ISSUE TITLE
strange "incompatible types" compile error

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-eclipse#1317]
In a new (or existing) eclipse project, create a file with:

```ceylon
import ceylon.language {
    Set
}

Float|Absent slowAverage<Absent>(
        Iterable<Float, Absent> xs)
        given Absent satisfies Null {

    assert(is Float|Absent result =
            foldPairs<Float?, Integer, Float>(
        null,
        (avg, i, x) // error marker here
        //(Float? avg, i, x)
        =>  if (exists avg)
            then avg + (x - avg) / i
            else x,
        1:runtime.maxIntegerValue,
        xs));

    return result;
}

// incompatible types
//  required: ceylon.language.Float
//  found:    java.lang.Object
```

And also create a second file, which can be empty.

When re-saving the second file, the error noted above appears. The error does not occur:

* If there are no imports in the file with `slowAverage` (although the particular import doesn't seem to matter)
* Immediately after cleaning the project
* Immediately after re-saving the file with `slowAverage`
* If the line `//(Float? avg, i, x)` is used instead of the preceding line

**Comment by davidfestal** [comment]
@jvasileff : does it occur also with the CLI compiler when compiling files incrementally in the same order as in the IDE ?

**Comment by jvasileff** [comment]
I wasn't aware of incremental compilation on the CLI - is this something that has to be enabled?

I tried re-saving the second file the same way, and also explicitly listing the files to be compiled, but was not able to recreate the error.

**Comment by quintesse** [comment]
@jvasileff No, it's not something that needs to be enabled, you just explicitly specify the files you want to compile, eg:

    ceylon compile source/testmodule/myfile.ceylon

versus

    ceylon compile testmodule

**Comment by jvasileff** [comment]
Ok, thanks @quintesse. I tried various file orders and combinations, but was unable to reproduce on the CLI.

**Comment by davidfestal** [comment]
@jvasileff : thanks for your answer. I'm looking into it right now.

**Comment by FroMage** [comment]
Did you close it on purpose ?

**Comment by davidfestal** [comment]
@FroMage : yes. Indeed, the backend was incrementally compiling a file that had not been incrementally typechecked, which might lead to backend errors because, in the IDE, the front-end typechecker model is reused by the backend. So there is no real reason to think of a real backend bug.

**Comment by jvasileff** [comment]
Works great, thanks!
