### ISSUE TITLE
IDE can't find Ceylon source for type()/typeLiteral() in metamodel.ceylon

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1323]
Attempting to Open or navigate to `typeLiteral()` takes me to the Java editor for `typeLiteral_.class`.

Very strange, since it doesn't seem to happen for any other file!

@davidfestal any ideas?

**Comment by davidfestal** [comment]
@gavinking : I didn't find the Ceylon file that contains the Ceylon declaration code for this method. Are you sure it has also been defined in Ceylon with the `native` annotation ?

**Comment by davidfestal** [comment]
Ah, OK
It's because, according to the current way native Java implementations are mapped to Ceylon definitions, the Ceylon declaration file name should have the same basename as the java implementation file name (without the trailing `_` of course), like this: `typeLiteral.ceylon` and `type.ceylon`.

And currently the Ceylon declaration is in `metamodel.ceylon`.

**Comment by gavinking** [comment]
> according to the current way native Java implementations are mapped to Ceylon definitions, the Ceylon declaration file name should have the same basename as the java implementation file name (without the trailing `_` of course), like this: `typeLiteral.ceylon` and `type.ceylon`.

Well that's not actually a valid assumption...

**Comment by davidfestal** [comment]
I know, but curretly it's better than nothing, and works in most cases until we have something explicit (a `fileName` parameter in the `native` annotation for example ? )

**Comment by davidfestal** [comment]
From the beginning I thought that this solution should only be provisional, until explicit mapping rules are provided.

**Comment by gavinking** [comment]
But the name of the file is always in the `Unit`, no?

**Comment by davidfestal** [comment]
no, the `fileName` attribiute in `Unit` that comes from a binary archive, is the class name. This has been like that from the beginning of the model loader

**Comment by gavinking** [comment]
That's weird, since certainly the source file name is available from the Java class. It gets compiled in somewhere, no?

**Comment by davidfestal** [comment]
When a class file is generated from Ceylon code, the `mapping.txt` generated by the Java backend compiler inside the CAR archive META-INF directory allows retrieving the Ceylon source file that produced this class file.
*But* in this case the class file was produced by the compiler from the Java source file only : the Ceylon declaration source file is only used as a facade to have a look to sources inside the IDE, or to be able to typecheck the language module when in JavaScript only mode.

**Comment by davidfestal** [comment]
We need a way to associate  native Ceylon declaration to the name of the Java ( and/or Javascript in the future) file where the implementation if the declaration is given.

**Comment by gavinking** [comment]
Thanks David.
