### ISSUE TITLE
model for method is missing members representing parameters

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1324]
Suddenly, I can't navigate to method parameters in the doc hover. That's because the `JavaMethod` representing, e.g. a `String.join()` does not have a member for the parameter of `join()`.

**Comment by davidfestal** [comment]
This regression came with commit ceylon/ceylon-compiler@82d658c that just removed a line that had been added for ceylon/ceylon-ide-eclipse#828 (commit ceylon/ceylon-compiler@3dcc5e2).

**Comment by FroMage** [comment]
Well, then I assume one of the two fixes was invalid. I'll let you guys debate as to which one was the right one ;)

**Comment by davidfestal** [comment]
@tombentley : is it possible to revert commit ceylon/ceylon-compiler@82d658c and fix ceylon/ceylon.language#566 in another way ? In typechecked sources, parameters of methods (as well as non-shared parameters of a class) *are* members of the class or method.

**Comment by tombentley** [comment]
Probably.  Reopen and assign to me please and I'll look at it later.

**Comment by gavinking** [comment]
Working now, thanks guys.
