### ISSUE TITLE
Quickfixes for "Case types must cover all cases of the switch type or an else clause must appear"

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-ide-eclipse#1328]
I guess we need two quickfixes:

1. Add the missing `case` clauses
2. Add an `else` clause

**Comment by gavinking** [comment]
Did not mean to close.

**Comment by gavinking** [comment]
So I have done #2. 

#1 is easy to add, I think.

**Comment by gavinking** [comment]
OK now they are both there but I probably need to harden up the implementation of cases a little bit further. Anyway it works.

**Comment by tombentley** [comment]
Cool, thanks! One day I might have time to actually try it :cry:

**Comment by gavinking** [comment]
Done, closing.
