### ISSUE TITLE
Quick assist: convert positional invocation to named invocation (and vice versa)

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-ide-eclipse#1329]
Is there a reason we don't have this already?

**Comment by gavinking** [comment]
We have had it for _years_. Closing.

**Comment by tombentley** [comment]
Then how come I couldn't see it on the Ctrl+1 list?

**Comment by gavinking** [comment]
Put your caret on the paren or brace?

**Comment by tombentley** [comment]
...or anywhere in the argument list. Well that wasn't very obvious at the time.

**Comment by gavinking** [comment]
Where did you have it? On the function name?

**Comment by tombentley** [comment]
Yes

**Comment by gavinking** [comment]
Hrm. I suppose you're not the only one who will try that.
