### ISSUE TITLE
New Ceylon project should not appear uncategorized

### ISSUE THREAD

**Issue by fbricon** [ceylon/ceylon-ide-eclipse#1337]
`Ceylon Project` wizard currently appears both  as uncategorized and in the Ceylon category. 

![](http://content.screencast.com/users/fbricon/folders/Jing/media/05163ce9-6db4-4874-8dd5-6bed84d0d5a2/00000093.png)

It should only appear categorized, like other Eclipse citizens.

Using Ceylon IDE 1.1.0.v20141013-1438-Final, installed in JBDS 9.0.0.Alpha2

**Comment by fbricon** [comment]
This is caused by the use of `primaryWizard`s in https://github.com/ceylon/ceylon-ide-eclipse/blob/94ca9e5ab2b600573af01e37a2eee90658f5fb21/plugins/com.redhat.ceylon.eclipse.ui/plugin.xml#L256

From in http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fextension-points%2Forg_eclipse_ui_newWizards.html : 

    <!ELEMENT primaryWizard EMPTY>
    <!ATTLIST primaryWizard
    id IDREF #REQUIRED>
    a means of declaring that a wizard is "primary" in the UI. A primary wizard is emphasized 
    in the new wizard dialog. Please note that this element is not intended to be used by 
    plug in developers! This element exists so that product managers may emphasize a 
    set of wizards for their products.

    id - the id of a wizard that should be made primary.

**Comment by maxandersen** [comment]
Yeah, the plugin should avoid such usage. Could we gett he primaryWizard use removed ? 

(This is in context of providing Ceylon in jboss tools / developer studio)

**Comment by gavinking** [comment]
It is only in the Ceylon perspective, just like in the Java perspective, Java wizards appear uncategorized.

So I think I'm doing the right thing here.

**Comment by fbricon** [comment]
No, it's visible in all perspectives, at least in JBDS. And only Ceylon shows up that way. 

We're not talking about the `New` menu, but the `New > Project...` **wizard** ( see screenshot above)

**Comment by fbricon** [comment]
unrelated : best issue id I've ever had #1337

**Comment by gavinking** [comment]
> It is only in the Ceylon perspective

I lie. It appears in all of them, just like JDT's New Class, New Interface, and New Java Project, and new Java Project from Existing Ant Buildfile appear in every perspective.

So, OK, I agree that the documentation of the extension suggests that we shouldn't do this. But if the developers of JDT are going to pollute our perspective with their New wizards, I'm not strongly inclined to think I'm doing the wrong thing....

**Comment by gavinking** [comment]
> unrelated : best issue id I've ever had #1337

You just won, I think. :)

**Comment by maxandersen** [comment]
Please just don't do it. If everyone does it the wizards gets overcrowded.

same reason not to contribute top-level context menus and buttons to all perspectives/menus. 

It is all these small cuts that makes eclipse UI a mess. less not enforce it ;)

**Comment by fbricon** [comment]
@gavinking the Java Project wizard clearly doesn't show up at the root of tree, in the screenshot :-)

**Comment by gavinking** [comment]
@fbricon It does in my installation of Eclipse.

**Comment by fbricon** [comment]
Indeed, it shows there along with Plugin and Java Ant projects in stock Eclipse JavaEE.

I wonder why it doesn't in JBDS.

Still, we'd rather avoid having to pollute JBDS if we are to make Ceylon available from JBoss Central (see https://issues.jboss.org/browse/JBIDE-18902)

**Comment by gavinking** [comment]
My issue is that if I remove these from the `newWizards` extension point, hitting `⌘N` in the Ceylon perspective takes me to a list of Java artifacts I could create, with Ceylon stuff hidden under an unexpanded category. This makes `⌘N` almost useless in the Ceylon perspective. Now, OK, sure, I have `⌥⌘N` which will give me Ceylon-related stuff, and I have the toolbar buttons, but to be honest `⌘N` is what I usually use, and it would be a pain if the workflow to create a new Ceylon source file were: `⌘N` - <search> - <expand node> - <double click>. That's lame.

**Comment by gavinking** [comment]
@fbricon isn't there an extension that products can use to suppress an extension? Is JBDS a product? If it is, then I think it can suppress these, IIRC.

**Comment by gavinking** [comment]
There's also `⌃⌥N F`, `⌃⌥N N`, `⌃⌥N P`, and `⌃⌥N M`, but even _I_ have not taken the time to learn those ones.

**Comment by fbricon** [comment]
Dunno if there's an extension to suppress these. @dgolovin any idea?

**Comment by gavinking** [comment]
Well how does JBDS suppress the JDT New wizards?

**Comment by maxandersen** [comment]
No, we can't. and we want to also install in to plain user eclipse where products can suppress things.

Also please note that as soon as you have run one wizard in a perspective it will default to that being selected. Meaning this force "see me first"-UI trick has very little impact day-to-day. Only impact it has is that it makes the list longer and encourages bad behavior for other plugins ;)

**Comment by fbricon** [comment]
I dunno why JBDS doesn't see the Java stuff. It may be some JDT plugin that we purposefully skip when building the product, or something else. @dgolovin may know.

**Comment by maxandersen** [comment]
btw. I'll assume you have the Eclipse *Java* EPP package installed ? thus the Java features are highlighted in that.

JBDS just bundle JDT, it does not bundle the EPP package addons.

**Comment by maxandersen** [comment]
..so in short - we "suppress" it by *not* running the Java default version of eclipse ;)

**Comment by gavinking** [comment]
So if we packaged these `primaryWizard` elements in a separate `plugin.xml` file, it would solve your problem?

**Comment by gavinking** [comment]
Can't we just solve this problem at the build level? :-)

**Comment by maxandersen** [comment]
if you separate this out in a separate plugin that does not get included in the main ceylon feature then we can use that. This does really belong in a Ceylon IDE packaging feature rather in "just" the Ceylon plugin.

**Comment by luolong** [comment]
Now, it has been a while since I last delved into Eclipse apis, but isn't this configurable per perspective somewhere?

**Comment by gavinking** [comment]
Sadly it does not seem to be :-(

**Comment by luolong** [comment]
Aah, that was only for the "New" menu item in the context menu...

**Comment by gavinking** [comment]
Yep.

**Comment by maxandersen** [comment]
@luolong - it is, but not when you use the primary wizard approach overruling anything else ;)

**Comment by dgolovin** [comment]
New Java Project issue seems to be related to Eclipse SDK distribution only, I cannot replicate it for EPP downloads, I verified that on Committer and Java Packages. We don't use SDK plug-ins and that's why JBDS doesn't have problem like that.

**Comment by gavinking** [comment]
> overruling anything else ;)

Which "anything else". As far as I know there is _no other way_ to put something in a prominent location (i.e. accessible via a single-click) in the window that pops up when I type `⌘N`.

Seriously, that's a real concrete usability issue: `⌘N` is the usual shortcut people use to create a new artifact.

**Comment by gavinking** [comment]
Anyway, no-one has answered by question as to why this can't be fixed in the build. It's easy to write a build that just removes a few lines from the `plugin.xml` file, isn't it?

**Comment by dgolovin** [comment]
It cannot be fixed in devstudio build for well known reason. If update installed directly from Ceylon IDE p2 repository plugin.xml will be replaced to original one. 

Another option we used to have is osgi hooks, didn't work well due to required changes in .ini files, which is not easy to deliver through eclipse update mechanism.

Max mentioned another option about moving primaryWizard mark to separate plugin and deliver it as part of Ceylon IDE Package along with Ceylon Main feature, this is exactly what Eclipse does.

**Comment by fbricon** [comment]
+1 to move it to a sdk plugin

**Comment by maxandersen** [comment]
@gavinking we are trying to avoid having to fork and rebuild the plugins.

About putting something in a noteworthy place then that make sense if you are making Ceylon IDE that is eclipse packaged especially for ceylon - we are trying to make a package that support more than just Ceylon hence we try and avoid adding things to top level constructs like the menus, tool button bars, etc. unless that perspective is specifically relevant for that feature.

There is a reason why every plugin on this planet don't use primaryWizard. it ends up being really messy.

**Comment by gavinking** [comment]
Look, I'm happy to split this out into a separate `plugin.xml`. But I don't personally have the knowledge of OSGi nor of how our build works to know how to set all that up. So it has to be someone else who knows this stuff.

**Comment by luolong** [comment]
This has nothing to do with OSGi, and everything to do with Eclipse Platform/JDK implementation.

IMO the best course would indeed be to create another plugin+feature just for packaging up Ceylon IDE as a stand-alone eclipse based application. 

That would give us also an opening to do some more branding work -- Adding custom splash screen, modifying application  and dock icons, etc.

Ceylon specific `primaryWizard` configuration could go into that main application's `plugin.xml`.

**Comment by maxandersen** [comment]
@luolong correct.

**Comment by gavinking** [comment]
OK, fixed. I have stopped contributing stuff to other perspectives.
