### ISSUE TITLE
small bottleneck when creating a new workspace

### ISSUE THREAD

**Issue by Gurkenmaster** [ceylon/ceylon-ide-eclipse#1345]
I am a bit dissatisfied by the performance of the IDE plugin. Feature-wise it's great but it still feels a bit sluggish to me. I have tried profiling the 1.1.0 version but then started building the latest version from source because the only profiling method that actually works on plugins inside eclipse is CPU sampling which doesn't tell me at all how often a method is called and is inaccurate for smaller methods. The latest version seems to have improved the performance noticeably but there is still room for improvement.

I found one bottleneck that should be easy to fix.

Here is the culprit:
https://github.com/ceylon/ceylon-ide-eclipse/blob/master/plugins/com.redhat.ceylon.eclipse.ui/src/com/redhat/ceylon/eclipse/core/classpath/CeylonClasspathUtil.java#L326-L348

Calling the removeFile method on the ZipFile class (of the zip4j library) will create an entirely new archive and write it to disk everytime a single file is removed.

![Image](http://i.imgur.com/B171YCf.png)

**Comment by davidfestal** [comment]
@Gurkenmaster : This should be fixed.
