### ISSUE TITLE
Default source folder is called `defaultSourceFolder`

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-ide-eclipse#1348]
Creating a new project will create a folder that’s literally called `defaultSourceFolder`. That’s a bit silly, it should just be `source`.

Possibly introduced in c99726aad5a161d205d4988648041501a1f24781. That commit seems to indicate that a resource folder would similarly be called `defaultResourceFolder`, but I haven’t tested that.

**Comment by gavinking** [comment]
@lucaswerkmeister I can't reproduce this, and I don't see anything in the code that suggests to me that this could possibly occur. Unless you have hacked `Constants` in `ceylon-common`.

**Comment by lucaswerkmeister** [comment]
Couldn’t it be [these two constants](https://github.com/ceylon/ceylon-ide-eclipse/blob/master/plugins/com.redhat.ceylon.eclipse.ui/src/com/redhat/ceylon/eclipse/code/preferences/CeylonPreferenceInitializer.java#L52-L53)?

**Comment by gavinking** [comment]
@lucaswerkmeister No, they are just used as keys into the preference store.

**Comment by sgalles** [comment]
How to reproduce :
* `File > New > Ceylon project`
* type the project name
* uncheck `Use default location` and target **an empty directory that already exists**
* `Finish`

You see

![defaultsourcefolder](https://cloud.githubusercontent.com/assets/153065/8788051/135a90cc-2f38-11e5-8936-d6d1c8f36ff5.png)

**Comment by gavinking** [comment]
OK, fixed. Thanks.
