### ISSUE TITLE
Quick-fix for native import in non-native module

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-ide-eclipse#1351]
Right now this code:

```ceylon
    module foo.bar "1" {
        import java.base "7";
    }
```

will not compile unless you do either:

```ceylon
    native("java")
    module foo.bar "1" {
        import java.base "7";
    }
```

or

```ceylon
    module foo.bar "1" {
        native("java")
        import java.base "7";
    }
```

The error message itself says that you have to choose on or the other.
It would be nice to have a quick fix that gives you these options.

**Comment by quintesse** [comment]
Is this something that's not too much work @davidfestal ?

**Comment by davidfestal** [comment]
probably, but I'm not the quick-fixes expert :-)

**Comment by quintesse** [comment]
Ok hehe :)

**Comment by gavinking** [comment]
Done.

**Comment by quintesse** [comment]
Nice! thanks!
