### ISSUE TITLE
Native: SDK project shows an error in com.redhat.ceylon.testjs.HtmlReportGenerator

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-ide-eclipse#1353]
Now that I moved the `com.redhat.ceylon.testjs` module back to the normal `source` folder because with native support this should work now. And indeed the CLI compilers have no problem with this but in the IDE an error appears:

    Imported declaration not found: 'StringBuilder'	HtmlReportGenerator.ceylon	/ceylon-sdk/source/com/redhat/ceylon/testjs	line 11	Ceylon Error

**Comment by davidfestal** [comment]
I cannot reproduce this after all the recent fixes to the `native` support

**Comment by davidfestal** [comment]
@quintesse : do you confirm that we can close this ?

**Comment by quintesse** [comment]
Well it's more that Gavin removed that line because it wasn't necessary (see ceylon/ceylon-sdk@e257fe16a102dbecb026f544d437e401343ea5bc) , so I can't confirm 100%

**Comment by quintesse** [comment]
Ok, dunno what weirdness was going on before if `StringBuilder` isn't even part of `ceylon.collection`. But anyway, let's just close this then.
