### ISSUE TITLE
No overloads for native attributes

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-ide-eclipse#1363]
@gavinking said on gitter: "OK cool, I have the overloads list in the IDE for methods, but not for native attributes"

**Comment by davidfestal** [comment]
it works now. it was probably fixed as a side-effect of the last commits.
@gavinking : can you confirm it also works for you (in source project of course, not in source of binary archives).

**Comment by davidfestal** [comment]
@gavinking : any news ? Can I close the issue ?

**Comment by gavinking** [comment]
Yes, working.

**Comment by gavinking** [comment]
(Thanks.)
