### ISSUE TITLE
Update ceylon.math version in Modules Introduction

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-ide-eclipse#1372]
[`ModulesIntro.xml`](https://github.com/ceylon/ceylon-ide-eclipse/blob/master/plugins/com.redhat.ceylon.eclipse.ui/intro/ModulesIntro.xml) contains a `ceylon.math` module import; we’ll have to update its version just before the 1.2 release.

**Comment by gavinking** [comment]
Was done by @FroMage.
