### ISSUE TITLE
strange type error with type argument

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-eclipse#1373]
Two error markers appear as noted below in Eclipse projects with the JVM backend enabled:

```ceylon
T&Object bar<T>(T t) {
    if (exists t) { // Expression must be of optional type: T is not optional
        return t; // T is not assignable to T&Object
    }
    throw;
}

void foo<U>(Anything x) {
    assert (is U? x);
}
```

Note: it's the `foo` function that seems to pollute the environment.

**Comment by gavinking** [comment]
What is going on is that `Anything` has just one case type, `Object`, in the IDE with the Java compiler enabled. @davidfestal This is one for you.

**Comment by jvasileff** [comment]
FWIW, a workaround appears to be to avoid using `?` and type arguments within assert. So:

```
void foo<U>(Anything x) {
    assert (is U|Null x);
}
```

**Comment by davidfestal** [comment]
@gavinking : the root cause is here : https://github.com/ceylon/ceylon-compiler/commit/da429b2aa0c8ee0d87130b1ac395f13a9d85ff2d#commitcomment-11586723
