### ISSUE TITLE
Poor handling of non-existent annotation

### ISSUE THREAD

**Issue by tkaitchuck** [ceylon/ceylon-ide-eclipse#1376]
If one writes
shared notthere void fooBar() {
 ...
}

The error generated by the compiler is:
"Function or value does not exist: notthere"
And it provides a quickfix to add an argument named notthere who's type is a Callable. This is an insane quickfix as it does not produce code that fixes the problem.

**Comment by gavinking** [comment]
Fixed, thanks!
