### ISSUE TITLE
error annotations in outline view for String

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1380]
Navigate to the source for `String` in `ceylon.language`, and look at the outline view.

**Comment by davidfestal** [comment]
This is related to ceylon/ceylon-spec#1358. This is the error that produces the error annotation.

**Comment by davidfestal** [comment]
Fixed now with ceylon/ceylon-spec@9cf81f7fe9a3b8f5d12e413234395dd48ef536c6

**Comment by gavinking** [comment]
Awesome!
