### ISSUE TITLE
Open Declaration dialog *really* slow and seems to leak memory when developing IDE

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1382]
When I have the `ceylon-ide-eclipse` projects open, OpenDeclaration is incredibly slow and seems to run out of memory.

**Comment by davidfestal** [comment]
@gavinking : is it better with my last changes (at least regarding the slowness) ?
As for memory, I wonder if this would require being able to unload the declarations loaded by the model loader.

**Comment by gavinking** [comment]
It is definitely _better_, yes. But it's still too slow :-(

**Comment by davidfestal** [comment]
@gavinking : should be even better now that no more lazy loading happens during package scanning (due to ceylon/ceylon-model@3059ad7)

**Comment by gavinking** [comment]
_Much_ better now :-)
