### ISSUE TITLE
Remove Overrides problem marker job is can be very slow

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1385]
Apparently this code can hang for a while:

        Job job = new Job("Remove Overrides problem marker") {
            @Override
            protected IStatus run(IProgressMonitor monitor) {
                try {
                    if (project.findMarkers(CEYLON_INVALID_OVERRIDES_MARKER, false, DEPTH_INFINITE).length > 0) {
                        project.deleteMarkers(CEYLON_INVALID_OVERRIDES_MARKER, false, DEPTH_INFINITE);
                    }
                }
                catch (CoreException e) {
                    e.printStackTrace();
                }
                return Status.OK_STATUS;
            }
        };

@davidfestal this seems super-inefficient. I don't think we need a whole `DEPTH_INFINITE` search here, _let along two of them_! AFAICT the problem marker can only occur in one of two places.

Could you look at this please?

**Comment by davidfestal** [comment]
the `Overrides.xml` can be placed anywhere inside the project. And when its path has been removed fromthe config files, I don't see any other mean to remove the corresponding marker.

**Comment by davidfestal** [comment]
@gavinking : did you see my answer ?

**Comment by gavinking** [comment]
Well yeah but we can't keep track of where it is? I don't understand how it can be in any arbitrary location. Don't we have it's location in the project properties?

**Comment by davidfestal** [comment]
Its location is only specified inside the `.ceylon/config` properties file. If, for example, the `config` file is deleted by hand, or changed, then we have lost the indication of where file is.

Now what I could implement is just store some information in the project that tells you the path of the Overrides.xml file when we add an error marker on it. So we only have to read this information, and remove it as soon as we have removed the marker.

Let me try to do that..

**Comment by davidfestal** [comment]
@gavinking : it should be better like that, much faster I assume.

**Comment by gavinking** [comment]
OK, good, thanks.
