### ISSUE TITLE
Show package on top of the hover tooltip

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-eclipse#1387]
Especially when using Java interop, it can be quite difficult to select the desired class when invoking code completion. For example, I have a dozen `Tree` proposals, but in order to know which one I'm interested in, I have to use the mouse to scroll to the bottom of the documentation tooltip (for each proposal!).

If the package name (and perhaps the module?) was displayed at the top of the documentation tooltip, it would be much easier to use code completion.

**Comment by gavinking** [comment]
I have reorganized the hover a little to make the package more prominent for toplevels.
