### ISSUE TITLE
Project dependencies don't work if system repo is changed to ~/.ceylon/repo

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-eclipse#1388]
I have two projects in my workspace: **A** is `ceylon-ide-common` and **B** is `plugin-ceylon-code` (the Ceylon code for the IntelliJ plugin). A has a dependency on B. 

* If I add a class or function in B, or modify a signature, the change is not visible in A unless I recompile using the CLI.
* If in project A I ctrl-click on a declaration located in B, it navigates to the source file in `~/.ceylon/repo/xyz.src` instead of the source file in project B.

Everything goes back to normal if in the project settings I change the system repo from `${user.home}/.ceylon/repo` to an empty value.

**Comment by davidfestal** [comment]
In fact it seems that the system repo is searched before the user repos. It seems more a CMR problem. Maybe some additional configuration could help.

**Comment by davidfestal** [comment]
Well, indeed it seems we would need a way to add an extra user repo *before* the system repo, which doesn't seem to be available.

In this case, what we want is : 
- use the `com.redhat.ceylon.ide.common` classes that come *directly* from the `modules` repo  of the corresponding project.
- use the Ceylon distribution classes just compiled in the very last `ant` build (and not those embedded inside the main Eclipse instance)

We should be able to do that by setting the system repo to : `.../ceylon-dist/dist/repo`

**Comment by davidfestal** [comment]
by the way, I wonder whether we should emit a warning inside the IDE when an artifact of the module of a required project is found in another repo than the required project `modules`repo.

**Comment by quintesse** [comment]
No you do **not** want a way to put something before the system repo! That would be like saying Java "just add tit to the `-Xbootclasspath`" and everybody knows that's an extremely bad idea.

The whole problem here is that, like Java's `Xbootclasspath`, setting the system repository is a very "dangerous" operation where you need to be aware of all the possible implications. I'm very much inclined to remove the option altogether from the IDE dialog because it's just too easy to get weird problems like this.

But the reason for this problem is simply: don't set the system repository to a place where you have mixed both system modules and *copies* of the modules you are actually working on: it won't work.

**Comment by davidfestal** [comment]
Sure, @quintesse, thanks for this very clear explanation. We should have a way to check that the chosen system repo *only* contains distribution artifacts.

**Comment by davidfestal** [comment]
but it's of course not that easy

**Comment by bjansen** [comment]
Then how am I supposed to work on ceylon-ide-common, if it's also embedded in Ceylon IDE's system repo?

**Comment by davidfestal** [comment]
no, if in both the `ceylon-ide-common` and the IntelliJ Ceylon project, you set the system repo to : 
`<your git root>/ceylon-dist/osgi/embeddedRepository/repo`
everything works as you would expect.

**Comment by davidfestal** [comment]
@bjansen : In the IDE repositories dialog, it is not allowed to use relative paths for the system repository. But if you change the value in the `.project` file to set a path relative to the current project (`../ceylon-dist/osgi/embeddedRepository/repo`) it works well.
I'll make this setting change in both projects, and will fix the IDE to support it in the IDE.
And then you will find back a better environment to work easily :-)

**Comment by bjansen** [comment]
Thanks David!

**Comment by davidfestal** [comment]
I've fixed the IDE to allow the changed settings of projects `ceylon-ide-common` and `ceylon-ide-intellij`.
Let me close the issue then, since the general behavior is expected.
