### ISSUE TITLE
Open Ceylon declaration does not work if the declaration is in a required project

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-eclipse#1393]
(perhaps due to the fix in #1383 ?)

In the project "IntelliJ Plugin Ceylon Code", I can't navigate to declarations located in "ceylon-ide-common" using ctrl-click.

For exemple, in `ideaCompletionManager` I can't navigate to `IdeCompletionManager` or `FindNodeVisitor`. It works for declarations located in the same project (e.g. `functionInsertHandler`).

**Comment by davidfestal** [comment]
@bjansen : I don't understand. I can navigate to the other class. The only point is that I arrive inside the archive

**Comment by bjansen** [comment]
You can reproduce it by changing "System repository" to an empty value in the settings of "IntelliJ Plugin Ceylon Code" (I did this because of #1388)

**Comment by davidfestal** [comment]
@bjansen : even then I can navigate from `ideaCompletionManager` to the `IdeCompletionManager` suorce code in the `ceylon-ide-common` project.
Are you sure you pulled everything ?

**Comment by bjansen** [comment]
Yes, I pulled and built everything this morning, I'll try again then.

**Comment by bjansen** [comment]
Weird, now it works again, but I didn't change anything... I'll close the issue then.

**Comment by davidfestal** [comment]
Thanks
