### ISSUE TITLE
Add a refactoring to create an alias for a type name

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-eclipse#1394]
Given the following code:

```
class Foo() {
    shared void method1(Map<List<String>, Map<Object, Integer>> param) { ... }
    shared Map<List<String>, Map<Object, Integer>> method2() { ... }
}
```

It would be nice to have a refactoring that creates an alias for the selected text, then replaces every occurence of this text with the alias name:

```
class Foo() {
    shared alias MyType => Map<List<String>, Map<Object, Integer>>;

    shared void method1(MyType param) { ... }
    shared MyType method2() { ... }
}
```

**Comment by gavinking** [comment]
On it.

**Comment by gavinking** [comment]
OK, this is basically done. There's some obvious potential improvements, like supporting scopes other than "current package", but this is good enough for now.

Also it makes me feel like we really need `Inline...` to handle aliases.

But those can be separate issues.
