### ISSUE TITLE
src dir in plugin project appears empty in Ceylon Explorer

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1396]
I just have an empty `(default module)` node.

**Comment by davidfestal** [comment]
@gavinking : is the `Empty Parent Packages` filter enabled in the `Ceylon Explorer` filters ?

**Comment by gavinking** [comment]
No. Only the Empty Ceylon Parent Packages filter.

**Comment by davidfestal** [comment]
OK, my bad : the flag producing the problem is `Empty Ceylon Parent Packages`

**Comment by davidfestal** [comment]
@gavinking : is it better if you uncheck this filter ?

**Comment by davidfestal** [comment]
@gavinking : it should be good now.

**Comment by gavinking** [comment]
Yep, fixed, thanks.
