### ISSUE TITLE
"Extract value" generates incorrect code in "fat arrow" functions

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-eclipse#1404]
Given the following code:

```
[1, 2].each((el) => print(el));
```

When the cursor is on the second occurrence of `el`, "Extract value" suggests the following expressions:

```
el
print(el)
...
```

But if I choose one of these two expressions, the resulting code is incorrect:

```
value integer = el;
[1, 2].each((el) => print(integer));

value anything = print(el);
[1, 2].each((el) => anything);
```

Expected behavior:

* don't suggest these expressions, or
* create a body for this function, and put the new value inside the body

```
[1, 2].each((el) { value integer = el; return print(integer);});
				
[1, 2].each((el) { value anything = print(el); return anything; });
```

**Comment by gavinking** [comment]
Yay, finally fixed!

@bjansen + @davidfestal note that this code needs to be ported to Ceylon!
