### ISSUE TITLE
Convert single quoted strings to triple quoted ones and vice-versa

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-ide-eclipse#1405]
For example I have a string like `"((?:^|\\G|[^$])\\\\(?:\\$\\$)*)\\$&"` and I'd like to convert it to `"""((?:^|\G|[^$])\\(?:\$\$)*)\$&"""` and vice-versa without having to think about it too much and counting backslashes to make sure I haven't missed one etc.

**Comment by gavinking** [comment]
There is already a quick fix for this I believe.

**Comment by quintesse** [comment]
You're absolutely right, I had looked for it in the menus, not the quick-fix pop-up. Closing.

**Comment by quintesse** [comment]
Btw is it normal that running this quick-fix immediately saves the file? (or at least it doesn't mark the file as having changed)
