### ISSUE TITLE
JS backend doesn't ignore module imports marked `native("jvm")`

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-ide-eclipse#1410]
I have a module with a descriptor like this:

```ceylon
module foobar "1.0.0" {
    native("jvm") import java.base "7";
}
```

and when trying to run this in the IDE (fully up-to-date with everything from master) as a JavaScript application I get the following error:

```
module.js:340
          ^
Error: Cannot find module 'java/base/8/java.base-8'
```

The same code compiles and runs fine from the CLI.

**Comment by davidfestal** [comment]
@quintesse : strange, I don't succeed in reproducing it.

**Comment by quintesse** [comment]
@davidfestal Just updated the IDE and I can't reproduce it anymore. Closing.
