### ISSUE TITLE
CCE "Retrieving Fixes"

### ISSUE THREAD

**Issue by DiegoCoronel** [ceylon/ceylon-ide-eclipse#1413]
create a shortcut method with this code:

```ceylon
	shared actual Comparison compare(Jogadas other) =>
		switch (other)
		case (tesoura) 
			smaller; //Intentional, some syntar error
		case (papel) 
			equal
		case (pedra) 
			larger
```

and put mouse hover ```switch``` word..

Result:
```ceylon
An internal error occurred during: "Retrieving Fixes".
com.redhat.ceylon.compiler.typechecker.tree.CustomTree$MethodDeclaration cannot be cast to com.redhat.ceylon.compiler.typechecker.tree.Tree$SwitchStatement
```

**Comment by DiegoCoronel** [comment]
if its not clear enough tell me and i can elaborate it better, Im right now in a working meet ;)

**Comment by davidfestal** [comment]
@gavinking : it seems to me that it might be fixed by your following commit : 364a6ca
Am I right ?
@DiegoCoronel : does the problem still happen ?

**Comment by gavinking** [comment]
Yes, surely the same problem. I did not notice this issue.

**Comment by DiegoCoronel** [comment]
i tried today but with yesterday source, here a complete sample that reproduces same error:
```ceylon
abstract class Test() of foo | bar{}

object foo extends Test(){}
object bar extends Test(){}

void test(Test test) {
	Test a = 
	switch(test)
	case (foo) foo // put ',' here to force a error and mouse hover 'switch' word
	case (bar)bar;
}
```

**Comment by DiegoCoronel** [comment]
ill update everything here to todays source...

**Comment by gavinking** [comment]
Should be fixed now.
