### ISSUE TITLE
Find references does not display references in projects the current project depends on

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-eclipse#1417]
Steps to reproduce:

Create a project P1, with a module `module1`, and a file containing:

```ceylon
shared interface Foo {
    shared formal String foo;
}

void myPrint(Foo f) {
    print(f.foo);
}
```

Create a project P2, change its settings to depend on P1, create a module `module2` and a file containing:

```ceylon
import module1 {
    Foo
}

class FooImpl() satisfies Foo {
    shared actual String foo = "foo";
}
```

Right-click on `foo` (the identifier of the `actual` declaration), and call `Find > Find References`.

Expected: one reference should be found (the function `myPrint` in project P1).
Actual: no reference is found.

Works correctly if everything is in the same project.

**Comment by gavinking** [comment]
This is working perfectly fine for me now. Closing. @bjansen reopen if it occurs again.

**Comment by bjansen** [comment]
I'm still seeing the problem: I have a class in `ceylon-ide-intellij` that refines a `formal` function in `ceylon-ide-common`. If I use find references on the `actual` function, it shows 0 occurrence, but the `formal` version is used in `ceylon-ide-common`.
If I call find references on the `formal` function, it works as expected.

**Comment by bjansen** [comment]
FTR I'm searching usages of this function: https://github.com/ceylon/ceylon-ide-intellij/blob/master/plugin-ceylon-code/source/org/intellij/plugins/ceylon/ide/ceylonCode/completion/ideaCompletionManager.ceylon#L151

**Comment by gavinking** [comment]
@bjansen are they both Ceylon projects?

**Comment by gavinking** [comment]
OK, so after gitter discussion we realized the problem was the exact opposite of the original issue title. Now fixed.
