### ISSUE TITLE
Find References for Iterable.sequence() returns bogus matches in .class files

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1421]
If I run Find References on Iterable.sequence() I get:

- a bunch of bogus matches from `ceylon.language - /Users/gavin/Documents/workspace/.metadata/.plugins/com.redhat.ceylon.eclipse.ui/JavaSourceArchiveCache/Users/gavin/.ceylon/repo/ceylon.language-1.1.1.javaSources.zip`, and
- depending where I am when I run it, a bunch of additional bogus matches in `.class` files in a totally weird and broken-looking module named `ceylon.language_1.1.1` in the project `com.redhat.ceylon.eclipse.ui`.

@davidfestal these bugs could be mine, but they look suspiciously like they have to do with your modularity stuff. Would you take a look, please?

**Comment by davidfestal** [comment]
@gavinking : could you confirm this works for you ?

**Comment by gavinking** [comment]
Yes, seems to be fixed. Thanks!
