### ISSUE TITLE
Open Declaration finds stuff from ceylon.language in module ceylon.locale

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1438]
When I search for `Iterable` using Open Declaration, I get three matches instead of two.

The extra match is in the package `ceylon.language`, in the module `ceylon.locale` (!) in `~/.ceylon/repo`.

**Comment by gavinking** [comment]
This only occurs when `ceylon-ide-common` is open in my Eclipse workspace. @davidfestal any ideas?

**Comment by davidfestal** [comment]
Not really.

**Comment by gavinking** [comment]
This problem seems to have disappeared, though I was still experiencing it just a few days ago. I will close it for now, and reopen it if it reoccurs.
