### ISSUE TITLE
navigation for doc links broken in editor

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1439]
@davidfestal command-clicking on a `[[DocLink]]` in the Ceylon editor suddenly no longer works. Did you touch something?

**Comment by davidfestal** [comment]
@gavinking : no, not especially, but I'll check if this could come from null-related potential source of bugs mentioned here : https://github.com/ceylon/ceylon-ide-common/issues/9 , especially in the abstracted `nodes.ceylon` file.

**Comment by gavinking** [comment]
Fixed.
