### ISSUE TITLE
Formatting fails silently for last declaration in file

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-eclipse#1443]
With the file:

```ceylon
void formatMe1() {
print("");
}

void formatMe2() {
print("");
}

//
```
To reproduce, highlight the `formatMe2` function *including* additional trailing whitespace, and attempt to format with `command-shift-F` or similar.

Notes:

* The final `//` is simply to illustrate whitespace after the last `}` and can be removed.
* If the selection ends exactly at the last `}`, formatting works.
* If `formatMe1` is selected as well, formatting works.

attn @lucaswerkmeister

**Comment by lucaswerkmeister** [comment]
I’ll look into it tomorrow

**Comment by lucaswerkmeister** [comment]
Okay, the problem is that
```java
Nodes.findNode(pc.getRootNode(), ts);
```
returns `null`, since the selection extends past the end of the `formatMe2` node (even though it’s only whitespace).

I’ll try to fix it so it ignores any ignored tokens (ws, comments) in the selection.

**Comment by lucaswerkmeister** [comment]
Should be fixed now. In general, selections including whitespace will now be “tighter”, which is good :)
