### ISSUE TITLE
CCE `Retrieving Fixes` MethodDeclaration vs SwitchStatement

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-ide-eclipse#1449]
with this (erroneous) code, hover over `switch` with the mouse cursor
```ceylon
shared String foo(Integer bar) => switch (bar)
```
you get
`An internal error occurred during: "Retrieving Fixes". com.redhat.ceylon.compiler.typechecker.tree.CustomTree$MethodDeclaration cannot be cast to com.redhat.ceylon.compiler.typechecker.tree.Tree$SwitchStatement`

**Comment by gavinking** [comment]
@sgalles I don't get this. And I already fixed two similar bugs, so are you sure it hasn't already been fixed?

**Comment by sgalles** [comment]
@gavinking Ah, yes, maybe I recompile and I let you know.

**Comment by sgalles** [comment]
@gavinking you're right I don't reproduce this now.
