### ISSUE TITLE
NPE when renaming module

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-ide-eclipse#1452]
Check out https://github.com/ceylon/ceylon.tool.converter.java2ceylon, select its main module, then right-click on `Refactor > Rename` and change its name. You will get LOTS of NPEs in the backend when the build is done. Wait about 30 seconds, then they're gone and all is green.

**Comment by FroMage** [comment]
Haha, that's even stranger than I thought. Check out the progress window to see why the errors go away after a while. Every five seconds Eclipse wakes up to check something (not sure what). After about 30 seconds, a new build is triggered (no clue why). It fixes nothing. Then wait about 10 seconds, again another build. This time the errors in the test module are gone, but just them. Wait another 10 seconds and a last build will remove all remaining errors.

**Comment by FroMage** [comment]
Tried with the latest code and now it's even easier to reproduce. Run `Clean` on that project and you get 25 NPE errors after the build is done. Wait 5 seconds and they're gone.

**Comment by FroMage** [comment]
Here's an image to show you:
![test](https://cloud.githubusercontent.com/assets/179265/9383262/fecd07b6-4747-11e5-9797-1d57f5c867c8.gif)

**Comment by FroMage** [comment]
So, how can I debug this if you can't reproduce?

**Comment by FroMage** [comment]
I can reproduce even in Mars. 27 errors, then 25, then 0.

**Comment by davidfestal** [comment]
@FroMage : let me just finish my current task on my branch, and I'll test it then.

**Comment by davidfestal** [comment]
I don't succeed in reproducing it for the moment

**Comment by davidfestal** [comment]
even on Mars

**Comment by FroMage** [comment]
Bah, forget it, now that I have rebuilt everything, closed and reopened `ceylon.language`, I can't reproduce it either.
