### ISSUE TITLE
Pressing F5 repeatedly in the Ceylon explorer changes order of projects randomly

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-ide-eclipse#1454]
Select a single project in the Ceylon explorer and press F5 repeatedly, observe the order of projects changes.

![test](https://cloud.githubusercontent.com/assets/179265/9381732/55c70e62-473a-11e5-825e-13899c352abd.gif)

**Comment by davidfestal** [comment]
@FroMage : This should be OK now. Do you confirm that the behavior has disappeared on your side ?

**Comment by davidfestal** [comment]
@FroMage : can you confirm that I can close this one ?

**Comment by gavinking** [comment]
He can reopen it if necessary.

**Comment by FroMage** [comment]
Nope, I can still reproduce :(

**Comment by davidfestal** [comment]
@FroMage : I can reproduce the bug *only* once after the opening of a working set. Then the order is maintained when refreshing the next times. Is it the same for you ?

**Comment by davidfestal** [comment]
In fact sometimes the Sort algorithm used to sort the projects (`TimSort`) sometimes fails with a "broken contract error) . The comparator used is the `JavaElementSorter`. The "next times" are the cases when the sort succeeds and the projects are correctly sorted in the right order.
In fact I suspect the label returned for projects by the Ceylon Explorer to change when the `>` character is added at the beginning of the label. If the label changes during the sort, this might explain the failure.

**Comment by FroMage** [comment]
Well now pressing F5 seems to have no effect anymore on the whole set, but if I select at least two projects and press F5 repeatedly it will switch at some point, once per every 5-6 keystrokes.

**Comment by davidfestal** [comment]
@FroMage : Can you confirm that it's OK now ?

**Comment by FroMage** [comment]
YES :)
