### ISSUE TITLE
Extract Value broken for some expressions

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1455]
Given:

    print(loop(1)((a) => a<10k then a*10 else finished));

Select the argument of `print()` and try to Extract Value. 

@davidfestal would you take a look please?

**Comment by davidfestal** [comment]
Yes, I'll have a look asap.

**Comment by gavinking** [comment]
Thanks.

**Comment by lucaswerkmeister** [comment]
Should be fixed now.
