### ISSUE TITLE
Error mis-classified as backend error

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-ide-eclipse#1459]
https://github.com/ceylon/ceylon-compiler/issues/2292

**Comment by gavinking** [comment]
So it seems to me that `CompileErrorReporter.setupMarker()` is being called when it should not be.

**Comment by gavinking** [comment]
And that's because the `Diagnostic` we're being sent has the wrong line number.

**Comment by gavinking** [comment]
OK, it's because `AnalysisMessage.getLine()` does not call `getIdentifyingNode()`.

**Comment by gavinking** [comment]
Fixed.
