### ISSUE TITLE
Refine formal members quick assist much worse after change to FindNodeVisitor

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1466]
`FindNodeVisitor` has started returning statements that the caret is not inside of. That has broken the behavior of the refine formal members quick assist, which used to be able to add the refined members at the caret position, but can't anymore, even with the bugfix I just committed.

**Comment by lucaswerkmeister** [comment]
Can you give an example (code + caret)? The behavior should only have changed if the caret is on whitespace.

**Comment by lucaswerkmeister** [comment]
Example given on Gitter:
```ceylon
class Foo {

    void x() {}

}
```
Putting the caret on line 2 or 4 selects `x`. I agree that this is incorrect.

**Comment by luolong** [comment]
As I mentioned in the Gitter discussion, here's how I think the algorithm should be adjusted:

Basically, in case of a caret (the case where start and end positions of the selection are the same), the search for closest sibling node should be limited to the line of the caret's position.

If the selection spans two or more characters, then the search scope should be limited to the selection.

If no suitable node is found within the scope, then the outer node should be returned instead.

What do you think about that?

**Comment by luolong** [comment]
In case of the example in #issuecomment-138613687:

When caret is either on line 2 or line 4, the body of the `class Foo` should be found.

If the caret is on line 3, then it should return `x` instead.

**Comment by gavinking** [comment]
Thanks, working now.
