### ISSUE TITLE
Add imports when pasting code

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-eclipse#1472]
IIRC, until two or three months ago, imports would automatically be added as necessary when copying and pasting code from one file to another.

For example, in a project without errors, copying and pasting:

```ceylon
value l = ArrayList<String>();
```
would add
```ceylon
import ceylon.collection {
    ArrayList
}
```
if necessary.

**Comment by gavinking** [comment]
You recall correctly.

**Comment by gavinking** [comment]
Fixed, thanks!
