### ISSUE TITLE
Correctly synchronize the parse controller typechecking

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-eclipse#1478]
Now that the typechecking performed inside the `CeylonParseController` isn't synchronized anymore by the `Workspace` scheduling rule, it seems that regularly the `unit` of some AST nodes is found to be `null`, which cause NPEs at various places. 

We should find a way to avoid this without reintroducing the previous synchronization that was a cause of deadlock (#1412).

For example, see : 
- https://github.com/ceylon/ceylon-ide-eclipse/commit/5356a58d6abe8d768a5fc20bd289407ec9444303#commitcomment-13051207
- #1461

**Comment by gavinking** [comment]
@davidfestal would it be enough to just fix the npes by adding null checks? We already have them in lots of places...

**Comment by davidfestal** [comment]
why not, but the thing is that each time we get a node, we should just have waited for the current typechecking to be achieved.
The problem is that *during the typechecking*, and mainly *during the `DeclarationVisitor` process*, intermediate nodes of the AST don't have the `unit` set.

The best way would be probably to just synchronize the `CeylonParseController` typechecking and the use of the `rootNode`.

More precisely we should have a way to avoid doing something on a PhasedUnit (or Tree.CompilationUnit) that *is currently being typechecked*.

**Comment by gavinking** [comment]
Oh, sure. Yes we still do need to synchronize any typechecking that happens on the same tree.

**Comment by davidfestal** [comment]
Indeed it might be sufficient to use `CeylonParseController.getPhasedUnit().getCompilationUnit()` instead of `CeylonParseController.getRootNode()` at the various places where you want a *correctly typechecked* AST.

Because `rootNode` is set *as soon as* the parsing is finished whatever the typechecking state is of will be.

Then checking of `phasedUnit != null` should be sufficient to ensure that all the nodes have their `unit` correctly set.

**Comment by davidfestal** [comment]
closed by mistake

**Comment by davidfestal** [comment]
closing since synchronization is not necessary anymore when the *right* node is retrieved and used

**Comment by gavinking** [comment]
Cool! :-)

That's gotta be a good thing, right? More responsive, do you think?

**Comment by davidfestal** [comment]
yes, I think it's globally better, but exposed this old misuse of the original `getRootNode()` method, which was previously hidden by the unnecessary synchronization.

**Comment by davidfestal** [comment]
That's not as simple as it seems, since some context require both an AST that is : 
- up-to-date with source code (the very last parsed AST)
- fully-typechecked.

Previously we were always returning the very last AST, but sometimes it was not fully typechecked
Now we are returning the last typechecked AST, but it might be slightly inconsistent with the source.

This might have impacts on Refactorings for example.

I'm working on it, but reopen the issue until I'm sure we take in account all theses contraints

**Comment by davidfestal** [comment]
Let me summarize what we have now :

- the `CPC.getLastCompilationUnit()` (used *by default* where `getRootNode()` was used previously) returns the compilation unit of the __*last typechecked `PhasedUnit`*__, which is *not necessarily* the last parsed AST (=> possibly not consistent with the document source code).

- the `getParsedRootNode()` always returns the __*most recently parsed AST*__ (=> always consistent with the source code), that __*might have not been typechecked*__ (in case of cancellation, or of a build typechecking being run), or that might be not fully typechecked (in case the CPC typechecking is still running).

- the new `getTypecheckedRootNode()` returns the __*most recently parsed AST*__ (=> always consistent with the source code), but __*only if it has also been fully typechecked, else it returns `null`*__.

The refactorings now use the `getTypecheckedRootNode()`method, in order to be proposed only when the last CPC analysis was *complete and up-to-date with the current source code*.

I have to review some other places that use the CPC to check whether the `getLastCompilationUnit()` is the right method (`TerminateStatementAction` for example).

But, @gavinking, if you have some ideas about the places in the  code (actions, listeners, etc ...) where root node retrieved from the current editor should absolutely be : 

- consistent with the current editor source code
- fully tyechecked
- or both,

please tell me. This will help greatly.

**Comment by gavinking** [comment]
Well we have the following general areas to consider:

- navigation (from the source code, from Java code, from outlines, and from the hierarchy view)
- searching (various flavors of Find, and the Search page)
- refactorings
- quick fixes / assists
- Organize Imports
- The module properties page

I'm not sure what you would say about navigation and searching. Perhaps it's OK to return out-of-date locations? Or perhaps we could keep track of exactly which files have changed? I'm not sure. It would certainly be nice to be able to navigate or run searches while a build is happening.

Refactorings generally depend on the source being typechecked.

I believe that _most_ of the quick assists either:

- operate completely within the editor, or
- don't use typing information at all.

But I guess there are _some_ quick fixes that use typing information. Stuff like create member.

Organize Imports appears to use the editor's AST. The module properties page looks like it uses the project AST.

Does that help?

**Comment by davidfestal** [comment]
@gavinking : yes, very much. Thanks ! I'm currently having a deeper look at quickFixes.

**Comment by davidfestal** [comment]
As for navigation and searching : yes, I assume it's OK to return out-of-date locations. Indeed it's a case that doesn't happen easily : start a long build, fully change you current source file, and explicitely search something inside your current source file ...

It seems to me that for the moment we can keep it like it is, and let experience speak when we have played with it a bit more in real cases, wdyt ?

**Comment by gavinking** [comment]
I agree.

**Comment by davidfestal** [comment]
@gavinking : so now : 

- For quickFixes, we use either the editor up-to-date root node only if fully typechecked, or the root node of the central model element if it exists.

- For QuickAssists, we always use the editor up-to-date root node only if fully typechecked.

**Comment by gavinking** [comment]
> For QuickAssists, we always use the editor up-to-date root node only if fully typechecked.

WDYM? What does "full typechecked" mean in this case?

**Comment by davidfestal** [comment]
it means that the CPC typechecking has be run until its end on it. So it's fully decorated with model elements and types

**Comment by gavinking** [comment]
@davidfestal OK, but we don't need to wait for the build to finish?

**Comment by davidfestal** [comment]
no.

Simply the actions that require such a consistent rootNode (consistent with  the editor source code and decorated with a consistent typechecked model), won't be proposed if it's not available (when `getTypecheckedRootNode()` returns null.

**Comment by davidfestal** [comment]
So it's not blocking, but respecting the concurrency constraints afaik.

**Comment by davidfestal** [comment]
@gavinking : In this last commit I tried to choose the best CPC `rootNode` getter, for each remaining call to `CPC.getLastCompilationUnit()`, taking in account its specific use-cases.

The result seems quite OK for me, but of course, your remarks will help tweaking specific cases if necessary.

For the moment let me close the issue, since it's mainly done.

If you encounter anything you want to be changed in a specific case, could you open a new issue ?

**Comment by gavinking** [comment]
Cool.
