### ISSUE TITLE
How do you specify --javac=-target=8 ?

### ISSUE THREAD

**Issue by jpragey** [ceylon/ceylon-ide-eclipse#1489]
Hi,
When you call a java 8 static interface method from ceylon, you get an error:

```
call to a static interface member is not allowed unless you set the -target flag to 8: --javac=-target=8
```

It's easy to add it in shell, but how do you do it in eclipse?

**Comment by bjansen** [comment]
Since Ceylon 1.3.1, `javac` options can be configured in `.ceylon/config`, see my comment here: https://github.com/ceylon/ceylon-ide-eclipse/issues/1787#issuecomment-255384619
