### ISSUE TITLE
boxing code not being filtered in debugger

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1498]
```ceylon
shared void test() {   
    print("hello hello".firstInclusion("hell"));
}
```

Stepping into the only line of code here takes me to `ceylon.language.String.instance()`.

**Comment by davidfestal** [comment]
I don't succeed in reproducing this with the exact same code :-(

**Comment by davidfestal** [comment]
I can't step into `String.instance()` by any mean...

**Comment by davidfestal** [comment]
You might debug it by adding a breakpoint in `DebugUtils.isCeylonGeneratedMethodToSkipCompletely()`
and look at what it does here
and if it doesn't stop here, just put a breakpoint on `com.redhat.ceylon.eclipse.core.debug.model.CeylonJDIThread.newStepIntoHandler().new StepIntoHandler() {...}.locationIsFiltered(Method)`

**Comment by davidfestal** [comment]
@gavinking : may I assign it to you then ?

**Comment by gavinking** [comment]
`DebugUtils.isCeylonGeneratedMethodToSkipCompletely()` returns true.

**Comment by gavinking** [comment]
Wait. Something has changed. @davidfestal did you touch something? Suddenly I don't get any visible stack filtering at all. Before I did (i.e. I had some greyed-out stack frames).

**Comment by gavinking** [comment]
@davidfestal so it seems `locationIsFiltered()` is never called&mdash;indeed `DebugUtils.isMethodFiltered()` is never called.

**Comment by davidfestal** [comment]
@gavinking : no I didn't touch anything in this area afaik.

**Comment by davidfestal** [comment]
OK, it seems to be due to changes in the Debug API in Mars.

**Comment by davidfestal** [comment]
I seems I found the fix. However the stack frame label seems to be broken for some cases. I'll have a look at this then.

**Comment by davidfestal** [comment]
@gavinking : this should have fixed your problem. Do you confirm ?

**Comment by gavinking** [comment]
Yes, it's fixed. Thanks David!
