### ISSUE TITLE
"Shadow reference" quick fix generates wrong selection

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-eclipse#1499]
Given the following code:

```
void run() {
    variable String? abc = "a";
    
    if (exists abc) {
        
    }
}
```

If I call "Shadow reference inside control structure" on `abc`, it will assign a new value named `string`, but will select the first character only (`s`). It would be more convenient to select the whole identifier to be able to rename it quickly.

![image](https://cloud.githubusercontent.com/assets/281528/10020876/6cc4be46-6145-11e5-84b3-045bed760305.png)

**Comment by gavinking** [comment]
Fixed.
