### ISSUE TITLE
Anonymous constructor shown as 'null' in quick fix

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-eclipse#1500]
Create an anonymous constructor with a formal parameter:

```
class A {
    shared new (formal Integer offset) {    
    }
}
```

The quick fix will suggest
> Make 'offset' non-formal in 'null'

instead of 

> Make 'offset' non-formal in anonymous constructor

![image](https://cloud.githubusercontent.com/assets/281528/10020995/14496798-6146-11e5-9cd5-589d568fafac.png)

**Comment by gavinking** [comment]
Fixed.
