### ISSUE TITLE
incremental compilation Java/Ceylon undetected change

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-ide-eclipse#1504]
Start with this Ceylon code
```ceylon
class Foo(){
	shared Object bar(){
		return "foo";
	} 
}

shared void run(){
	Baz().foo(); 
}
```
and this Java code
```java
public class Baz {
	void foo(){
		Object a = new Foo().bar();
	}
}
```
execute the `run` method in Eclipse. It works.

Now change the return type of method `bar` from `Object` to `String`
like this
```ceylon
class Foo(){
	shared String bar(){
		return "foo";
	} 
}
```
then execute `run` again, you get
```
Exception in thread "main" java.lang.NoSuchMethodError: Foo.bar()Ljava/lang/Object;
	at Baz.foo(Baz.java:4)
	at run_.run(run.ceylon:8)
	at run_.main(run.ceylon)
```
now clean the project, execute `run` again, it works

**Comment by sgalles** [comment]
On second thought, isn't this issue a dup of https://github.com/ceylon/ceylon-compiler/issues/470 ?

**Comment by davidfestal** [comment]
It's related to ceylon/ceylon-compiler#470.

More precisely it seems to me it is a dupe of #1335 that is planned for 1.3 .

@sgalles : Are you OK if I close it ?

**Comment by sgalles** [comment]
yes, np @davidfestal 
I take the liberty to close it for you

**Comment by davidfestal** [comment]
Thanks !
