### ISSUE TITLE
Test comparison window uses wrong encoding

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-ide-eclipse#1507]
In the `ceylon.test` comparison window, all my `’`s (U+2019 RIGHT SINGLE QUOTATION MARK) look like this: `â` (![screenshot from 2015-09-28 19-12-05](https://cloud.githubusercontent.com/assets/2346599/10142764/d9f2915e-6614-11e5-8876-0974634d7a91.png)). This is what you get if you interpret UTF-8 ’ (e2 80 99) as ISO 8859-1 (e2 is â, 80 and 99 are unassigned). I’m not sure why the test window chose ISO 8859-1 (my platform’s default encoding should be UTF-8), but it should probably use the encoding of the project (from the Ceylon config).

**Comment by thradec** [comment]
should work now (at least for czech characters :wink:)

![image](https://cloud.githubusercontent.com/assets/1357423/10413279/7a799388-6fa3-11e5-9aa6-57ca492fbb85.png)

**Comment by lucaswerkmeister** [comment]
Great, thanks!
