### ISSUE TITLE
Code completion performance issues in ceylon-ide-intellij

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-eclipse#1508]
The first time completion is called, these two hotspots can be seen in yourkit:

* a [call to `org.eclipse.jdt.internal.core.JavaElement.exists()`](https://github.com/ceylon/ceylon-ide-eclipse/blob/master/plugins/com.redhat.ceylon.eclipse.ui/src/com/redhat/ceylon/eclipse/core/model/JDTModelLoader.java#L376) takes ~ 40% of the total time
* a [call to `org.eclipse.jdt.internal.core.ClassFile.getBinaryTypeInfo(IFile, boolean)`](https://github.com/ceylon/ceylon-ide-eclipse/blob/master/plugins/com.redhat.ceylon.eclipse.ui/src/com/redhat/ceylon/eclipse/core/model/JDTModelLoader.java#L1126) takes ~ 60% of the total time

These two methods ultimately spend most of their time opening zip files (FTR `idea.jar` is approximately 125MB).

The second time completion is called, the hotspots change:

* approx. 45% of the total time is spent in `com.redhat.ceylon.model.typechecker.model.Declaration.equals(Object)`, called by [Package.getMatchingDeclarations()](https://github.com/ceylon/ceylon-model/blob/master/src/com/redhat/ceylon/model/typechecker/model/Package.java#L233)

See [this yourkit snapshot](https://drive.google.com/file/d/0B8u_iEp6ftT7b0s0Q2xPTlJ4SDQ/view?usp=sharing) for more details of the second run.

**Comment by gavinking** [comment]
@bjansen what happens if you change lines 231 and 232 of `Package` to:

```java
      Declaration id = importable.getDeclaration().getQualifiedName();
      Declaration ed = existing.getDeclaration().getQualifiedName();
```

**Comment by gavinking** [comment]
And what happens if we change `Declaration.equals()` to reverse the order of comparisons:

```java
        Declaration dec = (Declaration) object;
        Declaration that = (Declaration) object;
        String thisName = getName();
        String thatName = that.getName();
        if (!Objects.equals(getQualifier(), that.getQualifier())) {
            return false;
        }
        if (this.getModelClass() != dec.getModelClass()) {
            return false;
        }
```

**Comment by gavinking** [comment]
> reverse the order of comparisons

@bjansen I pushed that change to `ceylon-model`. Can you try it out please?

**Comment by bjansen** [comment]
Reversing the order of comparisons seems to just move the bottleneck, because now 28% of the time is spent here:

    String thisName = getName();

**Comment by bjansen** [comment]
As for

```
Declaration id = importable.getDeclaration().getQualifiedNameString();
Declaration ed = existing.getDeclaration().getQualifiedNameString();
```

It seems that getQualifiedNameString() isn't that efficient:

![image](https://cloud.githubusercontent.com/assets/281528/10162828/555c7866-66ae-11e5-8419-059610227ae5.png)

**Comment by gavinking** [comment]
> It seems that `getQualifiedNameString()` isn't that efficient:

OK, cool, thanks, was a question I always had.

**Comment by gavinking** [comment]
@bjansen And if you try this:

            String thisName = name;
            String thatName = that.name;

avoiding the getter?

**Comment by bjansen** [comment]
Oh wait, this might explain a few things...

![image](https://cloud.githubusercontent.com/assets/281528/10162886/c921db38-66ae-11e5-848e-ed844cc204e1.png)

(actual count for a single invocation to code completion)

**Comment by gavinking** [comment]
@bjansen well the model caches the `qualifiedNameString`. That should be something that costs only the *first* time...

**Comment by gavinking** [comment]
Another question: `TreeMap` stuff is getting called *a lot*. What happens if you change to use `HashMap`s in the model?

**Comment by bjansen** [comment]
Even with cache, it's called nearly a *billion* times!

**Comment by gavinking** [comment]
Who calls it?

**Comment by bjansen** [comment]
I don't have the call stacks when I count invocations.

**Comment by gavinking** [comment]
Something that is total rubbish here is that all the `LazyXxxx` classes override `getQualifiedName()` and just call `super`. Apparently in order to add a comment. That's crazy.

**Comment by gavinking** [comment]
I understand that this is already fixed, right @bjansen?

**Comment by bjansen** [comment]
Well, I fixed one problem, but I'm sure there are others left :-) Especially the first time completion is called, the model loader can take a long time to scan huge binary archives, but I think this will be addressed when we set up Lucene.
