### ISSUE TITLE
Paste into string without imports

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-ide-eclipse#1509]
If I paste ceylon code into a `doc` string (or indeed any other string, or I suppose a comment) then I expect the editor to be clever enough to know not to add stuff to the compilation unit's `import`s.

**Comment by gavinking** [comment]
Well looking at the code it's already supposed to do this...

**Comment by gavinking** [comment]
@tombentley is this bug specific to _verbatim strings_, perhaps?

**Comment by tombentley** [comment]
Weird, I wonder why it didn't work for me then.

**Comment by tombentley** [comment]
Yes, it was a verbatim string.

**Comment by gavinking** [comment]
OK. Easy to fix then.

**Comment by gavinking** [comment]
Fixed, along with some other bugs relating to verbatim strings.

**Comment by tombentley** [comment]
Thanks
