### ISSUE TITLE
Missing key bindings for "Open Declaration"

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-eclipse#1513]
I'm often missing the option for "Open Declaration" (⌘⇧T), and have to switch my workspace to some non-Ceylon perspective and then switch it back to restore the feature.

I began noticing this immediately after I started using "Open Declaration" a month or so ago when the performance improved.

It's possible that this issue is specific to my installation since I also have the Dart plugin installed.

**Comment by jvasileff** [comment]
I just noticed conflicts with Java, which has:

* "Open Declaration..." - f3
* "Open Type..." - ⌘⇧T

**Comment by gavinking** [comment]
You just have to click inside an editor, and you will get the shortcut back. This happens in the Java perspective too, AFAIK.

There aren't any conflicts; these key bindings are scoped to the perspective.

**Comment by jvasileff** [comment]
Per gitter chat, this is an Eclipse bug. Closing.
