### ISSUE TITLE
JavaScript-only project compile error on dynamic variable or block "Type dynamic is not supported on the JVM"	

### ISSUE THREAD

**Issue by lukedegruchy** [ceylon/ceylon-ide-eclipse#1515]
1) Create a new Ceylon project
2) Project Properties > Ceylon Build > Check "Compile Project for JavaScript" and Uncheck "Compile Project for JVM"
3) Create a ceylon file with the following code:

```ceylon
shared void do() {
    dynamic whatever = "";
}
```

Compile error:  

Type dynamic is not supported on the JVM

The same project with the same file compiles with Ceylon IDE 1.1.

**Comment by quintesse** [comment]
I'm wondering if this issue and #1514 have the same common cause: perhaps the IDE isn't correctly telling the typechecker which backends it supports.

**Comment by gavinking** [comment]
Well, are you sure, @quintesse, isn't this how you set it up? I have to explicitly mark a module as `native("js")` or I won't be able to use `dynamic`. I don't really agree with that behavior, but as far as I understand it, that's what you intended...

**Comment by quintesse** [comment]
No, just look at the CLI JS compiler which has no problem compiling that code.
Besides that error only appears when the JVM backend is enabled, so the fact that you even see it is a very strong indication that the JVM backend is enabled, or at least that's what the typechecker thinks.

**Comment by quintesse** [comment]
Ok, fixed it, it was the IDE not telling the typechecker which backends were supported (it always passed "JVM").

**Comment by lukedegruchy** [comment]
Confirmed.
