### ISSUE TITLE
NPE inside the Editor when writing a setter without any name

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-eclipse#1520]
This error makes the editor really unusable

**Comment by gavinking** [comment]
@davidfestal were you expecting that commit to close this issue?

**Comment by davidfestal** [comment]
@gavinking : yes, it fixed it on the branch, and I'll cherry pick the commit to master very soon, as soon as I've pulled everything

**Comment by gavinking** [comment]
oic.
