### ISSUE TITLE
Run as Ceylon test does not work for single method

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-ide-eclipse#1524]
If I select a test method, then right click and select "run as Ceylon test" it will test the whole file, not just the method. I think this is a regression (not sure).

What do you think @thradec? Time to fix this for 1.2?

**Comment by jvasileff** [comment]
I noticed that this *does* work if the clicked on test is a method. Something like:

```ceylon
shared class MyTests() {
    shared test void test1() {}
    shared test void test2() {}
}
```

**Comment by thradec** [comment]
Done via 50bde0e (yes regression, but luckily with easy fix)

**Comment by FroMage** [comment]
Thanks :)

**Comment by FroMage** [comment]
Confirmed it works now.
