### ISSUE TITLE
Unit tests: Inconsistent results when combining native and non-native unit tests in the same file

### ISSUE THREAD

**Issue by lukedegruchy** [ceylon/ceylon-ide-eclipse#1527]
Write the following unit test in a Ceylon project that supports JVM and JS:

It may be necessary to rename the non-native unit test or move its relative position in the file to reproduce this. 

```ceylon
import ceylon.test {
    test,
    assertTrue
}

native
test
shared void crossPlatformTest();

native("jvm")
test
shared void crossPlatformTest() { assertTrue(true); }

native("js")
test
shared void crossPlatformTest() { assertTrue(false); }

test
shared void normalTest() {assertTrue(true);}
```
Sometimes both unit tests will be executed and sometimes only one will be executed.    Repeated executions with different ordering will be necessary to reproduce this because it's totally inconsistent and I can't find the determining factor.  The unit test that's left out is not consistent either.  Sometimes it's the native unit test, sometimes it's the non-native unit test.

I could not reproduce this at all from the command line (JVM or JavaScript), which is why I'm filing it under ceylon-ide-eclipse.

**Comment by lucaswerkmeister** [comment]
Does this happen on both backends?

**Comment by lukedegruchy** [comment]
I can't only speak to JVM tests.  I can't test against JS because of this:  https://github.com/ceylon/ceylon-ide-eclipse/issues/1519

**Comment by thradec** [comment]
The ordering should be always alphabetical. How do you run it (via context menu in editor/explorer/...)? Can you check the behaviour if in your run configuration is whole package or module. Thanks.

**Comment by lukedegruchy** [comment]
I'm looking in my run configuration and I'm not sure where to look.   I've tried right-clicking the package folder and right-clicking in the editor.   Because of https://github.com/ceylon/ceylon-ide-eclipse/issues/1528 I can't test anything in the IDE now.

**Comment by FroMage** [comment]
@lukedegruchy can you test again now that #1528 passes for you?

**Comment by lukedegruchy** [comment]
@FroMage As of yesterday, I no longer get interrupted exceptions with JDK tests.  I re-verified just now and I still can't reproduce the error.   I closed 1528 and I think it should stay closed.

**Comment by lukedegruchy** [comment]
I think this may be invalid.  I'm going to close this if nobody else speaks out.

I think this may be because I was right-clicking and doing Run > Ceylon Test in different parts of the editor.   Sometimes I would click on a function, sometimes I would click on the space between functions.  Based on that positioning, it would either run all tests in the file or run only that single method.  This would appear to be a recently introduced feature.  When I try this on Ceylon IDE 1.1, this will always run all unit tests in the file, never just the one that I clicked on.

**Comment by thradec** [comment]
ok, closing (but thanks for pointing this out, it needed some polishing)
