### ISSUE TITLE
All JVM tests become interrupted

### ISSUE THREAD

**Issue by lukedegruchy** [ceylon/ceylon-ide-eclipse#1528]
Write a simple Java test:

```ceylon
import ceylon.test {
    assertTrue,
    test
}

test
shared void testMe() {
    assertTrue(true);
}
```

Run As > Ceylon Test

Doesn't matter if you right-click on the package, on the ceylon file, or within the editor.

The Ceylon Test view shows 0 tests run with the following text below the icons:

Interrupted: test -> Java(7) JVM

**Comment by thradec** [comment]
Sorry, I can't reproduce (with rebuild everything from today's morning). Does somebody else observe this too?

**Comment by lukedegruchy** [comment]
I did a full clean slate build (deleted all ceylon-**** projects and re-cloned) this morning (EDST).   I can still reproduce this.  Unit tests are not working in Eclipse for me.

**Comment by jvasileff** [comment]
I've had the same for as long as I can remember.

But after a clean build just now, JS tests work for me in the IDE (except for https://gitter.im/ceylon/user?at=561a594e99bbd76f0f30c632 in some cases)

**Comment by FroMage** [comment]
Is this perhaps on windows?

**Comment by FroMage** [comment]
@thradec: a socket shutdown missing ?

**Comment by thradec** [comment]
> @thradec: a socket shutdown missing ?

I'm closing opened sockets in [tooljvm](https://github.com/ceylon/ceylon-sdk/blob/master/source/com/redhat/ceylon/testjvm/tool.ceylon#L166) and [ide](https://github.com/ceylon/ceylon-ide-eclipse/blob/master/plugins/com.redhat.ceylon.test.eclipse.plugin/src/com/redhat/ceylon/test/eclipse/plugin/model/TestEventListener.java#L167)

**Comment by sgalles** [comment]
Windows+JDK1.7+Kepler or Windows+JDK1.8+Kepler I can't reproduce this with a full clean build of master

**Comment by lukedegruchy** [comment]
OS X Mars JDK 8 for me when I reproduced it yesterday.

**Comment by lukedegruchy** [comment]
I can no longer reproduce this with the latest build.  Closing.
