### ISSUE TITLE
Debug stackframe label broken for anonymous function objects

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-eclipse#1535]
When debugging inside the anonymous function assigned to `innerF`, the stackFrame label should be changed to be ceylon-aware, but it is not. 
  
```ceylon
shared void topLevelFunction() {
    value innerF = (Integer i) {
        print("");
    };
}
```

**Comment by davidfestal** [comment]
This is due to recent scoping changes.

See this Gitter conversation : 

> the declaration of the anonymous function assigned to innerF is : `topLevelFunction.innerF.anonymous#2`
> and its scope is `topLevelFunction.innerF`
> Is it expected ?
> Shouldn't it be `topLevelFunction` directly ?
> it seems it used to be at some stage, but maybe it has changed.
>
> **FroMage 17:44**
> yes it changed recently
>
> **davidfestal 17:51**
> so what are the rules now ?
> it seems it impacts the debug support
as well as overall Ceylon 2 Java Mapping
and also possibly the AST delta builder tests
>
> **quintesse 17:52**
> It's now the same as if it were a getter
> or a normal method
> so scope-wise there's no difference anymore between : 
>    `void innerF(Integer i) { print(""); }` and `value innerF = (Integer i) { print(""); }`

**Comment by quintesse** [comment]
Well no *that* recent, I think it's been this way for a good two months now ;)
