### ISSUE TITLE
 Also use a integer to store the flags of JDT model loader mirrors ...

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-eclipse#1538]
instead of many boolean values. This should also greatly reduce memory.

**Comment by bjansen** [comment]
If my calculations are correct, with bit fields I managed to save 5 bytes per `JDTClass` and 15 bytes per `JDTMethod`. With `ceylon-ide-common`, `com.redhat.ceylon.eclipse.ui` and `com.redhat.ceylon.eclipse.ui.jdt.debug.fragment` open in Eclipse, this gives me approximately 1.1MB of saved memory, which isn't *that* much but still better than nothing. This was measured right after the projects were loaded. Of course, the improvement is also interesting in the long term, when we load more declarations (during code completion etc.),
