### ISSUE TITLE
JavaScript import errors on JVM-only module

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-eclipse#1539]
It's sometimes useful to have a JVM+JS multi-module project that contains a JVM-only module. Currently, this produces import errors unless `native("jvm")` is specified redundantly:

```ceylon
license("http://opensource.org/licenses/MIT")
by("John Vasileff")
native("jvm")
module com.vasileff.ceylon.random.java "0.0.5-SNAPSHOT" {
    shared import java.base "7";
    shared import ceylon.math "1.2.0";
    // error: Module not available for JavaScript platform: ceylon.math "1.2.0"
    shared import com.vasileff.ceylon.random.api "0.0.5-SNAPSHOT";
    import ceylon.interop.java "1.2.0";
    // error: Module not available for JavaScript platform: ceylon.interop.java "1.2.0"
}
```

The workaround is to add `native("jvm")` to the JVM-only imports.

Edit to add - to be clear, this is for projects with both "Compile project for JVM" and "Compile project to JavaScript" enabled.

**Comment by gavinking** [comment]
I think this is probably not a bug. I think this is how @quintesse intends it to behave.

**Comment by quintesse** [comment]
Nope, this is the IDE adding its own errors, I'm already looking into it

**Comment by quintesse** [comment]
This should fix it @jvasileff , unfortunately I found some other stuff that is broken :/

**Comment by jvasileff** [comment]
Works great, thanks!
