### ISSUE TITLE
quick assist and accelerator for generating equals()/hash

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1543]
In @a81b34dbcd25098dbb1ed87a958d26a3bab0edb2 I added a quick assist to make it easier to access the functionality for refining `equals()` and `hash`. The previous autocompletion-based approach is still there.

**Comment by sgalles** [comment]
BTW I noticed that the generated code ignore the nullable fields (String?, Integer? and so on) is this on purpose ?
