### ISSUE TITLE
Enabling/disabling a backend recompiles the project twice

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-ide-eclipse#1544]
The `CeylonBuilder.generateBinaries()` gets called twice when changing any of the two backend options. On a large project that's quite noticeable.

In fact, if you're just *disabling* a backend why do a rebuild at all? Just do nothing (or just clean up the relevant binaries)

**Comment by quintesse** [comment]
I made sure to see if any of the two builds was "incremental" but it doesn't seem to be that way. The arguments to the method are the same each time.

With regard to my comment about preventing a rebuild when disabling a backend: that might be impossible for now. With `native` it might be possible that disabling/enabling a backend results in errors being generated/removed. So that idea is out for now.

**Comment by gavinking** [comment]
Another annoyance is that turning logging on or off forces a complete rebuild:

**Comment by quintesse** [comment]
I guess that besides marking the property page as "dirty" each time you make a change there could be another property `shouldRebuild` so we can decide for each of our options if it affects code output or not.

**Comment by davidfestal** [comment]
Sure, it's a good idea !

**Comment by davidfestal** [comment]
I tried on a project that don't use intra-project Java 2 Ceylon dependencies (which is not officially supported), and the second build (`Rebuild project ....`) indeed is an incremental build and does nothing (unless something changed in the classpath in the meantime). I couldn't reproduce the fact that `generateBinaries()` is called twice. @quintesse  : Maybe there is a specific scenario that could help me to reproduce the problem ?

@gavinking  : As for the annoyance of triggering builds after changing some settings such as logs, could we open another issue assigned to 1.3 ?

Then if you agree I would be able to close this one (unless @quintesse provides a reproducing scenario of course).

**Comment by gavinking** [comment]
@davidfestal OK #1551.

**Comment by davidfestal** [comment]
@quintesse : Is the problem of calling `generateBinaries()` twice a problem that occurs systematically, or only on some specific projects ?
if not systematically, would you agree to postpone this to 1.3 ?

**Comment by quintesse** [comment]
@davidfestal I don't get the previous situation anymore where I said: "I made sure to see if any of the two builds was "incremental" but it doesn't seem to be that way. The arguments to the method are the same each time."

So now it's obvious that the second build is incremental, it just seems to pass all the files that have errors in them?

So, no hurry... if there's even a problem left.

**Comment by davidfestal** [comment]
OK. let me close it then ?

**Comment by gavinking** [comment]
@quintesse Please respond so that we know whether to close or slip this issue.

**Comment by quintesse** [comment]
Well @davidfestal  didn't respond to the part "So now it's obvious that the second build is incremental, it just seems to pass all the files that have errors in them?"

**Comment by davidfestal** [comment]
yes, for the moment it's right that an incremental build always includes files that have some type of errors : `duplicate declarations` and `unresolved declaration`

**Comment by davidfestal** [comment]
this is on purpose

**Comment by quintesse** [comment]
Ok, but that means you *do* compile files even when nothing has changed. Which means the module artifacts get updated which could affect projects that depend on it?

**Comment by quintesse** [comment]
Anyway, that would perhaps be a different issue, so this one can be closed for all I care.

**Comment by davidfestal** [comment]
well, not necessarily.it depends on the use-case

**Comment by davidfestal** [comment]
yes, this might be related to https://github.com/ceylon/ceylon-ide-eclipse/issues/1554

**Comment by quintesse** [comment]
Indeed, the root cause might be the same.
