### ISSUE TITLE
navigation to and hover for language module declaration in web ide project

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1547]
Open `Autocompleter.ceylon` in branch 83 or `ceylon-web-ide-backend`, and attempt to navigate to `String`. It will take you to `String.java`. Also, the documentation hover does not show the docs.

**Comment by gavinking** [comment]
This problem seems to have resolved itself :-/ Closing.

**Comment by davidfestal** [comment]
Cool !
