### ISSUE TITLE
Screwy syntax highlighting colours

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-ide-eclipse#1549]
For some reason the IDE has decided that keywords, braces and backticks should be white, the same colour as the editor background.

Obviously I can change this in **General > Appearance > Colours and Fonts** and that works, but if I open preferences a second time it has quietly reset the colours back, so something is definitely not right.

**Comment by gavinking** [comment]
Reinstall Eclipse from scratch.

**Comment by tombentley** [comment]
Oh, that's lame. There goes half an hour while I configure it into usability.
