### ISSUE TITLE
Build tries forever to compile project with errors

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-ide-eclipse#1554]
Take the SDK, introduce an error somewhere, and observe the build launch a full build every 5 seconds for no reason, even without any further file change. That has to stop ;)

**Comment by davidfestal** [comment]
@FroMage : I don't succeed in reproducing this, even when renaming `ArrayList` or `LinkedList` and introducing more than 600 errors.

Please could you tell a precise scenario to reproduce the problem ? files to modify, description of the errors introduced, ...

**Comment by FroMage** [comment]
Trying now and indeed it "only" seems to want to recompile 2 files every five seconds. But when I fucked up `LinkedList` it re-typechecked everything. Is there a good reason for this? I mean, the type has errors, why propagate to dependents before that type is fixed?

**Comment by FroMage** [comment]
Ah OK I can reproduce it: just insert a bogus import in the `ceylon.collection` module:

```ceylon
    import condetarace "3";
```

That will cause a full build every 5 seconds (well, ever 5 seconds after the minute it needs to fail the full build).

**Comment by FroMage** [comment]
And I can't even fix my module descriptor while that build is in progress :( because it won't let me edit/save it, I have to wait.

**Comment by davidfestal** [comment]
what I don't understand is : why does it even try to recompile every five seconds ? I din't have this behavior, even when introducing errors.
