### ISSUE TITLE
JavaScript Unit tests leave processes running in Eclipse

### ISSUE THREAD

**Issue by lukedegruchy** [ceylon/ceylon-ide-eclipse#1556]
Run a bunch of JavaScript unit tests in Eclipse.

Notice the red "stop" button doesn't disappear in Eclipse.
Switch to the Debug perspective.
See a bunch of processes still running in the Debug View.

**Comment by thradec** [comment]
Should by fixed via ceylon/ceylon-sdk@fb568c5

**Comment by lukedegruchy** [comment]
Confirmed
