### ISSUE TITLE
CeylonTest View doesn't expand unit test file failure tree into individual tests

### ISSUE THREAD

**Issue by lukedegruchy** [ceylon/ceylon-ide-eclipse#1558]
Write a unit test with at least one failure.   This can be reproduced with either a single failing unit test, multiple failing unit tests, or a mix of failures and successes.

With a Java JUnit test, In the JUnit view, the presence of at least one failing unit test expands the tree belonging to the unit test class.  It will not expand the view if all tests pass.

In Ceylon, near as I see, the tree never expands.   This means needed to click on the tree to expand it every single time. 

This happens in 1.1, so this is not a regression and it's probable it has always behaved this way.

I don't think this is severe enough for 1.2.

**Comment by thradec** [comment]
Done via 5ec2700

**Comment by lukedegruchy** [comment]
Confirmed.
