### ISSUE TITLE
JS Backend NPE on JVM maven imports

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-eclipse#1561]
This is Eclipse specific.

For a dual backend project with nothing but `module.ceylon`:

```ceylon
module simple "1.0.0" {
    native("jvm") import java.base "7";
    native("jvm") import "com.google.guava:guava" "18.0";
}
```

There are two error markers on the `guava` import:

```
the '' caused an exception visiting a 'ImportModule' node:
'"java.lang.NullPointerException"'
at 'com.redhat.ceylon.compiler.js.JsCompiler$1.visit(JsCompiler.java:265)'
```

The same happens for `native("jvm") import "log4j:log4j" "1.2.17";`

**Comment by gavinking** [comment]
This is actually a bug in `ceylon-js`, which is not handling the quoted import correctly.

@chochos this is urgent&mdash;do you have a chance?
