### ISSUE TITLE
create new source folder links in wizards do not update the config file!

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1567]
Wow, this is just crappy. All our wizards have links to create new source folders. But if you try to use them you get errors saying "module descriptor encountered in root source folder" because the wizards do not update the config file.

**Comment by davidfestal** [comment]
@gavinking : probably I didn't understand the problem, but when I create a project with the wizard (or change the source folder in the `Ceylon Build Paths` wizard, and add new source folder (either inside the project or with a link) it works correctly and the source directory are correctly added to the `.config` file.
What did I miss ?

**Comment by gavinking** [comment]
@davidfestal From the New Module, New Source File, or New Package wizards I mean.

**Comment by davidfestal** [comment]
Ah OK
