### ISSUE TITLE
Installation problem for 1.2.0

### ISSUE THREAD

**Issue by jeancharles-roger** [ceylon/ceylon-ide-eclipse#1568]
Trying to install the Ceylon IDE in Eclipse, I ran into the problem:
"Cannot complete the install because one or more required items could not be found. Software being installed: Ceylon IDE 1.2.0.v20151028-2224-Final (com.redhat.ceylon.eclipse.feature.feature.group 1.2.0.v20151028-2224-Final)
 Missing requirement: Ceylon IDE 1.2.0.v20151028-2224-Final (com.redhat.ceylon.eclipse.feature.feature.group 1.2.0.v20151028-2224-Final)  requires ‘org.eclipse.zest.feature.group 1.5.0' but it could not be found"

Installing Zest using the update site: http://download.eclipse.org/tools/gef/updates/releases/ fixed the problem. I used Eclipse Mars for Java Developper.

Regards

**Comment by gavinking** [comment]
@davidfestal?

**Comment by davidfestal** [comment]
I'll have a look tonight. I also thought I had fixed this. Strange.

**Comment by davidfestal** [comment]
in fact I had added the feature requirement. This was the fix at this time, for a different problem. But here it seems that for Mars Gef / Zest is not available in the main Mars update site. I'll have to have a look. and if necessary add this generic update site in the composite update-site XML files available on the ceylon-lang.org web site. That might be sufficient.

**Comment by davidfestal** [comment]
Fixed by https://github.com/ceylon/ceylon-lang.org/commit/da3e496951abb7efb39c24355934b60071c70f68

This will work automatically now only when using the update site URLs given on the Ceylon web site? 

@jeancharles-roger : do you confirm this is OK now ?

**Comment by jeancharles-roger** [comment]
I've removed Ceylon IDE and Zest and install Ceylon IDE by it self and worked like a charm.
I saw a GEF folder appear in the Ceylon update site.

Thank you.
