### ISSUE TITLE
Declarations are not found after upgrade to 1.2.0

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-eclipse#1569]
I recently cleaned my local repo because I had dev modules tagged 1.2.0 and wanted to download the final builds from Herd. I deleted every folder named `1.2.0` in `~/.ceylon/repo`.

Then I went back to eclipse, and ceylon-ide-common wouldn't build anymore: some dependencies were not found in the local repo, for example `ceylon.interop.java 1.2.0`. The CLI could compile the project, because it downloaded dependencies in `~/.ceylon/cache`, but it looks like Eclipse only looks for dependencies in `repo`, not `cache`. 

What's strange is that I can ctrl-click on the package `ceylon.interop.java` and it will bring me to the correct `module.ceylon` in `~/.ceylon/cache/.../ceylon.interop.java-1.2.src!/...`, but somehow declarations in that package can't be found.

I built the dist and the SDK, which put all the necessary dependencies in `~/.ceylon/repo` and everything went back to normal.

Note: the checkbox "work offline" is not enabled in ceylon-ide-common.

**Comment by davidfestal** [comment]
@bjansen : I removed `ceylon.interop.java` from `~/.ceylon/repo`, and it automaticallyretrived the right one from Herd, and no error. Even the first time. So we might close it probably.

**Comment by bjansen** [comment]
Huh, I tested that again and now it works, even though I don't see any folder named `ceylon/interop/java` in `~/.ceylon/repo`. I'll close the issue then.
