### ISSUE TITLE
Ceylon IDE 1.2.0 builds continously

### ISSUE THREAD

**Issue by ncorai** [ceylon/ceylon-ide-eclipse#1570]
In Eclipse Mars 2.4.1 and Ceylon 1.2.0.v20151028-2219, my Ceylon project rebuilds continuously when `General->Workspace->Refresh using native hooks or polling` is checked (Windows 8.1, JRE 1.8.0_65). I have no errors or warnings, project is jvm only.

**Comment by gavinking** [comment]
Sounds like it could be related to #1554.

**Comment by davidfestal** [comment]
@ncorai : I'm not able to reproduce this. Could you share a project on which the bug happens systematically?

**Comment by davidfestal** [comment]
@ncorai : any news ?

**Comment by ncorai** [comment]
The projects that were doing this had been created under previous versions of the Ceylon IDE. Compared to a brand new project in which I would copy the same code, a legacy project that kept rebuilding was missing a `.settings` folder with a `org.eclipse.jdt.core.prefs` file in it containing the following properties:
```
eclipse.preferences.version=1
org.eclipse.jdt.core.compiler.codegen.inlineJsrBytecode=enabled
org.eclipse.jdt.core.compiler.codegen.targetPlatform=1.8
org.eclipse.jdt.core.compiler.codegen.unusedLocal=preserve
org.eclipse.jdt.core.compiler.compliance=1.8
org.eclipse.jdt.core.compiler.debug.lineNumber=generate
org.eclipse.jdt.core.compiler.debug.localVariable=generate
org.eclipse.jdt.core.compiler.debug.sourceFile=generate
org.eclipse.jdt.core.compiler.problem.assertIdentifier=error
org.eclipse.jdt.core.compiler.problem.enumIdentifier=error
org.eclipse.jdt.core.compiler.source=1.8
```
Copying the file over to my legacy project seems to have stopped the endless rebuilding cycle, so you can close the issue.

**Comment by gavinking** [comment]
Thanks!
