### ISSUE TITLE
migrate back the ExtractXXX refactorings to the `ceylon-ide-common` version.

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-eclipse#1573]
since @gavinking had rollbacked this some weeks ago : https://github.com/ceylon/ceylon-ide-eclipse/commit/11730c2b665d1c6a8264734ddeea8ea601d094c8

And then @bjansen merge some branch changes on it : https://github.com/ceylon/ceylon-ide-eclipse/commit/356742c0d106da8441cc7cc0876c71c0043ac6c7

So a review is necessary about the current state of this.

**Comment by davidfestal** [comment]
@gavinking : I made many tests with linked mode, preview, dialog, etc ... and it seems to work correctly.
However if you succeed in reproducing the CCEs that made you rollback these changes before 1.2.0, please open an issue and assign me.

**Comment by gavinking** [comment]
@davidfestal when I extract the anon function:

    "".split((Character ch) => nothing, false, true);

it doesn't allow me to rename the function in linked mode.

**Comment by davidfestal** [comment]
let me test is right now.

**Comment by davidfestal** [comment]
This works for me here.
