### ISSUE TITLE
debugger currently unusable

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1576]
The debugger is currently unusable, I'm getting CCEs attempting to add breakpoints, and rendering labels of the stack viewer.

**Comment by davidfestal** [comment]
@gavinking : could you add the stacktrace ?

**Comment by gavinking** [comment]
Dude, this is *incredibly* easy to reproduce: just try debugging something, anything.

**Comment by davidfestal** [comment]
@gavinking: is it still happening with the last master ? I don't have that, and I can set breakpoints and debug on stop on them correctly.

**Comment by gavinking** [comment]
Let me check. But I think you might be right; I think it might have fixed itself already.

**Comment by gavinking** [comment]
Seems fixed.
