### ISSUE TITLE
broken refinement completion

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1579]
Given:

```ceylon
class X() satisfies Set<Character> {
    
}
```

Attempt to refine `contains()`, `union()`, or `intersection()`.

**Comment by gavinking** [comment]
Not sure if this is a bug in 1.2.0, but probably not. It _probably_ happened after the merge of @bjansen's work on completions, but I need to make sure.

**Comment by gavinking** [comment]
Thanks to @ASzc for confirming that this is a problem specific to 1.2.

**Comment by bjansen** [comment]
Fixed by https://github.com/ceylon/ceylon-ide-common/commit/ccf316dc4090f88720f2bcae03c3ee33bb92e519

**Comment by gavinking** [comment]
Thanks!
