### ISSUE TITLE
extra quick fix to change void to return type

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1582]
Given:

```
void add(Float x, Float y) => x + y;
```

I should be able to quick fix my way out of that.

**Comment by gavinking** [comment]
Note: this is super-easy to implement but requires a tiny change (error code) to the typechecker, so not for 1.2.1.

**Comment by bjansen** [comment]
Please implement this in ceylon-ide-common so that I can easily add the same quick fix to IntelliJ.

**Comment by bjansen** [comment]
There's already a quick fix for that, closing.

<img width="668" alt="capture d ecran 2016-12-22 a 18 06 29" src="https://cloud.githubusercontent.com/assets/281528/21433769/70e6e7bc-c871-11e6-956b-c10424dd1e0e.png">
