### ISSUE TITLE
linked mode argument proposals broken for String.split()

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1583]
Completing `String.split()` results in something screwy with the linked mode. I'm not sure is this is a bug in 1.2.0, or only appeared after the merge of @bjansen's completions work, but need to investigate.

**Comment by gavinking** [comment]
Thanks to @ASzc for confirming that this is a problem specific to 1.3.

**Comment by bjansen** [comment]
I was able to track to problem down to `ParameterContextValidator.findCharCount()` that was badly converted to Ceylon: it uses a lot of fall-through and breaks, which don't work in Ceylon switches. 

I pushed a fix that works (https://github.com/ceylon/ceylon-ide-common/commit/364a5123ba615177c4dee90a675605d6fcfa39ff), but I'm not satisfied with the general algorithm that now uses boolean flags and lots of `if`.

@gavinking could you take a look at `findCharCount()` in `completionUtils.ceylon` and see if you can find a better approach?

**Comment by gavinking** [comment]
@bjansen is that better, do you think?

**Comment by bjansen** [comment]
Yes it's better, I can close the issue now. Thanks!
