### ISSUE TITLE
completing member named "interface" does not escape with \i

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1585]
In the 1.2.0 release, autocompletion produces, `X().\iinterface`, but in current master, it produces `X().interface`.

@bjansen would you take a look, please?

**Comment by bjansen** [comment]
Fixed in https://github.com/ceylon/ceylon-ide-common/commit/edb3be2ca45817ae19503ff692a613c82ec897f3.

Perhaps we should open those kind of issues in ceylon-ide-common instead, since they will likely affect other IDEs as well?
