### ISSUE TITLE
Run the "Preparing completions" task in a background thread.

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-eclipse#1589]
Currently, when you invoke code completion in a project that has huge dependencies, it can take a while before the popup appears. The IDE is completely frozen while it is preparing completions. It would be nice if we could continue typing while stuff is being computed in the background.

Also, it is currently not possible to stop this preparation, the red square is useless because it keeps computing things after you click it.

**Comment by davidfestal** [comment]
related to #1815 and #1814

**Comment by davidfestal** [comment]
Finally fixed for release 1.3.0 !
