### ISSUE TITLE
Clicking on failed test should jump to failed assertion, not test method decl

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-ide-eclipse#1593]
When I double click on a failed test in the test plugin the editor changes to highlight the `test`-annotated declaration which failed. What I really want is for it to highlight the failed `assert`, `assertEquals` or whatever within that test, because my `test` methods frequently have several assertions in them and picking through the failure stacktrace to find the one which failed is not much fun.

Now obviously sometimes my assertions are directly in the `test`-annotated method and sometimes they're encapsulated in a helper method which the `test`-annotated method calls. So there's no right answer about whether to jump to the line in the `test`-annotated method which the `Assertion*Error` propgates from, or whether to jump to the line of the helper method. But either would be more helpful than the current behaviour for forces me to poke around in stacktraces for *every* failure.

**Comment by thradec** [comment]
Done, via 15cfdaf.
