### ISSUE TITLE
hover over value or function should offer "specify explicit type"

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1596]
In the released IDE, when you hover over `value` or `function`, it offers you the ability to "Specify explicit type". That is gone on master.

@bjansen @davidfestal I assume this is a side-effect of the abstraction work.

**Comment by bjansen** [comment]
Yeah sorry that's a thing I didn't have time to abstract yet, and I wasn't sure I was gonna implement it in IntelliJ, because such features don't exist in the java IDE. But then again, we are trying to build the best IDE ever, so I think I'll give it a try tomorrow.
