### ISSUE TITLE
spurious error in Integer.ceylon

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1611]
Opening `Integer.ceylon` from its source archive gives me this spurious error:

    Illlegal reference to native declaration runtime: native declaration Integer has a different backend

Likely a side-effect of https://github.com/ceylon/ceylon-spec/issues/1468.

**Comment by quintesse** [comment]
Actually probably not related, the error messages are not the same and only deal with `module` and `import`. Personally I think this was there before but just nobody noticed. Anyway, I'll take a look.

**Comment by davidfestal** [comment]
Fixed now on `master` and `1.2.1-preparation` branches.
