### ISSUE TITLE
type argument substitution in doc hover is broken

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1619]
When hovering over `map` in the following statement:

    "asdfas".map((ch) => ch.uppercased);

I am supposed to see the signature of `map()` with type arguments substituted. This is currently completely broken.

@bjansen would you take a look at this please?

**Comment by bjansen** [comment]
Fixed.

**Comment by gavinking** [comment]
Thanks Bastien.
