### ISSUE TITLE
broken quick fix

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1623]
Given this code:

```ceylon
class PersistentSet() satisfies MutableSet<Element> {}
```

There is supposed to be a quickfix `Add type parameter 'Element' to 'PersistentSet'`. It has disappeared in recent builds.

**Comment by bjansen** [comment]
If the bug is on master, shouldn't the milestone be 1.3 instead of 1.2.1?

**Comment by bjansen** [comment]
```
//TODO addCreateTypeParameterProposal(data, bt, brokenName);
```
Well, time to do it then :smile:

**Comment by gavinking** [comment]
I guess so:

**Comment by gavinking** [comment]
Thanks mate!
