### ISSUE TITLE
support overrides.xml per module

### ISSUE THREAD

**Issue by DiegoCoronel** [ceylon/ceylon-ide-eclipse#1624]
Currently its not possible to have a project with modules and each one with its own overrides.xml. Im trying for example to have one project with modules for: SpringBoot and Arquillian...

**Comment by gavinking** [comment]
The lack of assemblies is beginning to bite us...

**Comment by DiegoCoronel** [comment]
I see it with good eyes, we are getting further and further away and with it we are finding some needs , definitely we can already integrate with various frameworks used by the market , there are only some polishing so that everything is smooth in the development

**Comment by gavinking** [comment]
Closing this one in light of https://github.com/ceylon/ceylon/issues/5955.
