### ISSUE TITLE
font size for file name in doc hover

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1637]
The source file name is too big in the doc hover. This doesn't seem to affect the 1.2.0 release.

**Comment by bjansen** [comment]
On my machine, they have the same size as before:

<img width="250" alt="capture d ecran 2015-12-03 a 16 15 58" src="https://cloud.githubusercontent.com/assets/281528/11564429/7835d126-99d9-11e5-99d7-eb535fe48822.png">
<img width="257" alt="capture d ecran 2015-12-03 a 16 17 11" src="https://cloud.githubusercontent.com/assets/281528/11564428/78341584-99d9-11e5-9e5a-36a163c5e59f.png">

**Comment by bjansen** [comment]
Links are a bit bigger than regular text, but I think this is due to the monospace font which is a bit larger.

**Comment by gavinking** [comment]
You are using Monaco, right? Try switching to Inconsolata 13

**Comment by bjansen** [comment]
OK I can see it now.

**Comment by gavinking** [comment]
Thanks.
