### ISSUE TITLE
type hover should show TC type as well as written type

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-ide-eclipse#1640]
The typechecker can simplify `Usable&<Resource|Null>` to `Usable&Resource`, but when I hover over that type in the IDE it shows me the unsimplified type.

It might be nice if, as well as the "Abbreviation of: ", it also showed "Simplifies to: " in those cases where the type the user wrote is can be simplified.

**Comment by gavinking** [comment]
I have implemented this. But I was surprised, @bjansen, to find that this little bit of functionality hasn't been abstracted yet. There's no selected type hover in IntelliJ?

**Comment by bjansen** [comment]
By default the popup is shown using a keyboard shortcut, not on hover. I think it would be possible to add the same feature when text is selected. 

I'll dot it in https://github.com/ceylon/ceylon-ide-common/issues/19
