### ISSUE TITLE
In Compare results dialog actual/expected values are swapped

### ISSUE THREAD

**Issue by thradec** [ceylon/ceylon-ide-eclipse#1641]

**Comment by lucaswerkmeister** [comment]
I disagree. Expected – Actual makes much more sense to me.

**Comment by thradec** [comment]
well there is no right order, and this fix at least the difference with `assertEquals` (spotted by @tombentley today)

**Comment by lucaswerkmeister** [comment]
well to me there is, otherwise I wouldn’t have commented :)

**Comment by thradec** [comment]
FTR In first implementation of assertEquals it was reversed, but then somebody complained. Personally, I don't care, if you find enough voices, we can switch it every year ;-)

**Comment by tombentley** [comment]
Thanks @thradec!
