### ISSUE TITLE
unable to build sdk with latest Eclipse plugin

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-eclipse#1644]
With a clean build of the latest Eclipse plugin (eod December 4th), I can't build the `ceylon.transaction` and `ceylon.test` modules in Eclipse. There seems to be a problem with transitive dependencies declared in `module.properties` files.

I *was* able to get `ceylon.transaction` to compile by adding to `module.ceylon`:

```ceylon
    shared import javax.transaction.api "1.2";
    shared import "org.jboss.jboss-transaction-spi" "7.3.1.Final";
    shared import "org.jboss.jnpserver" "5.0.3.GA";
```

but this should not be necessary as these are listed in `org/jboss/narayana/jta/5.2.7.Final/module.properties`, and `narayana` is imported in `module.ceylon`.

**Comment by davidfestal** [comment]
@jvasileff : with the changes I just pushed to several GitHub repos, I was able to build the SDK again.
Can you confirm and close the issue ?

**Comment by jvasileff** [comment]
@davidfestal everything compiles and looks good. Thanks!
