### ISSUE TITLE
outline view empty for source file in ceylon.language project

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1654]
I can't seem to open the outline view for a source file with no Ceylon builder enabled.

**Comment by gavinking** [comment]
Note, this does not seem to affect the 1.2.0-fixes branch.

**Comment by davidfestal** [comment]
@gavinking : With the last master, I get the outline view  for language module source files. Tested on:
 - `Array.ceylon`,
- `Measure.ceylon`, 
- etc...
