### ISSUE TITLE
walk-through master fails

### ISSUE THREAD

**Issue by qsys** [ceylon/ceylon-ide-eclipse#1656]
In an attempt to start learning ceylon, I just followed (Eclipse Mars):
http://ceylon-lang.org/documentation/1.2/walkthrough/
The first issue had to do with a compiler version 7 not compatible with version 8. So I changed the 'module.ceylon'-files and imported ceylon.collection from 1.1.0 to 1.2.0
However, I still have issues in the file 06interfaces_operators. Here are the markers/problems:

    Description	Resource	Path	Location	Type
    cannot find symbol
      symbol:   class Writer
      location: package de	06schnittstellen_operatoren.ceylon	/ceylon-walkthrough/source/de	line 25	Ceylon Backend Error
    cannot find symbol
      symbol:   class Writer
      location: package en	06interfaces_operators.ceylon	/ceylon-walkthrough/source/en	line 23	Ceylon Backend Error
    cannot find symbol
      symbol:   class Writer
      location: package es	06interfaces_operadores.ceylon	/ceylon-walkthrough/source/es	line 24	Ceylon Backend Error
    cannot find symbol
      symbol:   class Writer
      location: package fr	06interfaces_operateurs.ceylon	/ceylon-walkthrough/source/fr	line 24	Ceylon Backend Error
    compiler bug: class file for java.lang.Deprecated not found at unknown	06interfaces_operateurs.ceylon	/ceylon-walkthrough/source/fr	line 238	Ceylon Backend Error
    compiler bug: class file for java.lang.Object not found at unknown	06interfaces_operateurs.ceylon	/ceylon-walkthrough/source/fr	line 11	Ceylon Backend Error
    compiler bug: class file for java.lang.String not found at unknown	06interfaces_operateurs.ceylon	/ceylon-walkthrough/source/fr	line 9	Ceylon Backend Error
    compiler bug: visitor didn't yield any result at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.transformExpression(ExpressionTransformer.java:340)	06interfaces_operateurs.ceylon	/ceylon-walkthrough/source/fr	line 11	Ceylon Backend Error
    compiler bug: visitor didn't yield any result at unknown	06interfaces_operateurs.ceylon	/ceylon-walkthrough/source/fr	line 11	Ceylon Backend Error
    package java.lang does not exist	07arguments_nommes.ceylon	/ceylon-walkthrough/source/fr	line 186	Ceylon Backend Error
    Some classes are missing from the generated module archives, probably because of an error in the Java backend compilation. The detail of missing classes is given in the Information markers.	ceylon-walkthrough		Unknown	Ceylon Backend Error

I tried with JRE7 and JRE8.

**Comment by gavinking** [comment]
Hi, @qsys, it's working for me on both the 1.2.0 MR1 release of Ceylon IDE, and against current master.

You were using the repository https://github.com/ceylon/ceylon-walkthrough.git, right?

**Comment by qsys** [comment]
yes, tried both master and 1.2...
Eclipse Mars 4.5.0, Windows 7 Enterprise

**Comment by qsys** [comment]
solved: did work in Eclipse Mars.1, didn't work in Eclipse Mars 4.5.0

**Comment by qsys** [comment]
solved: did work in Eclipse Mars.1, didn't work in Eclipse Mars 4.5.0

**Comment by gavinking** [comment]
@davidfestal I would love to know why the walkthrough didn't build in the IDE running on Mars 4.5....
