### ISSUE TITLE
"Not definitely specified" error on imported symbol

### ISSUE THREAD

**Issue by lukehutch** [ceylon/ceylon-ide-eclipse#1657]
I'm trying to follow the Vert.x 3.2.0 docs for Ceylon here: http://vertx.io/docs/vertx-core/ceylon/ -- however, the examples don't seem to work in Eclipse at least. I have in `module.ceylon`:
```
native ("jvm") module webtest "1.0.0" {
	shared import io.vertx.ceylon.core "3.2.0";
	shared import io.vertx.ceylon.web "3.2.0";
}
```
And in `webtest.ceylon`:
```
import io.vertx.ceylon.core {
	vertx
}

shared void run() {
	value vertx = vertx.vertx();
}
```
However, I get the error `Not definitely specified: vertx`. I have to change this to the following to run. Is this expected, i.e. are the Vert.x docs wrong?:
```
import io.vertx.ceylon.core {
	vertx_=vertx
}

shared void run() {
	value vertx = vertx_.vertx();
}
```
@sadmac7000 on Gitter said that he thinks it should work without the underscore, but "definitely file that as a bug if you can get a small reproducer, because at minimum the error message is wrong."

**Comment by gavinking** [comment]
This isn't a bug in Ceylon. The `vertx` that is in scope in `run()` is the local `value`, not the imported thing.  And that is indeed not definitely specified at the point where you evaluate it.

It is a bug in the vert.x docs.
