### ISSUE TITLE
"compiler bug: empty iterable literal with sequenced arguments"

### ISSUE THREAD

**Issue by lukehutch** [ceylon/ceylon-ide-eclipse#1658]
I'm trying to follow the Vert.x 3.2.0 docs for Ceylon here: http://vertx.io/docs/vertx-core/ceylon/ -- however, the examples don't seem to work. I have the following code:
```
import io.vertx.ceylon.core {
	vertx_=vertx
}
import io.vertx.ceylon.core.http {
	HttpServerRequest
}
shared void run() {
	value vertx = vertx_.vertx();
	value server = vertx.createHttpServer();
	server.requestHandler((HttpServerRequest request) => {
		//...
	});
	server.listen(8080);
}
```
I get an error on the lambda expression, `Expression cannot be assigned`. I have no idea what this error message is, or why it is shown (suggestion: please report a more useful error message here!)

I tried extracting the expression, in case it gave me a more useful error message:

```
shared void run() {
	value vertx = v_.vertx();
	value server = vertx.createHttpServer();	
	value handler = (HttpServerRequest request) => {
                //...
	};
	server.requestHandler(handler);
	server.listen(8080);
}
```
Now I get the following error:
```
Compiler bug: compiler bug: empty iterable literal with sequenced arguments:
+ { [SequenceEnumeration] (13:48-13:48) : {Nothing*}
  |  +  [SequencedArgument]
   at unknown
```

@sadmac7000 on Gitter suggested that `=>` and `{}` are usually an either-or proposition. So I removed the `=>`, and the code compiles fine. Nevertheless, even if the Vert.x docs are wrong, the above scary error message about a compiler bug should never be triggered (or seen by the user)! (And the earlier one about "Expression cannot be assigned" was completely unhelpful.)

**Comment by gavinking** [comment]
@lukehutch with the code you've shown, I don't get a "compiler bug". Perhaps it's whatever you've elided with the `//...`?

I agree that the message `Expression cannot be assigned` could be improved.

**Comment by gavinking** [comment]
@lukehutch I have improving the parser in @e5282a6, so that Ceylon produces a much nicer error in this case. (It was a matter of making the parser accept some things that are definitely not legal syntax.)

**Comment by gavinking** [comment]
I'm closing this, because it was mis-filed against the IDE, when really the problems were in the vert.x docs, and the parser. @lukehutch if you're unhappy with the fix, please open a new issue against ceylon/ceylon.

**Comment by lukehutch** [comment]
Sorry, this is the complete code. The compiler error occurs at the '{' on the line marked "//*". Yes, the expression is incorrect, but I'm sure it shouldn't trigger a "compiler bug" error.

```
import io.vertx.ceylon.core {
	v_=vertx
}
import io.vertx.ceylon.core.http {
	HttpServerRequest
}

shared void run() {
	value vertx = v_.vertx();

	value server = vertx.createHttpServer();
	
	value handler = (HttpServerRequest request) => {    //*
		
		// This handler gets called for each request that arrives on the server
		value response = request.response();
		response.putHeader("content-type", "text/plain");
		
		// Write to the response and end it
		response.end("Hello World!");
	};
	
	server.requestHandler(handler);
	
	server.listen(8080);
}
```

(and module.ceylon is):
```
native ("jvm") module webtest "1.0.0" {
	shared import io.vertx.ceylon.core "3.2.0";
	shared import io.vertx.ceylon.web "3.2.0";
}
```

**Comment by gavinking** [comment]
Right, so my change to the parser seems to have fixed the "compiler bug" too.

**Comment by lukehutch** [comment]
I forgot I had this typo in my code still, and came back to Ceylon today after updating everything to the latest version. I'm still seeing "compiler bug" here with the latest git version, at least in the Eclipse IDE (I haven't tried it in the commandline compiler).
