### ISSUE TITLE
IDE does not display any documentation when hovering vert.x APIs

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1660]
Vert.x does the right thing and encodes documentation using `@DocAnnotation$annotation$`, but the IDE just refuses to display it. This is *terrible*, since it means there is simply no way to view the documentation for any vert.x APIs.

@davidfestal what's your take on this?

**Comment by davidfestal** [comment]
@gavinking : the case when a Ceylon declaration is written in Java was simply not taken in account. The IDE Documentation hover assumes the Ceylon source to be available. I added support for annotations retrieved from the model loader.

**Comment by gavinking** [comment]
Great, thanks :)
