### ISSUE TITLE
option to re-run failed tests

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-eclipse#1664]
It would be nice to have the option to re-run only the tests that have failed in the "Ceylon Test" window. 

As a bonus, it would be nice to be able to manually select multiple items to run (something like highlight multiple nodes, then right click "run" on one of the selections to run the selected tests.)

**Comment by thradec** [comment]
Done.

**Comment by jvasileff** [comment]
Cool!

On Jan 10, 2016, at 1:44 PM, Tomas Hradec <notifications@github.com<mailto:notifications@github.com>> wrote:


Done.
