### ISSUE TITLE
Auto-generated equals method is invalid (syntax error)

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-ide-eclipse#1669]
Enter the following class definition:
```ceylon
class C() {
    shared String s = "";
    
}
```
In the blank line, type `equa`, Ctrl+Space, and auto-complete the `shared actual Boolean equals(Object that)` entry. The result is:
```ceylon
class C() {
    shared String s = "";
    shared actual Boolean equals(Object that) {
        if (is C that) {
            return s==that.s && 
                ;
        }
        else {
            return false;
        }
    }
}
```
`&&;` is, of course, a syntax error.

This probably broke during the migration to Ceylon, but that’s just a guess.

<sub>Aside: this broken code also causes backend errors, though they don’t happen on the CLI. Should I report these in ceylon/ceylon?</sub>

**Comment by gavinking** [comment]
Fixed.

**Comment by lucaswerkmeister** [comment]
Um, thanks, I guess I’ll close ceylon/ceylon-ide-common#24 then…
