### ISSUE TITLE
clicking on a failed test should take you to that test

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-eclipse#1677]
With:

```ceylon
shared test
void myTest() {
    fail();
}

void fail() {
    assert (1==0);
}
```

clicking on the failed test in the "Ceylon Test" window takes you to the `assert` statement. But,

1. Jumping directly to the innermost frame isn't always that useful. You need to know how you got there in order to troubleshoot the problem.
2. If you do want to jump to the point of the failed assertion or `throw`, you can use the Failure Trace.

**Comment by thradec** [comment]
this request is in clash with #1593, ping @tombentley

**Comment by tombentley** [comment]
Haha! What an idiot I am. Maybe it should be an option, on a context menu or toggled from the toolbar?

**Comment by thradec** [comment]
What about compromise, jump to line inside test function/method from which the exception was thrown/propagated.

**Comment by jvasileff** [comment]
That sounds great to me. So if I understand correctly, it would link as marked below:

```ceylon
test shared void myTest() {
    assertEquals(2, 2);

    value actual = divide(2, 0); // <--- here
    assertEquals(actual, 0);
}

shared Integer divide(Integer a, Integer b) {
    return a / b; // <--- not here
}
```

**Comment by thradec** [comment]
yes
Dne 22. 1. 2016 16:13 napsal uživatel "John Vasileff" <
notifications@github.com>:

**Comment by thradec** [comment]
Done via 8765a9d.
