### ISSUE TITLE
"Ceylon Sources" No longer available under modules for 1.2.1 built modules

### ISSUE THREAD

**Issue by lukedegruchy** [ceylon/ceylon-ide-eclipse#1690]
I think this is due to the recent changes around where the *.src archive file is for SDK modules.

This means that it's not possible to view Ceylon source code for a given 1.2.1 module in the IDE as only "Java Binaries" shows under that module, and not "Ceylon Modules".

The IDE should point to the new location for the *.src archive files to expose this.

**Comment by bjansen** [comment]
I just tested it on a sample project, and everything works as expected, closing.

<img width="316" alt="capture d ecran 2016-12-22 a 18 09 57" src="https://cloud.githubusercontent.com/assets/281528/21433899/1241d04a-c872-11e6-82d2-28c982a75daf.png">

**Comment by lukedegruchy** [comment]
Confirmed.
