### ISSUE TITLE
Import overwrites .gitignore

### ISSUE THREAD

**Issue by simonthum** [ceylon/ceylon-ide-eclipse#1699]
Importing ceylon projects wipes out their .gitignore and writes one with ".exploded/". Since .gitignore is ususally checked in it's not a big issue, but could be handled better.

**Comment by jvasileff** [comment]
Yes. Very annoying. From some old notes I have, try this:

```
* Team/Git/Projects
    * Uncheck `Automatically ignore derived resources by adding them to .gitignore`
```

**Comment by simonthum** [comment]
Thanks!

That probably means it's not Ceylon IDE's fault, so I'm closing.
