### ISSUE TITLE
Missing .class files in compilation output

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-eclipse#1709]
> the java classes that are in source folders *without any ceylon file* are not integrated to the binary generation

**Comment by davidfestal** [comment]
This should have been fixed by da0759868f69f2ce38f086ee13cae18c40997faf and ceylon/ceylon-ide-common@aea58397958eb3783148f8ec460df9a457b1add0 
@bjansen, @gavinking : can you confirm this is OK for you too ?

**Comment by bjansen** [comment]
It looks like it's working, yes.

**Comment by gavinking** [comment]
Agreed. It's fixed. Thanks.
