### ISSUE TITLE
Completion misses candidates

### ISSUE THREAD

**Issue by simonthum** [ceylon/ceylon-ide-eclipse#1718]
When I have a method

```
class X {}
m<T>(T[], ...) given T satisfies X {...};
```

and in the calling scope there is an `X[] sequence`, the 1.2.1 eclipse IDE provides me with `empty` and `[]` but misses `sequence` when I type a new method call to `m` and try to complete the first argument.

Sure, the method's generic `T` is not resolved at this point due to more arguments still missing, but since there is a concrete upper bound on `m`, `seq` could be safely determined to be a candidate regardless of whether T can be resolved.

**Comment by gavinking** [comment]
We would need to distinguish type parameter types that are not defined in a containing scope, and replace them with their upper bounds. Has to happen recursively too.

**Comment by gavinking** [comment]
I have pushed a hacky fix that solves the problem in certain special cases, including the important case mentioned above (sequences) but not yet in full generality.

**Comment by simonthum** [comment]
Cool, and well before 1.3 ;)

**Comment by gavinking** [comment]
Well I'm not sure which IDE release this would go into. It's only on master for now.

**Comment by simonthum** [comment]
OK, thanks!

**Comment by gavinking** [comment]
This is fixed.

**Comment by simonthum** [comment]
Yay!
