### ISSUE TITLE
Hovers broken when the theme is Ceylon alt

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-eclipse#1727]
This is due to a recent change in the management of hyperlink and active hyperlink colors

**Comment by gavinking** [comment]
@davidfestal this is fixed now, isn't it?

**Comment by gavinking** [comment]
@davidfestal Ping. Is it fixed?

**Comment by davidfestal** [comment]
Yes, I just tried it and it seems fixed. Don't know why I had not closed the issue...

**Comment by gavinking** [comment]
Thanks.
