### ISSUE TITLE
Quickfix for switch expressions

### ISSUE THREAD

**Issue by Vorlent** [ceylon/ceylon-ide-eclipse#1730]
The quickfix `add else clause` and `add missing case clauses` should also work with switch expressions.
Right now this feature already exists but only for switch statements
![statement](http://i.imgur.com/Zdhdtfn.png)
but not for switch expressions
![expression](http://i.imgur.com/nXPNlPu.png)

**Comment by Vorlent** [comment]
I forgot to mention that I'm still using version 1.2.0 of the IDE. Is this perhaps already implemented?

**Comment by bjansen** [comment]
It seems the current version of Ceylon IDE still doesn't support `switch` expressions.

**Comment by bjansen** [comment]
(of course this has to be implemented in ceylon-ide-common 😉)

**Comment by gavinking** [comment]
Fixed by ceylon/ceylon-common@d9cf4e4

**Comment by gavinking** [comment]
Done!
