### ISSUE TITLE
Android: support alternate Jdk provider

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-ide-eclipse#1732]
The model loader now supports alternate `JdkProvider` modules: you select one of the modules you import and say this is the Jdk provider. The IDE UI needs the ability to select a `module/version` as a Jdk Provider and pass this on to the model loader.

**Comment by davidfestal** [comment]
did you open an IDE issue to explain what has to be implemented ?

**Comment by davidfestal** [comment]
how does it work on the command line ? is it a command line option, a module annotation ?

**Comment by davidfestal** [comment]
@FroMage : you already did it right ?

**Comment by FroMage** [comment]
Command Line or config. Tbh i don't remember if the ide supports it or not.

**Comment by davidfestal** [comment]
There is also a text box one can fill when creating a project.
