### ISSUE TITLE
Find References / Find Assignments and shortcut refinement

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1735]
Find References and Find Assignments are broken w/r/t shortcut member refinement.

```ceylon
interface Super {
    shared formal String name;
    shared void m() {
        printIt(name);
    }
}

class Sub1() satisfies Super {
    name = "Gavin";
}
class Sub2() satisfies Super {
    shared actual String name = "Bastien";
}
```

- Selecting `name` in `Super` and running either Find References or Find Assignments should give me the assignment in `Sub1`. 
- And in the case of Find References, it's also supposed to give me the refinement in `Sub2`, IIRC, though I'm not 100% sure on that one.

**Comment by bjansen** [comment]
Same thing in Ceylon IDE 1.2.2

**Comment by gavinking** [comment]
Fixed, with loverly special cases. :-/
