### ISSUE TITLE
`.SNAPSHOT` versions

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-ide-eclipse#1736]
Take a look at the `snapshot-versions` branches in the Ceylon distribution and the SDK.
They've now switched to using modules that have `.SNAPSHOT` qualifiers in their versions.

The IDE needs to be adjusted to use those versions.

This could perhaps be made less of a burden by turning the Ceylon version number into a variable that gets substituted at build time, see for example the [OSGi MANIFEST](https://github.com/ceylon/ceylon/blob/28f480ba52546c9f4cba4623da8b9426a1d70416/dist/osgi/META-INF/MANIFEST.MF#L5) and how it gets treated in [the build](https://github.com/ceylon/ceylon/blob/28f480ba52546c9f4cba4623da8b9426a1d70416/dist/osgi/build.xml#L109)

**Comment by quintesse** [comment]
@davidfestal I've made all the changes I wanted to make to the distribution, SDK, formatter, conversion tool and ide-common projects but I can't get the last step, the Eclipse plugin, to work. Can you please take a look at that? It' probably some "1.2.3" I've forgotten to change into "1.2.3.SNAPSHOT" somewhere, but I can't find it.

**Comment by davidfestal** [comment]
done.
