### ISSUE TITLE
refinement completions and qualified parameter types

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1742]
Autocompleting the refinement of `visit()`, results in this code:

``` ceylon
object x extends Visitor() {
    shared actual void visit(Resource? resource) {}

}
```

Its should be `Tree.Resource`, not just plain `Resource`.

**Comment by gavinking** [comment]
Oh, wait, apparently this is specific to Java classes. @davidfestal any idea why?

**Comment by gavinking** [comment]
Simple Java code to reproduce:

```java
package stuff;

public class Tree2 {

	static class Term {}
	static class Plus extends Term {}
	static class Minus extends Term {}

}

class Visitor {
	void visit(Tree2.Plus plus) {}
}
```

Try extending `Visitor` in Ceylon.

**Comment by gavinking** [comment]
Well, actually this appears to be a problem with `TypePrinter`, which omits the qualifying type for some reason.

**Comment by gavinking** [comment]
In fact, it is the Java model loader which appears to be at fault here. It doesn't set the qualifying type in this case.

**Comment by bjansen** [comment]
Seems to be fixed, the generated refinement for your last example is now:

```ceylon
object x extends Visitor() {
	shared actual void visit(Tree2.Plus? plus) => super.visit(plus);
}
```

Closing.
