### ISSUE TITLE
mangled identifier with rename refactoring

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-eclipse#1760]
If you have an unsaved file, rename refactoring may not work correctly.

Start with the files below, saved:

`fileA.ceylon`:
```ceylon
void foo() {}
```
`fileB.ceylon`:
```ceylon
void bar() => foo();
```

Then:

1. Add a space character before `void bar` in `fileB.ceylon`, so that there will be unsaved changes
2. CMD-Option-R on `fileA.ceylon`'s `foo`. Rename to `fooBar`
3. Click "OK" in the "Save Modified Resources" dialog that will appear

The result in `fileB.ceylon` will be `  void bar() =>fooBaro();`. With two spaces, `  void bar() =fooBaroo();`

**Comment by gavinking** [comment]
Strange. Stuff like this definitely shouldn't happen. Perhaps it's a regression.

**Comment by gavinking** [comment]
OK, fixed now, and you get nicely prompted to save files, which didn't work before.

**Comment by jvasileff** [comment]
Cool, thanks!
