### ISSUE TITLE
Ceylon IDE changes JDT launcher preferrences

### ISSUE THREAD

**Issue by fwgreen** [ceylon/ceylon-ide-eclipse#1762]
After creating a new Java project, from the Java perspective, you are forced to pick a launcher the first time you run the project.  This behavior appeared with Ceylon IDE 1.2.2.

OS X 10.11.4
JDK8 u72
Eclipse Mars.2
![screen shot 2016-04-14 at 11 45 49 am](https://cloud.githubusercontent.com/assets/7098161/14534372/e7c595ec-0236-11e6-993d-0692b44bb031.png)

**Comment by davidfestal** [comment]
Yes, this dialog appears as soon as you have several available launchers for a launch configuration type.
You can avoid it by setting the preferred launcher in your workspace settings.
 
However we'll try to find a way to set this preference to the default (non-ceylon-aware) launcher automatically.
