### ISSUE TITLE
Support for relative path for maven settings localRepository path

### ISSUE THREAD

**Issue by DiegoCoronel** [ceylon/ceylon-ide-eclipse#1764]
Currently Im using a local maven repository generated by ceylon-gradle-plugin:
```xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                        http://maven.apache.org/xsd/settings-1.0.0.xsd">
    <localRepository>/Users/DiegoCoronel/Documents/workspace/discovery/build/maven-repository</localRepository>
    <offline>true</offline>
</settings>
```
and eclipse works fine, but when i try to use relative path:
```xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                        http://maven.apache.org/xsd/settings-1.0.0.xsd">
    <localRepository>build/maven-repository</localRepository>
    <offline>true</offline>
</settings>
```

Eclipse is not able to use the repository and my code breaks with lots of compilation errors for not found imports in module

I tried with CLI and it works nice. This looks something eclipse only.

**Comment by DiegoCoronel** [comment]
This issue for me is a blocker, because my team contains 10 devs and I really want to start coding in ceylon, but i need to make a smooth transition, so this is something my team will complain if i try right now

**Comment by davidfestal** [comment]
@DiegoCoronel : in this documentation: https://maven.apache.org/guides/mini/guide-configuring-maven.html, in section *Configuring your Local Repository*, the last note specifies that:
> The local repository must be an absolute path.

Is this `settings.xml` automatically generated by the gradle plugin ?

**Comment by davidfestal** [comment]
After debugging it, this is doable but would require a change in the CMR APIs, to pass the repository manager current working directory up to the `AetherResolverImpl` object.
I'll do it.

**Comment by DiegoCoronel** [comment]
>Is this settings.xml automatically generated by the gradle plugin ?

@davidfestal yes, but i dont know if its something @renatoathaydes plugin generates or if its delegated to gradle.

**Comment by renatoathaydes** [comment]
The Ceylon Gradle plugin generates the `settings.xml` file on the location given by the `mavenSettings` property, as explained in the [docs](https://github.com/renatoathaydes/ceylon-gradle-plugin#configuring-the-ceylon-build). That could be an absolute path or relative path (relative to the project's root).

**Comment by davidfestal** [comment]
OK. Anyway, I have identified the required change in the CMR to also allow a relative path in the `localRepository` Maven setting. So no change would be needed in the gradle plugin, and the `settings.xml` could be generated only once (with a project-relative path) and then shared as-is to team members.

**Comment by davidfestal** [comment]
Now if I add:
```
remote=aether:maven/settings.xml
```
in my `.ceylon/config` file,

and I have:
```
	<localRepository>maven/repository</localRepository>
```
in `<my project root>/maven/settings.xml`

Maven artifacts are searched/downloaded in the following local repository:
`<my project root>/maven/repository`

@DiegoCoronel : do you confirm that is works for you also on master ?

**Comment by DiegoCoronel** [comment]
@davidfestal I promise you that Ill take a look tonight, tks for you efforts in this issue

**Comment by DiegoCoronel** [comment]
@davidfestal It looks great, at really its amazing :) . I just have one point:

- When using project properties --> ceylon build --> module repositories and import using Add Maven Repository it would be great if the folder is in the root project to make it relative, currently its importing using absolute path
