### ISSUE TITLE
Rename refactoring places ill-fomed imports with keyword package names

### ISSUE THREAD

**Issue by simonthum** [ceylon/ceylon-ide-eclipse#1765]
If I rename packages (with subpackages) that have keyword sub-packages, the new imports are illegal.

E.g. a.x -> a.y leads a.x.out to become a.y.out, but imports and package declarations of that identifier are not protected (a.y.\iout). In fact they become a.y.outut in some places, probably because the protection which was there before is not being accounted for.

**Comment by gavinking** [comment]
Fixed, thanks.
