### ISSUE TITLE
Cannot create ceylon file in keyword package using the wizard

### ISSUE THREAD

**Issue by simonthum** [ceylon/ceylon-ide-eclipse#1767]
I know, I'm asking for trouble, but then again there is no other way to root  out those bugs. Behold:

![eclipse_ceylon_bug_2_220x193](https://cloud.githubusercontent.com/assets/580723/14670602/1a87df56-06ee-11e6-9768-21b6192416e7.png)

Either the package needs to be auto-unprotected / reprotected or manual protection (as entered in the screenshot) has to be parsed.

**Comment by gavinking** [comment]
Fixed.
