### ISSUE TITLE
Rename refactoring shows invalid dialog:

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-eclipse#1771]
While trying to rename a declaration, an error pops up stating that the file I'm currently refactoring is not saved:

<img width="627" alt="capture d ecran 2016-04-21 a 22 23 55" src="https://cloud.githubusercontent.com/assets/281528/14723134/c9673662-080f-11e6-8d4d-67f68c0bda87.png">

**Comment by bjansen** [comment]
Some references to `TestDocument` were not updated in other files.

**Comment by gavinking** [comment]
Should be fixed now.
