### ISSUE TITLE
errors building the SDK when disconnected from internet

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1780]
I tried to clean build the SDK from inside Eclipse while disconnected. I got lots of these:

```
The  caused an exception visiting a ImportModule node: "java.lang.RuntimeException: java.net.UnknownHostException: modules.ceylon-lang.org" at com.redhat.ceylon.cmr.impl.RemoteContentStore.urlExists(RemoteContentStore.java:335)
```

**Comment by davidfestal** [comment]
I already had to fix it there:
b59f20a18636bdf86c6f9bfd4b99193e39794552
But visibly it's not sufficient.

This error seems to related to the following change ceylon/ceylon@57e84269bbaa76d3df8cb4a8d2ab021c08c90183

**Comment by gavinking** [comment]
@tombentley your thoughts?

**Comment by tombentley** [comment]
Let me try it with `urlExists()` returning false when it encounters an `IOException`, to see whether that defeats the changes I made to make CMR better able to cope with rubbish connections.

**Comment by tombentley** [comment]
@gavinking does that resolve it for you?

**Comment by gavinking** [comment]
Building...

**Comment by gavinking** [comment]
Looks good to me :)

**Comment by gavinking** [comment]
Thanks.
