### ISSUE TITLE
NPE on malformed Iterable source code

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-ide-eclipse#1781]
This (broken) code (because of `{String*}>`)

``` ceylon
class IterableNodeList(String nodeList) satisfies {String*}>{
    shared actual Iterator<String> iterator() => nothing;
}

class IterableNode(String node) satisfies {String*}{
    shared actual Iterator<String> iterator() => nothing;
    for(childNode in IterableNode("")){

    }
}
```

compiled with the IDE 1.2.2`:

```
The Ceylon Java backend compilation failed
  with 2 malformed Javac tree cases
  with a throwable : java.lang.NullPointerException
```

**Comment by bjansen** [comment]
Looks like it's already been fixed, I get totally different errors (parse errors):

<img width="592" alt="capture d ecran 2016-12-22 a 14 28 54" src="https://cloud.githubusercontent.com/assets/281528/21427132/059a7db6-c853-11e6-8196-f3b9b0ea78f1.png">

@sgalles please reopen if you're still having the problem.
