### ISSUE TITLE
Frequent lockups

### ISSUE THREAD

**Issue by realms50** [ceylon/ceylon-ide-eclipse#1782]
This is a spinoff from another issue, where I mention I use CLI tools because Eclipse locks up from time to time.

It seems to happen when I type and the "intellisense" is about to kick in. IIRC I was not able to reproduce consistently. This was the initial 1.2.2 release, sorry if this has been fixed in an update.

**Comment by gavinking** [comment]
Should have already been fixed by @3a586f98944812a43a61cd2262e2c2bec1400d2c and by some optimizations to the typechecker.

**Comment by realms50** [comment]
OK, thank you. Doesn't this warrant an interim release? The IDE is fairly unusable as is, so if this indeed solves the problem...
