### ISSUE TITLE
Unit test view and peformance

### ISSUE THREAD

**Issue by simonthum** [ceylon/ceylon-ide-eclipse#1788]
I have another - very reproducible - performance issue: Eclipse with a visible ceylon unit test view constantly eats 1/2 core, independent of the presence or volume of unit test results. As soon as I close or hide the view, eclipse drops to zero CPU usage, only to creep up when opening/showing it. I did not observe such behaviour with other views.

**Comment by gavinking** [comment]
@thradec would you be able to find time to take a look at this one, please?

**Comment by simonthum** [comment]
In hindsight, this issue is behind a fair share of the performance problems I experience(d). E.g. when the view is open, switching preference panels is next to impossible. Hiding it fixes that. It'd really help if you could reproduce it; I'm on Gentoo Linux, Java 8 r74 and Eclipse Mars.2.

**Comment by thradec** [comment]
I would like to help, but it is not reproducible on my machine (osx 10, java 8, eclipse mars 2). I have ceylon test view opened all the time and I have never observed any performance issue. Maybe somehow connected with linux eclipse distribution. Is anybody else observing this issue? Are you able to track where the time is spend?

**Comment by simonthum** [comment]
Hi Thomas, thanks for looking into it!

I can't really track it down so far. I can observe through top that my eclipse which is 1-4% CPU when idle suddenly doesn't every go below 100% when the view is visible. So according to top, that would be ~1 CPU eaten away.

I guess that it has to do with rendering as minimizing eclipse has roughly the same effect, the CPU goes back to normal, but that doesn't really help for average usage scenarios ;(

Regarding tracking down, I still get random stack traces from eclipse's UI freeze monitoring, but I seem to have found enough knobs to tune. For example, I configured eclipse to only have 4 or fewer editor windows open, which seems to keep the problem below my frustration threshold.

That said, the unit test view sill sucks. My stomach tells me it's rendering because other GUI apps like firefox behave worse. I tried to use jvisualvm on it but I did not see anything particular.

**Comment by simonthum** [comment]
One more: the JVM memory is pretty much constant without visible unit test view (eclipse being idle), but with the view it increases at about 5 MB / s. It's not a memory problem per se, the GC will clean up just fine, but there is a lot of churn. It looks a lot like constant forced view updates.

**Comment by simonthum** [comment]
So I checked with perf top.

 4.92%  libgdk-3.so.0.1800.7        [.] gdk_cairo_region_create_from_surface  
     2.06%  libjvm.so                   [.] _ZNK13ParMarkBitMap19live_words_in_ran
     1.87%  libjvm.so                   [.] _ZN14PhaseIdealLoop13get_late_ctrlEP4N
     1.47%  libglib-2.0.so.0.4600.2     [.] g_hash_table_lookup  

4.82%  libgdk-3.so.0.1800.7        [.] gdk_cairo_region_create_from_surface
     1.42%  libglib-2.0.so.0.4600.2     [.] g_hash_table_lookup                 
     1.26%  libgobject-2.0.so.0.4600.2  [.] g_type_check_instance_is_a   

gdk_cairo_region_create_from_surface is always on top, but the hash lookup and  ZN14PhaseIdealLoop13get_late_ctrlEP4N (not recognized by c++filt) are repeatable top-runners when the UT view is active.

For whatever reason it's hitting expensive gtk paths, or hitting hard on average gtk paths.

**Comment by simonthum** [comment]
OTOH the more reliable number is again the generic one:

```
PerfTop:    7674 irqs/sec  kernel:15.5%
```

Idle no-UTV eclipse sees 250 irqs (not sure which it counts) and 50 % kernel time, consistent with top reporting high CPU for eclipse.

An interesting bit is that the gdk_ciaro stuff is on top even when minimized. I guess I need to do more java-specific profiling ubt that needs to wait a bit.

**Comment by thradec** [comment]
@simonthum thanks for additional information, if you could provide _more java_ profilling, it would be great

@davidfestal did you experience some performance issues, which will affect only specific platform?

**Comment by simonthum** [comment]
For now, I preferred to use the source and ask whether

https://github.com/ceylon/ceylon-ide-eclipse/blob/master/plugins/com.redhat.ceylon.test.eclipse.plugin/src/com/redhat/ceylon/test/eclipse/plugin/ui/TestRunViewPart.java#L349

is really neccessary. Granted, the code looks right, but unless most other views have such a "thread" too I'm focusing on that.

**Comment by thradec** [comment]
Similar "thread" can be found in junit plugin [1], it's role is to update UI only when the test is running and only in specific time interval, not after every change in model.

[1] https://github.com/eclipse/eclipse.jdt.ui/blob/master/org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/ui/TestRunnerViewPart.java#L844

**Comment by simonthum** [comment]
You. nailed. it.  I don't believe it! The JUnit view is slightly less expensive, making up for 80% CPU according to top. Fun fact: They don't add up, i.e. they top at 100% when both are open.

The question is what to do about it. Can I pretty please get a system property to adjust the interval?

**Comment by thradec** [comment]
It is really strange, that on your system the UI update is so expensive, but for now I'm happy to go with system property workaround.

Done via 73a91d7, the property is `eclipse.ceylon.testview.refresh`, let me know if it helped.

**Comment by simonthum** [comment]
I'm building now but it'll take some time. The more interesting fact, to me, is that nothing should even be "running" without results. Maybe they aren't really `null` but something empty?

**Comment by simonthum** [comment]
Strange enough,  no  difference  with `-Declipse.ceylon.testview.refresh=3000`. I'll see if I can fire up the perf jvmti tooling,  unless you come up with something better.

**Comment by simonthum** [comment]
Looks a lot like https://bugs.eclipse.org/bugs/show_bug.cgi?id=378077 and maybe https://bugs.eclipse.org/bugs/show_bug.cgi?id=354842

**Comment by simonthum** [comment]
OK, going back to GTK+ 2.x fixes all these funny issues I experienced.  TL;DR:

```
SWT_GTK3=0 eclipse
```
is the way to go on linux with gtk2 and 3 installed. I suspect SWT's still missing flushes, subjecting itself to X protocol randomness. But at eclipse there are enough bugs open; I'll retry with Neon maybe.

**Comment by simonthum** [comment]
@stempler you might want to know about the above?

**Comment by simonthum** [comment]
This is just such a vast improvement, I recommend that you stick it to the download instructions or something! No reason to frustrate others.

I can't believe what a well-behaved application is now in front of me. The popups are now readable (used to be white on black) and completion comes up reliably. It all feels much more useable! 

@thradec Tanks for you help and kicking me to it. If you want to revert the property commit feel free to do so.

**Comment by stempler** [comment]
@simonthum Thanks for the hint. Had the same issue since updating to Ubuntu 16.04 - Eclipse / HALE was unusable more or less from the start. Switch to GTK 2 can also be done by adding
```
--launcher.GTK_Version
2
```
 to `eclipse.ini` (before the VM arguments).

**Comment by simonthum** [comment]
Good to know, thanks!

**Comment by thradec** [comment]
@simonthum I'm glad it is working for you now

**Comment by simonthum** [comment]
Epilogue

It turned out that GTK 2 wasn't the only performance problem I hit. My laptop's manufacturer managed to slip a folded plastic clip onto the CPU package, fittingly protecting the heat conductor from excessive CPU heat.

However, the relative improvement between fixing a CPU constantly running into overheat protection and switching to GTK2 is definitely on GTK2's side. Just to give you an idea of the magnitude of improvement.

**Comment by gavinking** [comment]
Wow!

**Comment by simonthum** [comment]
Yep. My very own epic bug journey ;( Sorry to have bothered you all!
