### ISSUE TITLE
Changes in a dependency project are not detected

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-eclipse#1792]
I have both ide-common and ide-eclipse open. If I remove a formal function from `DocGenerator`, save then go delete the actual declaration in `EclipseDocGenerator`, it does not see the changes I made in ide-common and complains that `Formal member getUnitName of DocGenerator not implemented in class hierarchy`. I have to clean build both projects to remove the error.

* I didn't change my project setup recently, and ide-eclipse still has a dependency to ide-common
* "build automatically" is enabled

**Comment by davidfestal** [comment]
I just tested and this works correctly. Closing.
