### ISSUE TITLE
Development update site not updated since version 1.2.0

### ISSUE THREAD

**Issue by lucono** [ceylon/ceylon-ide-eclipse#1795]
The Ceylon IDE eclipse plugin development update site ([specified here](http://ceylon-lang.org/documentation/1.2/ide/install/#installing_from_the_development_unstable_update_site)) does not contain versions of the IDE subsequent to 1.2.0.

Is there a way to get development builds of versions of the IDE subsequent to the latest stable 1.2.2 release version?

Much thanks.

**Comment by bjansen** [comment]
You can use nightly builds located here: https://ci-ceylon.rhcloud.com/job/ceylon-ide-eclipse/ws/site/target/repository/
