### ISSUE TITLE
typing letter from results in Open Declaration should focus filter box

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1801]
Like in IntelliJ, when you're navigating the result list, and you type a letter, that should refocus the filter input.

**Comment by gavinking** [comment]
Done. We actually should send this change as a patch to Eclipse's `FilteredItemsSelectionDialog`.

**Comment by bjansen** [comment]
I want that in the outline popup too :)

**Comment by gavinking** [comment]
I'll have a look.

**Comment by gavinking** [comment]
@bjansen done, just especially for you, because I love you.

**Comment by bjansen** [comment]
Aww that's really sweet of you, man!
