### ISSUE TITLE
The results of local typechecking (especially error annotations), disappear after completion

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-eclipse#1808]
This might to be a result of the optimization made here: 0cafe6b91c9dbf5caeed1fc99324ad5ea4311d0d.

**Comment by gavinking** [comment]
If this is something that happens _occasionally_ (I think it is) then I think it's tolerable. The java editor also exhibits this sort of behavior at times. OTOH, you could try just using `REPARSE_SCHEDULE_DELAY*2` and see if that helps.

Please don't remove the optimization, it is very useful.

**Comment by davidfestal** [comment]
In fact I already fixed it without removing your optimization. I still have to push it though.
