### ISSUE TITLE
Support new feature fat-jar from version 1.2.3

### ISSUE THREAD

**Issue by DiegoCoronel** [ceylon/ceylon-ide-eclipse#1810]
The release 1.2.3 have a feature to create fat-jar and IDE can have the options:
- Create fat-jar
- Run as Java Application (fat-jar) //or something like that

**Comment by DiegoCoronel** [comment]
The usecase i have now is to use JBoss Swarm, after talk to @FroMage we believe that JBoss Modules is currently a problem and one approach to make it work is with fat-jar.

**Comment by davidfestal** [comment]
Finished:
- a new `Run/Debug Java Application Packaged As FatJar` menu item is available in the Ceylon Explorer on Ceylon project nodes and module nodes. It will create a `FatJar` from a given module (and its dependencies), set the starting method to the `run`module method, and run the FatJar as a standard Java application. 
- if the one of the modules of a Ceylon project imports the `javax.javaeeapi` module, a new `Run/Debug Java Application Packaged By WildFly Swarm` menu item is available in the Ceylon Explorer on Ceylon project nodes and module nodes. It will create a war file and a Swarm archive from a given module (and its dependencies) and run the Swarm archive as a standard Java application. Note: The `ceylon.swarm` plugin should be installed on your system.  

Though both FatJar and Swarm launch menus are run as standard Java application, there is still the full support for Ceylon debugging, with debug hovers, type parameters, etc ...

In fact the `FatJar` and `Swarm` launch menus correspond to a single type of launch configuration: the `JarPackagedCeylonApplication`.You can create such a launch configuration manually, and then choose which Jar packaging tool will be used: `FatJar` or `Swarm`.

When running such launch configurations, the output of the packaging command (`ceylon fat-jar` or `ceylon swarm`) is available in the Console view.
