### ISSUE TITLE
Enhancement: Ceylon Repository Explorer: Display, open or link to module documentation

### ISSUE THREAD

**Issue by lukedegruchy** [ceylon/ceylon-ide-eclipse#1812]
This is a feature/enhancement request.

Currently the Ceylon Repository Explorer only shows the module name as well as all available compatible versions with the current release, as well as "Add Module Import". 

It would be useful to allow the user to at least do a cursory review of the module's documentation before actually using it.  They should be able to browse the module documentation either by having the Ceylon IDE:

a) Open the module docs inside of Eclipse in a README-type viewer
b) Open the Herd website inside the Eclipse web browser
c) Open the Herd website in the user's default web browser
d) Display the module's URL on Herd and allow the user to copy and paste it into a browser.

Presumably this could be extended to non-Herd repos in the future.

**Comment by gavinking** [comment]
WDYM? What's wrong with this:

<img width="599" alt="screen shot 2016-07-24 at 4 24 28 pm" src="https://cloud.githubusercontent.com/assets/579974/17084333/2d85d50a-51bb-11e6-882e-8b68dff278f4.png">

**Comment by lukedegruchy** [comment]
Odd I don't see this in the IDE that I built on July 18th and I'm getting build errors building this today.  Was this added recently?

**Comment by lukedegruchy** [comment]
Nevermind, I didn't click the show/hide documentation button.
