### ISSUE TITLE
Double dots

### ISSUE THREAD

**Issue by martyn-evgeny** [ceylon/ceylon-ide-eclipse#1815]
Hi!

After typing two dots  Eclipse Ceylon IDE is freezes. This issues like: https://github.com/ceylon/ceylon-ide-eclipse/issues/1814 but the IDE hangs much longer.

**Comment by fwgreen** [comment]
This happened to me!  I entered two dot operators by accident and the IDE locked up (much worse than the regular "Preparing completions..." freeze).  Force quitting generates a crash report.

![screen shot 2016-08-27 at 10 48 19 am](https://cloud.githubusercontent.com/assets/7098161/18036689/004b946c-6d40-11e6-92f9-b6d07a211815.png)

**Comment by davidfestal** [comment]
Fixed
