### ISSUE TITLE
Preferences > Keys > When > "Working in Ceylon Perspective" only applies to "Ceylon" perspective

### ISSUE THREAD

**Issue by lukedegruchy** [ceylon/ceylon-ide-eclipse#1819]
The key binding "When" category "Working in Ceylon Perspective"  only applies to the literal "Ceylon" perspective and not any perspective copied from "Ceylon".   So, for example, creating and using a perspective called "Ceylon2" will invalidate that key binding.

The expected behaviour should be that any perspective spawned from Ceylon should gain a "When" "Working in Ceylon Perspective" key binding.

A more specific example is a key binding for Show Package Explorer View "When" "In Windows" to CTRL-P.  Another key binding is Show Ceylon Explorer View  "When" "Working in Ceylon Perspective" to CTRL-P.  When working in the Java perspective CTRL-P binds to Show Package Explorer and when working in the literal "Ceylon" perspective it binds to Show Ceylon Explorer View.   However, when switching to "Ceylon2" CTRL-P once again binds to Show Package Explorer View.

The workaround is to backup the original "Ceylon" perspective and then modify the "Ceylon" perspective with the settings from "Ceylon2".

**Comment by gavinking** [comment]
Hrm. Do you know how to do that?

**Comment by lukedegruchy** [comment]
After a lot of Googling and grepping for "perspective" in the ceylon-ide-eclipse source code, this is still mysterious to me.

This seems to be the best resource I could find:

http://www.programcreek.com/2013/02/eclipse-plug-in-development-creat-a-perspective/

Near as I can tell, there's no concept of a "perspective type" or "perspective family", although there might be better documentation that I couldn't find.

I think it's probably safe to say this is a limitation of Eclipse itself, and not ceylon-ide-eclipse.
