### ISSUE TITLE
when creating a new project, bootstrap version 1.3.0 is not available

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-eclipse#1824]
Bootstrap version `1.3.0` is not available. The latest is `1.2.2`:

<img width="323" alt="screen shot 2016-09-14 at 12 49 10 pm" src="https://cloud.githubusercontent.com/assets/236050/18521444/243bbfb8-7a7a-11e6-86f9-dd9459c94af1.png">

**Comment by quintesse** [comment]
Well Ceylon 1.3.0 isn't released yet, so that's correct ;)

**Comment by bjansen** [comment]
This has been fixed in the released version of Ceylon IDE 1.3.0
