### ISSUE TITLE
Better syntax aware completion proposals

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-ide-eclipse#1826]
I have a declaration, like this:

```
FooBar foo = FooBar();
//   ^ caret here
```

where `FooBar` is not imported, and rather that using the "import FooBar from org.example.foobar" quickfix I have asked for completion of `FooBar` I get a list of completions that includes org.example.foobar::FooBar, which is great. But I would dearly, dearly love if that list was ordered in a context sensitive way, because it suggests completing as the invocations `FooBar()` and `FooBar{}` before the type `FooBar`. But it's a declaration, stupid, so obviously I mean the type!

**Comment by bjansen** [comment]
I simply removed invocation proposals when completing a `Tree.BaseType` (they're still here for `Tree.BaseTypeExpression` though).

@gavinking could you please check if I didn't break completion in other cases that I didn't think of?

**Comment by gavinking** [comment]
@bjansen I'm pretty certain you'll need to roll back this change.

Consider:

```ceylon
Foo
shared Integer f() 
```

That would be parsed as `Foo shared`.

I think the original bug report is garbage.

**Comment by gavinking** [comment]
> But it's a declaration, stupid, so obviously I mean the type!

@tombentley we just can't be sure of that. The IDE has to work correctly for lots of syntactically incomplete/broken code, as well as for well-formed code.

**Comment by bjansen** [comment]
@gavinking in that specific case you mentioned, the completion still behaves as expected, i.e. it will import `Foo` without suggesting invocations. I don't think an invocation at that location would be legal?

**Comment by gavinking** [comment]
@bjansen WDYM? Because I never want to insert a new line of code before an attribute or function declaration??!

**Comment by bjansen** [comment]
In your example, calling the code completion after `Foo` will now result in a single proposal `Foo`, that will automatically import the class. Previously, it also proposed `Foo()`, which I think is not valid at that specific location. So the new behavior is also correct in that case.

**Comment by gavinking** [comment]
Bastien, that's just not right.

This is legal Ceylon code:

```ceylon
Foo();
shared Integer f() => ... ;
```

But you don't want to help me write that. You're forcing me to add a `;` in order to make autocompletion work correctly. That's crazy.

Look, I know all the completion logic looks messy and crazy to you but in fact it was all quite carefully thought out on the basis of what is needed when I'm editing *incomplete* code.

**Comment by bjansen** [comment]
Err right, I was only thinking about toplevel code, but it's legal inside a class... I'm going to revert my change and close the issue as "won't fix" then.

**Comment by gavinking** [comment]
@bjansen well, I suppose you *could* do it for the case of a *toplevel* `BaseType`. i.e. for one that is not nested inside any kind of `Body`.

**Comment by bjansen** [comment]
I'm not sure it's really worth having that behavior in such a "limited" scope, so I reverted my change.

**Comment by gavinking** [comment]
OK.
