### ISSUE TITLE
Support navigation to java source when the origin is maven

### ISSUE THREAD

**Issue by DiegoCoronel** [ceylon/ceylon-ide-eclipse#1828]
Using imports from maven in modules and trying to navigate in declared classes in ceylon source give me the message:
`the JAR of this class belongs to container Ceylon Project Modules which does not allow modifications to source attachments on its entries` and this way i cant add/navigate the source.

**Comment by bjansen** [comment]
I believe this is caused by `CeylonProjectModulesContainer.getSourceArtifact()` that instantiates an `ArtifactContext` with a `null` namespace, which means source archives are never retrieved correctly for Maven dependencies.

**Comment by billoneil** [comment]
👍
