### ISSUE TITLE
Autocompletion of warning names in suppressWarnings

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-ide-eclipse#1829]
I would love auto complete on warning names:

```
suppressWarnings(/*HERE*/)
class SomeClassWithWarnings() {
    //
}
```

**Comment by bjansen** [comment]
Indeed, that would be very helpful.

**Comment by gavinking** [comment]
@tombentley well, OK, but really you should be using the quick fix to add `suppressWarnings` annotations!

**Comment by bjansen** [comment]
Done!

<img width="427" alt="capture d ecran 2016-12-23 a 15 53 26" src="https://cloud.githubusercontent.com/assets/281528/21456395/119836c8-c928-11e6-8cc9-7b7eb79ec03f.png">

**Comment by gavinking** [comment]
Great!!! Much better,

**Comment by tombentley** [comment]
Cool, thanks!
