### ISSUE TITLE
Ceylon errors missing from Problems view when Project scoped

### ISSUE THREAD

**Issue by ncorai** [ceylon/ceylon-ide-eclipse#1831]
In **Ceylon IDE 1.3.0.v20160916** and **Eclipse Neon**, in the _Problems_ view, with the down arrow select _Configure Contents..._ then uncheck _All Errors_ and check _Errors/Warnings on Project_. After clicking _OK_, no Ceylon errors or warnings are displayed anymore.

Workaround: check _Errors/Warnings on Selection_

**Comment by bjansen** [comment]
@ncorai I can't reproduce your problem. I created an error in a project, and when I select it in the Ceylon Explorer view, I can see the errors immediately in the Problems view. If I open a second project and switch back and forth between them, the error is correctly shown/hidden, without having to select anything in the Ceylon Explorer.

**Comment by ncorai** [comment]
Sorry for taking so long to get back to you. I've since upgraded Ceylon to 1.3.2 (in-place) and still see the issue but I'll install Eclipse Oxygen from scratch soon and let you know whether the issue is still happening.

**Comment by ncorai** [comment]
Works in my new dev environment, which I've recreated from scratch for Eclipse Oxygen. Closing the issue.
