### ISSUE TITLE
completion of keywords broken

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1838]
Completing `function` inserts the text `functionun`.

**Comment by gkutiel** [comment]
same problem with `value` see [ilustration](https://postimg.org/image/h7vqcd7kd/)

**Comment by davidfestal** [comment]
I cannot reproduce this on master. @gavinking is it still broken for you ?

**Comment by gavinking** [comment]
Yep, still broken. But here's how to reproduce. Type "f", open the completion popup, type "un", and then select "function" from the popup.

**Comment by davidfestal** [comment]
Ah, OK, I'll retry then.
