### ISSUE TITLE
clean build results in error on static member class

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1839]
Running a clean build on this code results in a backend error:

``` ceylon
shared class Hello {
    shared static class Member() {}
    shared new() {}
}

shared void run() {
    Hello.Member();
}
```

> Ceylon backend error: an enclosing instance that contains Hello.Member is required

**Comment by davidfestal** [comment]
I cannot reproduce this one, either in Java 7 and Java 8, either in the default module or in a real module.
@gavinking : is it the same for you ?

**Comment by gavinking** [comment]
Nope, it's still happening. I don't understand why you failed to reproduce it.

**Comment by gavinking** [comment]
Ah, OK, now I understand. To reproduce this bug, you must have a `.java` file somewhere in the project. (It can be empty.)

**Comment by davidfestal** [comment]
OK, now I have it, but only in the default module

**Comment by davidfestal** [comment]
@gavinking @FroMage : I also get the error when running from the CLI

**Comment by gavinking** [comment]
Well report it against the compiler then.

**Comment by davidfestal** [comment]
I fixed it indeed

**Comment by gavinking** [comment]
Great!
