### ISSUE TITLE
Override functional-interface methods in model loader

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-ide-eclipse#1840]
To support ceylon/ceylon#1617. See:

- `CeylonModelLoader.getFunctionalInterfaceType(TypeMirror)`
- `CeylonModelLoader.isFunctionalInterfaceType(TypeMirror)`
- `CeylonModelLoader.isFunctionalInterfaceType(ClassMirror)`

For inspiration. I assume Eclipse and IntelliJ will have enough infra to answer the question of whether a type is a SAM or not and give you the abstract method reference.

**Comment by gavinking** [comment]
@bjansen @davidfestal Just FTR, this is super-high priority.

**Comment by davidfestal** [comment]
@gavinking :I'm working on it.

**Comment by gavinking** [comment]
@davidfestal thanks

**Comment by davidfestal** [comment]
Done.

**Comment by davidfestal** [comment]
@FroMage maybe you would like to test this more deeply. There are certainly cases I'm not aware of.
