### ISSUE TITLE
npm modules not downloaded on incremental build

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1845]
Just adding an `npm:` import to the module descriptor is not enough to trigger installation of the module. You need to do a Clean build to force it to occur.

**Comment by davidfestal** [comment]
@gavinking : the fix for ceylon/ceylon-ide-common#90 also fixed this one. Do you also confirm that it's working correctly now , as it is for me locally ?

**Comment by davidfestal** [comment]
@gavinking please reopen it if it doesn't work for you.
