### ISSUE TITLE
Module conflict error crashes FatJar packaging tool

### ISSUE THREAD

**Issue by fwgreen** [ceylon/ceylon-ide-eclipse#1863]
From the command line, a module conflict results in...
```
Module org.slf4j:slf4j-api has multiple versions loaded: 1.6.4, 1.7.21 (use "--force" to select latest version 1.7.21)
ceylon fat-jar: Module conflict error prevented classpath generation: try
running "ceylon info --print-overrides app/1.0.0" to display an override file
you can use with "ceylon classpath --overrides override.xml app/1.0.0" or try
with "ceylon classpath --force app/1.0.0" to select the latest versions
```
But from within Eclipse the same conflict results in...
![fatjar tool crash](https://cloud.githubusercontent.com/assets/7098161/21608800/a10edff2-d18c-11e6-82ad-d00f43c04455.png)

**Comment by gavinking** [comment]
Hi @davidfestal, could you take a look at this one please?

**Comment by gavinking** [comment]
Fixed, I've just added `--force` to the arguments passed to `fat-jar`.
