### ISSUE TITLE
Make keyboard shortcuts work (better)

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-eclipse#1874]
This one has really bugged me since [2015](https://github.com/ceylon/ceylon-ide-eclipse/issues/1513): the shortcut `⌘⇧T` disappears, and there is no easy way to access "Open Declaration". I'm guessing other shortcuts are affected as well.

I now know a workaround, but I'm guessing most users would just go on missing this feature.

The problem is that when re-installing the plugin (e.g., instal a new version of Eclipse & the Ceylon plugin but keep the same workspace), the "old" perspective is renamed to "&lt;Ceylon>", but the keyboard bindings rely on it being named "Ceylon" (without the weird angle brackets). By default, the workspace will continue to display the "old" perspective that has been renamed.

The workaround is to "Save perspective as" "Ceylon" (overwriting the newly installed duplicate perspective). The perspective and all files must then be re-opened.

Note that the dependence on the perspective name also prevents users from being able to have multiple custom Ceylon perspectives (I guess some users find that useful?)

I don't know what the right fix is, but there *must* be some solution, like not re-creating and re-naming perspectives if they already exist or not depending on the workspace name for key bindings.

**Comment by gavinking** [comment]
@jvasileff I think you should report this as a bug against the Eclipse platform. We don't have any code at all to handle the Ceylon perspective, just stuff in `plugin.xml`. I don't believe it can possibly be anything the Ceylon plugin is doing wrong.

**Comment by gavinking** [comment]
@jvasileff it's *vaguely* possible that b22cd15882b2ca9b3bfc705f5289809fb4edd629 might help. But probably not.

**Comment by jvasileff** [comment]
Is there some reason 'T' and 'H' aren't configured for "Editing Ceylon Source"? Manually making the change makes this work in the "<Ceylon>" perspective.

<img width="767" alt="screen shot 2017-07-02 at 4 22 06 pm" src="https://user-images.githubusercontent.com/236050/27773288-322b60ce-5f44-11e7-8153-950573ed8b8b.png">

**Comment by gavinking** [comment]
'Editing Ceylon Source' means the shortcut is only active when a Ceylon editor is focused. That's not the behavior we want. We want the shortcut active whenever we're in the Ceylon perspective. The job of `CeylonStartup.updateContext()` is to detect when we switch in and out of the perspective.

**Comment by jvasileff** [comment]
I don't understand why it would hurt to have the shortcuts work when editing Ceylon source in other perspectives, but if this is not a bug I'll go ahead and close it.

**Comment by gavinking** [comment]
> I don't understand why it would hurt to have the shortcuts work when editing Ceylon source in other perspectives

Well, because in the Java perspective, that shortcut is supposed to open the *Java* 'Open Type' dialog.

Anyway, like I said, this is actually a bug in Eclipse.

**Comment by jvasileff** [comment]
If in a Java perspective and editing Java files, then yeah, but at that point you wouldn't be editing Ceylon sources.

> Anyway, like I said, this is actually a bug in Eclipse.

It seems to me everything is working as intended, even if I don't agree with some of it. Too much weight is given to perspectives given their fragility.

**Comment by gavinking** [comment]
> It seems to me everything is working as intended

Well, not precisely: if upgrading the plugin sometimes breaks the keybindings, that's certainly a problem.
