### ISSUE TITLE
upgrade Eclipse dependencies to Oxygen

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1877]
The Eclipse IDE now depends on Oxygen, but the generated list of module dependencies in `module.ceylon` is still being generated from the Luna platform. I tried changing the couple of places where "luna" is hardcoded in the build scripts and `pom.xml` to "oxygen", but apparently that wasn't enough, since I get build errors.

I need to do this upgrade in order to make use of the new support for higher-resolution icons in Oxygen.

@davidfestal can you help me out here please?

**Comment by davidfestal** [comment]
I'm looking into it

**Comment by gavinking** [comment]
Thanks David.
