### ISSUE TITLE
maven imports broken in Eclipse

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1878]
`maven:` imports result in the error:

> Unknown import namespace maven

This is blocking the release of 1.3.3.

**Comment by gavinking** [comment]
The `RepositoryManager` has no `CmrRepository` with the namespace `maven`.

**Comment by FroMage** [comment]
Probably due to the new aether module being optional?

**Comment by gavinking** [comment]
> Probably due to the new aether module being optional?

Not sure what you mean by that. Optional how?

**Comment by FroMage** [comment]
It's an optional import from the CMR. The old modules were forced imported in the eclipse plugin, perhaps.

**Comment by gavinking** [comment]
Well I tried adding it to the `META-INF` and to the module descriptor but neither helped.

**Comment by FroMage** [comment]
Got this stack to help:

```
Caused by: java.lang.ClassNotFoundException: com.redhat.ceylon.aether.codehaus.plexus.util.xml.pull.XmlPullParserException cannot be found by com.redhat.ceylon.module-resolver-aether_1.3.3.osgi-4-20170816-1320
```

**Comment by FroMage** [comment]
The manifest for the cmr-aether module appears correct, though:

```
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.9.8
Created-By: 1.8.0_66-internal (Oracle Corporation)
Bnd-LastModified: 1502889667997
Bundle-ManifestVersion: 2
Bundle-Name: com.redhat.ceylon.module-resolver-aether
Bundle-SymbolicName: com.redhat.ceylon.module-resolver-aether
Bundle-Version: 1.3.3.osgi-4-20170816-1320
DSTAMP: 20170816
Export-Package: com.redhat.ceylon.cmr.resolver.aether;version="1.3.3.o
 sgi-4-20170816-1320"
NOW: 201708161521
Originally-Created-By: 1.8.0_66-internal-b17 (Oracle Corporation)
Require-Bundle: com.redhat.ceylon.aether;bundle-version=3.3.9
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.7))"
TODAY: August 16 2017
Tool: Bnd-2.3.0.20140510-060958
TSTAMP: 1521
```

**Comment by FroMage** [comment]
And the exception class is there:

```
atlantis stephane 15:31 ceylon-ide-eclipse $ unzip -l site/target/repository/plugins/com.redhat.ceylon.aether_3.3.9.CEYLON-DEPENDENCIES-v1.jar |grep PullParser
     2911  2017-08-02 13:00   com/redhat/ceylon/aether/codehaus/plexus/util/xml/pull/XmlPullParser.class
     2206  2017-08-02 13:00   com/redhat/ceylon/aether/codehaus/plexus/util/xml/pull/XmlPullParserException.class

```

**Comment by FroMage** [comment]
And this is an Eclipse classloader, not a jboss modules one.

**Comment by FroMage** [comment]
AH, the manifest for the new aether module has a wildcard export package that is wrong (it does not include the shared packages):

```
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.9.8
Created-By: Apache Maven 3.3.9
Export-Package: com.redhat.ceylon.aether.*
Bundle-Vendor: Ceylon Project
Bundle-Version: 3.3.9.CEYLON-DEPENDENCIES-v1
Build-Jdk: 1.7.0_121
Built-By: stephane
Bundle-Name: Ceylon Aether, HTTP, and WebDAV dependencies
Bundle-ManifestVersion: 2
Bundle-License: http://www.apache.org/licenses/LICENSE-2.0.txt
Bundle-Description: A shaded fat jar including Aether, HTTP components
 , Sardine, and all dependencies.
Bundle-SymbolicName: com.redhat.ceylon.aether
Archiver-Version: Plexus Archiver
```

**Comment by FroMage** [comment]
So, who creates this manifest?

**Comment by FroMage** [comment]
That's done in the distrib

**Comment by FroMage** [comment]
DAMNIT.

**Comment by FroMage** [comment]
Meh, that line was added by you @gavinking ;) Lemme remove it and see if that fixes the issue.

**Comment by gavinking** [comment]
@FroMage which line?

**Comment by gavinking** [comment]
This one?

> Export-Package: com.redhat.ceylon.aether.*

**Comment by gavinking** [comment]
Wasn't added by me, I don't think, I guess it was generated by the Maven shade plugin. (Look at `ceylon/aether/pom.xml`.)

**Comment by gavinking** [comment]
Oh, no, you're right, it *is* explicit in the `pom.xml` file, so it *was* me.

**Comment by FroMage** [comment]
So I fixed the `Export-Package`, but the jar that ends up in the Eclipse plugin's build is not the one that comes from the distrib, and that one still has it. Or it's put back by _something_. The distrib one is fine, though.

**Comment by FroMage** [comment]
Where could it possibly come from????

**Comment by FroMage** [comment]
I rebuilt it all and it keeps coming back. I've no idea where it comes from.

**Comment by gavinking** [comment]
Oh, I forgot: generation of the shaded jar isn't part of the build. We have to manually copy the jar over!

**Comment by FroMage** [comment]
No I put it there myself, that's not it.

**Comment by gavinking** [comment]
oh.

**Comment by FroMage** [comment]
Try it yourself, you'll get the same issue: `ceylon/dist/osgi/build/dist/plugins/com.redhat.ceylon.aether_3.3.9.CEYLON-DEPENDENCIES-v1.jar` is fine, but `ceylon-ide-eclipse/site/target/repository/plugins/com.redhat.ceylon.aether_3.3.9.CEYLON-DEPENDENCIES-v1.jar` has the wrong manifest.

**Comment by FroMage** [comment]
and I've _no idea_ where that can come from.

**Comment by gavinking** [comment]
The Ant build rewrites the MANIFEST files of the jars.

**Comment by gavinking** [comment]
And I'm not sure but think it even runs BND on them.

**Comment by FroMage** [comment]
heh, it's worse: it gets that jar from _somewhere else_ because the manifest is entirely different. That jar in Eclipse is built in jdk7, while my jdk is 8.

**Comment by gavinking** [comment]
Perhaps if we add in explicit `Export-Package` tags to the shaded jar, they will be left alone by the build?

**Comment by FroMage** [comment]
No, I tried to change other tags to verify, like the license, and the change doesn't get carried over. Try it yourself, see if it carries the new manifest?

**Comment by FroMage** [comment]
I just pushed the shared jar copied to the runtime repo that I forgot.

**Comment by gavinking** [comment]
Trying now.

**Comment by FroMage** [comment]
For fun, I can even remove the jar from the ceylon distrib and Eclipse still compiles and gets that jar from _somewhere else_

**Comment by gavinking** [comment]
huh?!

**Comment by FroMage** [comment]
yes, it's that bad.

**Comment by FroMage** [comment]
and I've no other file named that way in my entire home dir.

**Comment by FroMage** [comment]
Well I'm fresh out of idea. I checked my entire FS for that file and it's not there (except in Eclipse plugin installations, but I don't think it can get it from there). I can't imagine it gets it from online either, because where would _that_ be?

**Comment by gavinking** [comment]
No, it's surely being created by the build.

**Comment by gavinking** [comment]
Have a look, for example, at what the `addRequiredOSGIHeaders` target does in `ceylon/dist/build.xml`.

**Comment by gavinking** [comment]
I suspect `bnd` is doing this.

**Comment by gavinking** [comment]
But @FroMage, the other thing I don't get is: what is wrong with that `Export-Package` header anyway? What *should* it be?

**Comment by gavinking** [comment]
Oh, `Export-Package` can't have wildcards, is that it?

**Comment by FroMage** [comment]
It should export everything including the shaded packages we're using.

**Comment by FroMage** [comment]
Oh damn you're right this is the right prefix. Duh. Such wasted time. Then why doesn't it work?

**Comment by gavinking** [comment]
> Then why doesn't it work?

Well my reading of the OSGi spec (which might be wrong), is that `Export-Package` doesn't support wildcards, and packages have to be enumerated explicitly.

OTOH, if I'm right and this line is being generated by the `bnd` tool, then I don't see why `bnd` would be generating something wrom.

So I'm confused.

**Comment by FroMage** [comment]
It's not generated, bnd is only called if there's no existing manifest.

**Comment by gavinking** [comment]
So where *the hell* does it come from?!

**Comment by FroMage** [comment]
No idea. Did you try ?

**Comment by FroMage** [comment]
HAHA FOUND IT!!!!

```
~/.m2/repository/p2/osgi/bundle/com.redhat.ceylon.aether
```

It had a slightly different name, that's why I didn't find it. So _that_'s where it's coming from (not the ceylon build dir).

**Comment by FroMage** [comment]
And when I remove that file, I confirm I can rebuild and the plugin works.

**Comment by FroMage** [comment]
So now, we have to figure out how to make that folder have a lesser precedence than the ceylon distrib.

**Comment by gavinking** [comment]
Ugh. OMG. So nuking the `.m2` dir is a bandaid solution?

**Comment by FroMage** [comment]
No clue.

**Comment by FroMage** [comment]
> Ugh. OMG. So nuking the .m2 dir is a bandaid solution?

At least `~/.m2/repository/p2` yes.

**Comment by FroMage** [comment]
Well, at least the error changed:

```
Caused by: java.lang.ClassNotFoundException: com.redhat.ceylon.aether.eclipse.aether.resolution.ArtifactResolutionException cannot be found by com.redhat.ceylon.module-resolver-aether_1.3.3.osgi-4-20170817-1250
```

**Comment by FroMage** [comment]
Of course, that package is now explicitly exported.

**Comment by FroMage** [comment]
Ah, my Eclipse installation still has the OLD OLD version with the wildcard. Brilliant.

**Comment by gavinking** [comment]
This is fixed, but all this wasted time has exposed a couple of issues with the build that really need fixing.

**Comment by gavinking** [comment]
See #1883.
