### ISSUE TITLE
Unable to install ceylon in eclipse 4.7

### ISSUE THREAD

**Issue by baberrehman** [ceylon/ceylon-ide-eclipse#1897]
I am following the instructions mentioned at https://ceylon-lang.org/documentation/1.3/ide/eclipse/install/ .
when installing ceylon for eclipse from https://ceylon-lang.org/eclipse/updatesite/ , I encounter the following error:

`Unable to read repository at https://ceylon-lang.org/eclipse/updatesite/content.xml.
Unable to read repository at https://ceylon-lang.org/eclipse/updatesite/content.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

I am using eclipse 4.7 and JRE 8, as mentioned at https://ceylon-lang.org/documentation/1.3/ide/eclipse/install/ .

**Comment by FroMage** [comment]
Hi, I've updated the certificate, can you try again?

**Comment by baberrehman** [comment]
Yes, it works now. Thanks!

**Comment by FroMage** [comment]
Great.
