### ISSUE TITLE
Store the typechecker, etc, for a Project in the CeylonNature

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#364]
I have a feeling it would be more elegant to keep the `Typechecker` and other project-specific state that is currently stored in static hashmaps in `CeylonBuilder` in the project's `CeylonNature`. @davidfestal does that sound right to you?

**Comment by davidfestal** [comment]
This issue is obsolete, since all those objects are now stored in the `CeylonProject` object in the `ceylon-ide-common` project.
