### ISSUE TITLE
Mouse over is not showing variable value while debuging

### ISSUE THREAD

**Issue by matejonnet** [ceylon/ceylon-ide-eclipse#417]
In Eclipse/Java while debuging, you can view varable value by moving a mouse over a variable.
Missing this in Ceylon.

**Comment by davidfestal** [comment]
Fixed by c8ddb805fe5b0467f217a2480669d22a1c764da0,  723d9050714ff1bdc6ea941f95bdddf27830313a, 2fa91dd3fb4260f9f0ba35d373d86ff29d10cfe8, f16bd7f375f9563eab264b4a1b159b07b2ce92aa and finally 9595624c1102890060f6fc51a933afd1c09c14fe
