### ISSUE TITLE
Confusing line number debug info

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-ide-eclipse#468]
It appears the compiler is generating code with line number information for overload methods (i.e. those which add a default parameter value, and then call the next overloaded method). 

This is a good thing because we need some way to debug the default value expressions. 

But currently it is confusing as we seem to enter the same method repeatedly, with no obvious indication that we're evaluating the defaulted method parameters (you *can* tell, by looking at the stack in the debug view, but that's not at all obvious, and you have to know how we munch method names to make any sense of it). So it there was some we we could indicate what's going on to the user, that would be nice.

**Comment by davidfestal** [comment]
mainly done. Closing. Please open individual issues for remaining cases
