### ISSUE TITLE
Convert Java to Ceylon when copy-pasting from Java to Ceylon file

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-ide-eclipse#519]
Would it be possible to do some trivial conversion between Java code to Ceylon code when copy-pasting from Java to a Ceylon unit?

`new Foo()` -> `Foo()`
`public class Bar implements Gee {}` -> `shared class Bar() satisfies Gee {}`
`@Override public void m(){}` -> `shared actual void m(){}`

If it's hard to do I guess it may not be worth it, but it's the sort of gimmick that awes people in conferences ;)

**Comment by bjansen** [comment]
Perhaps we can close this one?

**Comment by bjansen** [comment]
We have "Paste Java as Ceylon" now, closing.
