### ISSUE TITLE
Quick-fix when iterating Java collections

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-ide-eclipse#531]
http://m.infoworld.com/d/application-development/first-look-gavin-kings-ceylon-217197?page=0,1

We should detect that sort of error in the IDE and offer to use the interop module. Here I'm assuming the interop module has something to turn a Java Iterable into a Ceylon Iterable, right @quintesse?

**Comment by gavinking** [comment]
This won't be necessary when we do https://github.com/ceylon/ceylon-spec/issues/1283.

**Comment by bjansen** [comment]
Not necessary now that https://github.com/ceylon/ceylon/issues/4389 has been implemented.
