### ISSUE TITLE
Step filtering for certain language module methods

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-ide-eclipse#691]
When debugging something such as

    f(1); // where the argument is boxed

if I "step into" when on that line, I first step into `Integer.instance()`, which is not helpful: I really don't care about how the `int` is boxed. Eclipse has "Java > Debug > Step Filtering" which seems to be a way to avoid stepping into certain classes, packages etc.

We should have a list of classes/methods which are filtered like this. All the boxing and unboxing methods are obvious candidates, and I'm sure there will be others.

**Comment by davidfestal** [comment]
Done, mainly by managing each case specifically and explicitly, without skipping automatically locations without any line number, which would be a bad idea IMO.

Closing. Please open individual issues for use cases that would not be covered by the fixes.
