### ISSUE TITLE
Link with Editor doesn't work for module source files

### ISSUE THREAD

**Issue by ncorai** [ceylon/ceylon-ide-eclipse#727]
When adding a reference to a module the source files for that module are automatically downloaded. However, even when checking the "Link with Editor" option in Eclipse's Project Explorer, switching to a ceylon file in a module doesn't sync the source tree in the Project Explorer.

**Comment by gavinking** [comment]
I just tried this out and it seems to be working now (at least in the Ceylon Explorer). So closing.
