### ISSUE TITLE
"Open ... Type/Declaration" dialogs do not list Inner Java classes

### ISSUE THREAD

**Issue by ncorai** [ceylon/ceylon-ide-eclipse#768]
Public inner classes of imported Java classes do not get listed in the "*Open Ceylon Declaration*" / "*Open Ceylon or Java Type*" dialogs.

To help confirm where the issue lies, in my experience the inner type can be imported and used within Ceylon files without problems, it's just the dialogs that come up empty.

**Comment by gavinking** [comment]
This was fixed a while ago by adding an option to search for member declarations to the dialog.
