### ISSUE TITLE
nightly snapshot update site

### ISSUE THREAD

**Issue by djeang** [ceylon/ceylon-ide-eclipse#809]
Hi,

I am currently working on CeylonFx and i find the ide hardly workable when going to project with a certain size. 
I guess that a lot of improvements has been done since this realease so i would find convenient to use a more recent version (even unstable) without building the plugin myself.
By the way, is next official version still planned for Janvuary 2014 ?

**Comment by davidfestal** [comment]
@djeang : Can we close this one ?

**Comment by djeang** [comment]
@davidfestal  : Yes. Indeed.

**Comment by davidfestal** [comment]
OK, let me do it then.
