### ISSUE TITLE
Source attachments open with Java editor

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-ide-eclipse#831]
When you open a class file that has a Ceylon source attachment, the source is opened in the Java editor.

### How to reproduce
* In any Ceylon project, expand “Ceylon Language Module - 1.0.0” > “ceylon.language-1.0.0.car” > “ceylon.language” > “abstract_.class”, **or**
* When debugging, step into a method or function in `ceylon.language` that’s implemented in Ceylon (for example, `List.equals` of `print({1} == {1})`)

![Screenshot](https://f.cloud.github.com/assets/2346599/2093218/b3c7a344-8eb5-11e3-9478-801aef8dad49.png) – as you can see, annotations aren’t colored, multi-line (doc) strings don’t work, etc.

**Comment by davidfestal** [comment]
Broken again !

**Comment by davidfestal** [comment]
Well, not really. It's when you navigate to a Ceylon class file from a Java class file located inside a Ceylon binary archive. Let me open another issue
