### ISSUE TITLE
Renaming a type should rename values of that type

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#867]
Given:

    class Foo() {}

    Foo foo = Foo();

If I rename `Foo` to `Bar`, the wizard should suggest you select `foo` for renaming, resulting in:

    class Bar() {}

    Bar bar = Bar();
 
This is a nice feature of IntelliJ that we should copy.

Note that this probably isn't suitable for linked mode rename, it should be a feature of the dialog-based rename.

**Comment by PhiLhoSoft** [comment]
Actually, in Eclipse for Java, if you rename `FooBar` to `FooBaz` and have a declaration `FooBar fooBaz`, even in inline mode, it will rename the variable(s) to `fooBaz`, without asking. Something that makes sense, so I am not annoyed it doesn't ask (or perhaps it just remember / apply the last settings in the Rename Factoring dialog). And I can rename the variable later, in the unlikely case I want to keep the old name. Eclipse even renames the accessors (it makes even more sense, of course).

I agree that the linked mode is extremely useful, I use it almost exclusively as it is very fast.
Something that I asked in the past, IIRC, and I want to remind, it to avoid selecting the whole identifier when renaming in linked mode. 99% of the time, I only want to change a character or two, so I click on the place where I want to do the change, and hit Ctrl+Alt+R. I expect, like in Java, to just start editing my name, but instead I get the whole identifier selected.
This is useless (how many times do you type an entirely different name?) and annoying (I have to navigate back, with mouse or cursor keys, to the point I were).

If you feel this belongs to a new issue ([Inline rename](https://github.com/ceylon/ceylon-ide-eclipse/issues/177) is closed), tell me, I will create a new one.

**Comment by gavinking** [comment]
@PhiLhoSoft I have added a toggle, just especially for you: @1c4465a6c2d0ae08e8f0235abbc5a95b7b462117.

**Comment by PhiLhoSoft** [comment]
Many thanks! (that was fast!) ;-)

**Comment by gavinking** [comment]
The guts of this is now done, though it could be improved in various ways by adding additional options.

**Comment by gavinking** [comment]
I'm done on this for now. If anyone wants some additional refinement to this functionality, they can open a new issue. Closing, finally!
