### ISSUE TITLE
Model loader issue with zipPairs

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-ide-eclipse#917]
Originally reported as ceylon/ceylon-compiler#1582 but it is specific to the IDE: It seems the model of `zipPairs()` is different in the IDE model from how it appears in the CLI model.

**Comment by davidfestal** [comment]
@lucaswerkmeister , @gavinking , @tombentley , @FroMage : it seems that the original issue was fixed, which would explain why @lucaswerkmeister couldn't reproduce it.
Do you think we can close it now ?

**Comment by gavinking** [comment]
Fine by me.

**Comment by tombentley** [comment]
Let's close it then!
