### ISSUE TITLE
Depend on ceylon-ide-common; move general (non-Eclipse-dependent) IDE code there as needed

### ISSUE THREAD

**Issue by mmazi** [ceylon/ceylon-ide-eclipse#963]
The [ceylon-ide-common](/ceylon/ceylon-ide-common) project was created when work on the IntelliJ IDE plugin was started to hold any IDE code that can be used by any IDE and is not dependent on a specific IDE (eg. Eclipse).

ceylon-ide-eclipse should include ceylon-ide-common as a dependency and use its classes where possible.

**Comment by bjansen** [comment]
This is now obsolete, closing.
