### ISSUE TITLE
--maven-overrides for IDE, reloaded

### ISSUE THREAD

**Issue by jpragey** [ceylon/ceylon-ide-eclipse#984]
A few weeks ago issue #965 proposed it but was abandoned a bit hastily. Recently Hibernate started to work (https://github.com/ceylon/ceylon-runtime/issues/57) with a *tiny* (5 lines) maven overrides... but only in command line, IDE having no maven-overrides option.
Maven override can't probably solve easily complex dependencies conflicts, but for simple cases it's worth having it. And compatibility with a popular ORM would be a BIG advantage for ceylon 1.1.

**Comment by gavinking** [comment]
@davidfestal has added support to the IDE for the new `overrides.xml` file. The old `mavenoverrides` thingy is now obsolete. Closing.
